INSERT INTO `verbal` (`category`, `type`, `word`, `question`, `correct_answer`, `wrong_answer1`, `wrong_answer2`, `wrong_answer3`, `explanation`) VALUES
('Word Meaning and Usage', 'Definition', 'Abandon', 'What does "Abandon" mean?', 'To leave something completely and permanently', 'To keep something carefully and securely', 'To take responsibility and care for', 'To delay or postpone indefinitely', 'Abandon means to leave or give up something fully.'),
('Word Meaning and Usage', 'Definition', 'Adoption', 'What does "Adoption" mean?', 'The act of legally taking another’s child as one’s own', 'The refusal to accept or recognize officially', 'A temporary arrangement without formal approval', 'An informal agreement without legal standing', 'Adoption is legally taking someone’s child into your family.'),
('Word Meaning and Usage', 'Definition', 'Abandonment', 'What does "Abandonment" mean?', 'The act of leaving something or someone behind', 'The act of protecting and nurturing closely', 'A voluntary commitment to stay and care', 'A consistent and ongoing support system', 'Abandonment means leaving behind someone or something.'),
('Word Meaning and Usage', 'Definition', 'Adulation', 'What does "Adulation" mean?', 'Excessive admiration or praise', 'Mild criticism with helpful suggestions', 'Complete neglect or disregard entirely', 'Balanced and honest feedback offered', 'Adulation means extreme and excessive praise.'),
('Word Meaning and Usage', 'Definition', 'Abate', 'What does "Abate" mean?', 'To lessen in intensity or amount', 'To increase sharply and rapidly', 'To maintain or keep at the same level', 'To encourage continuous growth actively', 'Abate means to reduce or decrease in strength.'),
('Word Meaning and Usage', 'Definition', 'Advance', 'What does "Advance" mean?', 'To move forward or make progress', 'To retreat backward or withdraw quickly', 'To stand still without any movement', 'To postpone or delay action indefinitely', 'Advance means to move ahead or improve progress.'),
('Word Meaning and Usage', 'Definition', 'Aberration', 'What does "Aberration" mean?', 'A deviation from the normal or expected', 'A strict adherence to established rules', 'A planned and carefully designed process', 'An absolute and unquestioned fact stated', 'Aberration means an unusual or abnormal deviation.'),
('Word Meaning and Usage', 'Definition', 'Adventurous', 'What does "Adventurous" mean?', 'Willing to take risks or try new things', 'Avoiding risks or any form of danger', 'Preferring to stay within comfort zones', 'Being cautious and hesitant to act', 'Adventurous means eager to explore or take risks.'),
('Word Meaning and Usage', 'Definition', 'Abhor', 'What does "Abhor" mean?', 'To regard with disgust or hatred', 'To admire greatly and respect deeply', 'To accept willingly without objection', 'To forget about completely and ignore', 'Abhor means to hate or detest intensely.'),
('Word Meaning and Usage', 'Definition', 'Adversarial', 'What does "Adversarial" mean?', 'Involving opposition or conflict', 'Friendly and cooperative in nature', 'Indifferent and uninterested attitude', 'Supportive and encouraging behavior', 'Adversarial relates to opposition or conflict.');


INSERT INTO `verbal` (`category`, `type`, `word`, `question`, `correct_answer`, `wrong_answer1`, `wrong_answer2`, `wrong_answer3`, `explanation`) VALUES
('Word Meaning and Usage', 'Definition', 'Abhorrent', 'What does "Abhorrent" mean?', 'Inspiring disgust and hatred', 'Causing admiration and respect', 'Being mildly unpleasant or boring', 'Arousing curiosity and interest', 'Abhorrent means something that causes disgust or hatred.'),
('Word Meaning and Usage', 'Definition', 'Adverse', 'What does "Adverse" mean?', 'Preventing success or development', 'Encouraging positive growth and change', 'Unrelated to the matter at hand', 'Indifferent or neutral in effect', 'Adverse means harmful or unfavorable.'),
('Word Meaning and Usage', 'Definition', 'Abilities', 'What does "Abilities" mean?', 'Skills or competence to do things', 'Lack of skills or proper knowledge', 'Physical features or appearances', 'Temporary conditions or states', 'Abilities are skills or capacities to perform tasks.'),
('Word Meaning and Usage', 'Definition', 'Adversity', 'What does "Adversity" mean?', 'Difficulties or misfortune', 'Comfort and ease in circumstances', 'Joy and celebration in events', 'Predictable and controlled situations', 'Adversity means facing hardship or misfortune.'),
('Word Meaning and Usage', 'Definition', 'Able', 'What does "Able" mean?', 'Having the power or skill to do something', 'Lacking strength or capability entirely', 'Being unwilling or uninterested', 'Physically present but inactive', 'Able means capable or having the ability to do something.'),
('Word Meaning and Usage', 'Definition', 'Advise', 'What does "Advise" mean?', 'To offer recommendations or suggestions', 'To order someone to do something strictly', 'To ignore requests or questions completely', 'To refuse to give any opinion or help', 'Advise means to give suggestions or guidance.'),
('Word Meaning and Usage', 'Definition', 'Abnormal', 'What does "Abnormal" mean?', 'Not usual or typical', 'Common and expected behavior', 'Normal and regular in pattern', 'Typical and widely accepted', 'Abnormal means deviating from the norm.'),
('Word Meaning and Usage', 'Definition', 'Advocate', 'What does "Advocate" mean?', 'To publicly support or recommend', 'To oppose or reject strongly', 'To ignore or neglect completely', 'To criticize without offering help', 'Advocate means to support or argue for something publicly.'),
('Word Meaning and Usage', 'Definition', 'Abolish', 'What does "Abolish" mean?', 'To formally put an end to something', 'To create or start a new system', 'To maintain without any change', 'To temporarily suspend for a period', 'Abolish means to officially end or stop.'),
('Word Meaning and Usage', 'Definition', 'Aesthetic', 'What does "Aesthetic" mean?', 'Concerned with beauty or art', 'Related to practical or useful things', 'Focused on economic or financial gain', 'Ignoring appearance or style completely', 'Aesthetic relates to the appreciation of beauty.');
