
INSERT INTO `verbal` (`category`, `type`, `word`, `question`, `correct_answer`, `wrong_answer1`, `wrong_answer2`, `wrong_answer3`, `explanation`) VALUES
('Word Meaning and Usage', 'Definition', 'Abandon', 'What does "Abandon" mean?', 'To give up or leave something behind', 'To continue supporting despite all odds', 'To dedicate oneself and remain forever', 'To accept responsibility and never part ways', 'The word "Abandon" means to give up completely or to leave something or someone behind.'),
('Word Meaning and Usage', 'Definition', 'Adoption', 'What does "Adoption" mean?', 'The act of legally taking as one\'s own', 'The process of rejecting or discarding ideas', 'The act of distancing oneself from others', 'The practice of refusing new relationships', 'Adoption refers to the legal process of taking another’s child as one’s own or accepting something new.'),
('Word Meaning and Usage', 'Definition', 'Ancestor', 'What does "Ancestor" mean?', 'A person from whom one is descended', 'A close friend unrelated to family history', 'A future generation yet to be born', 'A distant colleague without blood ties', 'Ancestor refers to a person, usually more remote than a grandparent, from whom one is descended.'),
('Word Meaning and Usage', 'Definition', 'Assign', 'What does "Assign" mean?', 'To give a task or responsibility to someone', 'To refuse to delegate and do everything alone', 'To ignore duties and avoid all obligations', 'To accept work without distributing to others', 'Assign means to allocate a particular job or responsibility to someone.'),
('Word Meaning and Usage', 'Definition', 'Behalf', 'What does "Behalf" mean?', 'As a representative or for the interest of someone', 'For personal gain with no benefit to others', 'Against the wishes or approval of everyone', 'Working without representing any person or group', 'Behalf means acting for or in the interest of another person.');



INSERT INTO `verbal` (`category`, `type`, `word`, `question`, `correct_answer`, `wrong_answer1`, `wrong_answer2`, `wrong_answer3`, `explanation`) VALUES
('Word Meaning and Usage', 'Definition', 'Abhor', 'What does "Abhor" mean?', 'To regard with disgust or hatred', 'To admire and deeply appreciate', 'To misunderstand without any emotion', 'To accept gladly and celebrate', 'Abhor means to hate or feel disgust for something.'),
('Word Meaning and Usage', 'Definition', 'Adversarial', 'What does "Adversarial" mean?', 'Involving conflict or opposition', 'Promoting peaceful understanding always', 'Encouraging friendship and cooperation only', 'Showing indifference or lack of any stance', 'Adversarial means involving opposition or hostility.'),
('Word Meaning and Usage', 'Definition', 'Angel', 'What does "Angel" mean?', 'A spiritual being regarded as a messenger', 'A mischievous spirit known for trickery', 'An ordinary person without special power', 'A mythical creature from folklore tales', 'Angel means a spiritual being or messenger, often seen as kind and pure.'),
('Word Meaning and Usage', 'Definition', 'Assistance', 'What does "Assistance" mean?', 'The act of helping or supporting', 'The process of hindering or obstructing progress', 'The failure to recognize someone’s need', 'The act of ignoring requests for help', 'Assistance means giving help or support to someone.'),
('Word Meaning and Usage', 'Definition', 'Beloved', 'What does "Beloved" mean?', 'Dearly loved or cherished', 'Ignored or treated with indifference', 'Tolerated but never appreciated much', 'Criticized or scorned by many people', 'Beloved means someone who is dearly loved or cherished.'),
('Word Meaning and Usage', 'Definition', 'Abhorrent', 'What does "Abhorrent" mean?', 'Inspiring disgust or loathing', 'Causing deep admiration and respect', 'Eliciting laughter and positive feelings', 'Producing contentment and acceptance always', 'Abhorrent means causing hate or disgust.'),
('Word Meaning and Usage', 'Definition', 'Adverse', 'What does "Adverse" mean?', 'Harmful or unfavorable', 'Encouraging and highly beneficial', 'Neutral and neither good nor bad', 'Supporting improvement and great success', 'Adverse means harmful or unfavorable in effect.'),
('Word Meaning and Usage', 'Definition', 'Anger', 'What does "Anger" mean?', 'A strong feeling of displeasure', 'A sense of calm and relaxation always', 'An emotion of endless happiness only', 'A state of constant confusion without feeling', 'Anger is a strong feeling of annoyance or hostility.'),
('Word Meaning and Usage', 'Definition', 'Associate', 'What does "Associate" mean?', 'To connect or link in the mind', 'To deliberately separate and disconnect things', 'To misunderstand and keep unrelated always', 'To confuse and mix up unrelated ideas', 'Associate means to connect or bring things together in thought.'),
('Word Meaning and Usage', 'Definition', 'Below', 'What does "Below" mean?', 'In a lower place or position', 'At the same level or higher location', 'Within a completely different area altogether', 'Above and far away from the point in question', 'Below means in a lower position or beneath something.');

