INSERT INTO `verbal` (`category`, `type`, `sub_type`, `instruction`, `word`, `question`, `correct_answer`, `wrong_answer1`, `wrong_answer2`, `wrong_answer3`, `explanation`) VALUES
('Vocabulary and Meaning', 'Field-Specific Meaning', 'Biology', 'Identify the field-specific meaning of the given word in the context of its domain.', 'cell', 'In biology, what does the word "cell" specifically refer to?', 'The basic structural and functional unit of life', 'A small room in a prison for housing inmates', 'A portable device used for mobile communication', 'The power source compartment in electronic devices', 'In biology, a cell is the smallest unit of life that can replicate independently, forming the basis of all living organisms.'),
('Vocabulary and Meaning', 'Field-Specific Meaning', 'Law', 'Identify the field-specific meaning of the given word in the context of its domain.', 'appeal', 'In law, what does the word "appeal" specifically refer to?', 'A request for a higher court to review a decision', 'An urgent plea for assistance in emergencies', 'A compelling argument to persuade an audience', 'A strategic marketing approach to attract customers', 'An appeal is a formal legal request where a higher court reexamines a lower court’s decision for errors in procedure or judgment.'),
('Vocabulary and Meaning', 'Field-Specific Meaning', 'Physics', 'Identify the field-specific meaning of the given word in the context of its domain.', 'force', 'In physics, what does the word "force" specifically refer to?', 'A push or pull acting upon an object', 'Physical strength demonstrated by individuals', 'A specialized military unit for operations', 'Social influence affecting decisions', 'In physics, force (measured in Newtons) is any interaction that alters an object’s motion, direction, or shape when unopposed.'),
('Vocabulary and Meaning', 'Field-Specific Meaning', 'Economics', 'Identify the field-specific meaning of the given word in the context of its domain.', 'inflation', 'In economics, what does the term "inflation" refer to?', 'A general increase in prices and fall in purchasing value', 'Growth in national employment opportunities', 'Increased tax rates imposed by governments', 'Financial subsidies provided to industries', 'Inflation measures the sustained rise in the general price level of goods/services, eroding currency’s purchasing power over time.'),
('Vocabulary and Meaning', 'Field-Specific Meaning', 'Technology', 'Identify the field-specific meaning of the given word in the context of its domain.', 'firewall', 'In technology, what does the term "firewall" refer to?', 'A network security system monitoring traffic', 'A physical barrier designed to contain fires', 'Software that detects computer viruses', 'An application for internet browsing', 'A firewall is a security device/software that filters network traffic based on rules to prevent unauthorized access.'),
('Vocabulary and Meaning', 'Field-Specific Meaning', 'Mathematics', 'Identify the field-specific meaning of the given word in the context of its domain.', 'factor', 'In mathematics, what does the word "factor" refer to?', 'A number dividing another without remainder', 'A variable within algebraic expressions', 'An element contributing to outcomes', 'A procedure in scientific experiments', 'A factor is an integer that evenly divides another integer (e.g., 3 and 4 are factors of 12).'),
('Vocabulary and Meaning', 'Field-Specific Meaning', 'Geography', 'Identify the field-specific meaning of the given word in the context of its domain.', 'delta', 'In geography, what does the term "delta" refer to?', 'A landform at the mouth of a river', 'The highest peak of a mountain range', 'A directional ocean current pattern', 'An arid region lacking precipitation', 'A delta forms when river-deposited sediments accumulate at a river mouth, creating triangular-shaped fertile land.'),
('Vocabulary and Meaning', 'Field-Specific Meaning', 'Education', 'Identify the field-specific meaning of the given word in the context of its domain.', 'curriculum', 'In education, what does the term "curriculum" refer to?', 'The subjects comprising a course of study', 'A daily schedule of classroom activities', 'An instructor’s plan for teaching lessons', 'A system for evaluating student performance', 'Curriculum encompasses all planned learning experiences, including subjects, materials, and assessments.'),
('Vocabulary and Meaning', 'Field-Specific Meaning', 'Psychology', 'Identify the field-specific meaning of the given word in the context of its domain.', 'motivation', 'In psychology, what does the term "motivation" refer to?', 'The reason behind a person’s actions', 'Consequences discouraging unwanted behavior', 'Techniques for effective knowledge acquisition', 'External stimuli triggering physiological responses', 'Motivation describes the internal/external drives initiating and sustaining goal-oriented behaviors.'),
('Vocabulary and Meaning', 'Field-Specific Meaning', 'Sociology', 'Identify the field-specific meaning of the given word in the context of its domain.', 'norms', 'In sociology, what does the term "norms" refer to?', 'Accepted standards of behavior in society', 'Statistical measures of central tendency', 'Regulations enforced by legal systems', 'Core doctrines of religious faiths', 'Norms are unwritten societal rules dictating acceptable conduct within groups/cultures.');