
INSERT INTO `verbal` (`category`, `type`, `word`, `question`, `correct_answer`, `wrong_answer1`, `wrong_answer2`, `wrong_answer3`, `explanation`) VALUES
('Grammar and Structure', 'Correct  Comparative Form', 'convenient', 'E-filing is _____ than manual submission.', 'more convenient', 'convenienter', 'convenient', 'most convenient', '3+ syllable adjectives use \"more\" (convenient → more convenient).'),
('Grammar and Structure', 'Correct  Comparative Form', 'bad', 'Traffic is _____ during monsoon season.', 'worse', 'badder', 'more bad', 'worst', '\"Bad\" has irregular comparative form: bad → worse.'),
('Grammar and Structure', 'Correct  Comparative Form', 'good', 'Digital systems yield _____ results.', 'better', 'gooder', 'more good', 'best', '\"Good\" has irregular comparative: good → better.'),
('Grammar and Structure', 'Correct  Comparative Form', 'little', 'This project requires _____ funding.', 'less', 'least', 'littler', 'lesser', '\"Little\" (uncountable) becomes \"less\". \"Littler\" is for physical size.'),
('Grammar and Structure', 'Correct  Comparative Form', 'many', 'New offices have _____ employees.', 'more', 'many', 'much', 'most', '\"Many/much\" become \"more\" in comparatives.'),
('Grammar and Structure', 'Correct  Comparative Form', 'far', 'Cordillera is _____ from Manila than Bicol.', 'farther', 'farer', 'more far', 'further', 'Physical distance uses \"farther\". \"Further\" is metaphorical.'),
('Grammar and Structure', 'Correct  Comparative Form', 'easy', 'Online exams are _____ to administer.', 'easier', 'more easy', 'more easier', 'easiest', '2-syllable adjectives ending in -y change to -ier (easy → easier).'),
('Grammar and Structure', 'Correct  Comparative Form', 'simple', 'The new process is _____ to follow.', 'simpler', 'more simple', 'simplest', 'more simpler', '2-syllable adjectives often take -er (simple → simpler).'),
('Grammar and Structure', 'Correct  Comparative Form', 'important', 'Punctuality is _____ than paperwork.', 'more important', 'importanter', 'important', 'most important', '3+ syllable adjectives use \"more\" (important → more important).'),
('Grammar and Structure', 'Correct  Comparative Form', 'busy', 'Manila is _____ than Iloilo City.', 'busier', 'more busy', 'busyer', 'bussier', 'Adjectives ending in -y change to -ier (busy → busier).'),
('Grammar and Structure', 'Correct  Comparative Form', 'thin', 'New laptops are _____ than old models.', 'thinner', 'thiner', 'more thin', 'thinest', 'One-syllable adjectives with CVC pattern double last letter (thin → thinner).'),
('Grammar and Structure', 'Correct  Comparative Form', 'beautiful', 'Batanes is _____ than expected.', 'more beautiful', 'beautifuller', 'beautifuler', 'most beautiful', '3+ syllable adjectives require \"more\" (beautiful → more beautiful).'),
('Grammar and Structure', 'Correct  Comparative Form', 'early', 'CSC applicants arrive _____ than required.', 'earlier', 'early', 'more early', 'earliest', 'Adverbs ending in -ly use \"more\", but \"early\" is exception (earlier).'),
('Grammar and Structure', 'Correct  Comparative Form', 'old', 'Traditional methods are _____ than digital ones.', 'older', 'elder', 'more old', 'oldest', '\"Older\" for things/people; \"elder\" for family hierarchy.'),
('Grammar and Structure', 'Correct  Comparative Form', 'much', 'Senior staff have _____ experience.', 'more', 'much', 'many', 'most', 'Uncountable nouns use \"more\" (much → more).'),
('Grammar and Structure', 'Correct  Comparative Form', 'clever', 'The new software is _____ than the legacy system.', 'cleverer', 'more clever', 'clever', 'cleverest', 'Some 2-syllable adjectives take -er (clever → cleverer).'),
('Grammar and Structure', 'Correct  Comparative Form', 'narrow', 'Provincial roads are _____ than expressways.', 'narrower', 'more narrow', 'narrow', 'narrowest', '2-syllable adjectives ending in -ow add -er (narrow → narrower).'),
('Grammar and Structure', 'Correct  Comparative Form', 'friendly', 'Rural offices are _____ than urban ones.', 'friendlier', 'friendlyer', 'more friendly', 'more friendlier', '-y adjectives become -ier (friendly → friendlier).'),
('Grammar and Structure', 'Correct  Comparative Form', 'polite', 'Written requests should be _____ than verbal ones.', 'more polite', 'politer', 'politest', 'polite', 'Most 2-syllable adjectives use \"more\" (polite → more polite).'),
('Grammar and Structure', 'Correct  Comparative Form', 'badly', 'The printer performs _____ during brownouts.', 'worse', 'more badly', 'badder', 'worst', 'Irregular adverb: badly → worse.'),
('Grammar and Structure', 'Correct  Comparative Form', 'well', 'Trained officers perform _____.', 'better', 'gooder', 'more well', 'best', '\"Well\" (adverb) has irregular comparative: well → better.'),
('Grammar and Structure', 'Correct  Comparative Form', 'careful', 'Documentation requires _____ handling.', 'more careful', 'carefuller', 'carefuler', 'carefulest', '2-syllable adjectives not ending in -y use \"more\" (careful → more careful).'),
('Grammar and Structure', 'Correct  Comparative Form', 'big', 'Metro Manila has _____ population than Davao.', 'bigger', 'biger', 'more big', 'biggest', 'One-syllable CVC adjectives double last letter (big → bigger).'),
('Grammar and Structure', 'Correct  Comparative Form', 'lazy', 'Automation makes workers _____.', 'lazier', 'more lazy', 'lazy', 'more lazier', '-y adjectives become -ier (lazy → lazier).'),
('Grammar and Structure', 'Correct  Comparative Form', 'few', 'Private companies have _____ holidays than government.', 'fewer', 'less', 'few', 'least', 'Countable nouns use \"fewer\" (few → fewer).'),
('Grammar and Structure', 'Correct  Comparative Form', 'expensive', 'Imported equipment is _____ than local versions.', 'more expensive', 'expensiver', 'expensive', 'most expensive', '3-syllable adjectives use \"more\" (expensive → more expensive).'),
('Grammar and Structure', 'Correct  Comparative Form', 'sad', 'Budget cuts made the meeting _____ than usual.', 'sadder', 'sader', 'more sad', 'saddest', 'CVC adjectives double last consonant (sad → sadder).'),
('Grammar and Structure', 'Correct  Comparative Form', 'hot', 'April is _____ than January in the Philippines.', 'hotter', 'hoter', 'more hot', 'hottest', 'One-syllable CVC adjectives double last letter (hot → hotter).'),
('Grammar and Structure', 'Correct  Comparative Form', 'intelligent', 'Promotion exams are _____ than entry tests.', 'more intelligent', 'intelligenter', 'intelligent', 'most intelligent', '3+ syllable adjectives require \"more\" (intelligent → more intelligent).'),
('Grammar and Structure', 'Correct  Comparative Form', 'heavy', 'Logistical equipment is _____ than documents.', 'heavier', 'heavyer', 'more heavy', 'heaviest', '-y adjectives become -ier (heavy → heavier).'),
('Grammar and Structure', 'Correct  Comparative Form', 'dangerous', 'Fieldwork is _____ than desk jobs.', 'more dangerous', 'dangerouser', 'dangerous', 'most dangerous', '3-syllable adjectives use \"more\" (dangerous → more dangerous).'),
('Grammar and Structure', 'Correct  Comparative Form', 'fast', 'Digital processing is _____ than manual.', 'faster', 'fast', 'more fast', 'fastest', 'One-syllable adjectives add -er (fast → faster).'),
('Grammar and Structure', 'Correct  Comparative Form', 'modern', 'The new building is _____ than the old one.', 'more modern', 'moderner', 'modern', 'most modern', '2-syllable adjectives ending in -n often use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'quiet', 'Provincial offices are _____ than city branches.', 'quieter', 'quiet', 'more quiet', 'more quieter', '2-syllable adjectives can take -er (quiet → quieter).'),
('Grammar and Structure', 'Correct  Comparative Form', 'tidy', 'Electronic files are _____ than paper records.', 'tidier', 'tidy', 'more tidy', 'more tidier', '-y adjectives become -ier (tidy → tidier).'),
('Grammar and Structure', 'Correct  Comparative Form', 'useful', 'Mobile apps are _____ than printed manuals.', 'more useful', 'usefuller', 'useful', 'usefullest', '2-syllable adjectives ending in -ful use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'clean', 'Government hospitals are _____ than before.', 'cleaner', 'clean', 'more clean', 'cleanest', 'One-syllable adjectives add -er (clean → cleaner).'),
('Grammar and Structure', 'Correct  Comparative Form', 'bright', 'LED lights are _____ than fluorescent bulbs.', 'brighter', 'brigher', 'more bright', 'brightest', 'One-syllable adjectives add -er (bright → brighter).'),
('Grammar and Structure', 'Correct  Comparative Form', 'shallow', 'Coastal waters are _____ in Boracay than Palawan.', 'shallower', 'shallow', 'more shallow', 'shallowest', '2-syllable adjectives ending in -ow add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'wise', 'Veteran employees offer _____ advice.', 'wiser', 'wise', 'more wise', 'wisest', 'One-syllable adjectives add -er (wise → wiser).'),
('Grammar and Structure', 'Correct  Comparative Form', 'serious', 'Cyber threats are _____ than physical breaches.', 'more serious', 'seriouser', 'serious', 'seriousest', '3-syllable adjectives use \"more\" (serious → more serious).'),
('Grammar and Structure', 'Correct  Comparative Form', 'long', 'Procurement takes _____ time than approval.', 'longer', 'long', 'more long', 'longest', 'One-syllable adjectives add -er (long → longer).'),
('Grammar and Structure', 'Correct  Comparative Form', 'noisy', 'Urban centers are _____ than rural areas.', 'noisier', 'noisy', 'more noisy', 'more noisier', '-y adjectives become -ier (noisy → noisier).'),
('Grammar and Structure', 'Correct  Comparative Form', 'brave', 'Frontliners are _____ than we acknowledge.', 'braver', 'brave', 'more brave', 'bravest', 'One-syllable adjectives add -er (brave → braver).'),
('Grammar and Structure', 'Correct  Comparative Form', 'common', 'Online scams are _____ than offline fraud.', 'more common', 'commoner', 'common', 'commonest', '2-syllable adjectives can use \"more\" or -er. \"More common\" preferred.'),
('Grammar and Structure', 'Correct  Comparative Form', 'gentle', 'Revised guidelines are _____ than previous rules.', 'gentler', 'gentle', 'more gentle', 'more gentler', '2-syllable adjectives often take -er (gentle → gentler).'),
('Grammar and Structure', 'Correct  Comparative Form', 'soon', 'Digital services will launch _____ than planned.', 'sooner', 'soon', 'more soon', 'soonest', 'One-syllable adverbs add -er (soon → sooner).'),
('Grammar and Structure', 'Correct  Comparative Form', 'often', 'Seniors use portals _____ than juniors.', 'more often', 'oftener', 'often', 'oftenest', 'Formal English prefers \"more often\" for 2+ syllable adverbs.'),
('Grammar and Structure', 'Correct  Comparative Form', 'late', 'Night shifts end _____ than day shifts.', 'later', 'late', 'more late', 'latest', 'One-syllable adjectives/adverbs add -er (late → later).'),
('Grammar and Structure', 'Correct  Comparative Form', 'risky', 'Field assignments are _____ than office tasks.', 'riskier', 'risky', 'more risky', 'more riskier', '-y adjectives become -ier (risky → riskier).'),
('Grammar and Structure', 'Correct  Comparative Form', 'tall', 'The Banaue Rice Terraces are _____ than most modern agricultural structures.', 'taller', 'more tall', 'tallest', 'most tall', 'One-syllable adjectives add -er. \"More tall\" is grammatically incorrect.'),
('Grammar and Structure', 'Correct  Comparative Form', 'efficient', 'Digital processing is _____ than manual methods.', 'more efficient', 'efficienter', 'efficient', 'most efficient', '3+ syllable adjectives require \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'far', 'Palawan is _____ from Manila than Bohol.', 'farther', 'further', 'more far', 'farer', '\"Farther\" for physical distance. \"Further\" is for metaphorical distance.'),
('Grammar and Structure', 'Correct  Comparative Form', 'wealthy', 'Makati has _____ residents than most provinces.', 'wealthier', 'wealthyer', 'more wealthy', 'more wealthier', '-y adjectives change to -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'complex', 'Tax regulations are _____ than before.', 'more complex', 'complexer', 'complexxer', 'most complex', '3+ syllable adjectives use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'simple', 'The new protocol is _____ to implement.', 'simpler', 'more simple', 'simplest', 'more simpler', '2-syllable adjectives often take -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'bad', 'Pollution levels are _____ during summer.', 'worse', 'more bad', 'badder', 'worst', 'Irregular comparative: bad → worse.'),
('Grammar and Structure', 'Correct  Comparative Form', 'little', 'Rural clinics have _____ equipment than urban hospitals.', 'less', 'fewer', 'littler', 'least', '\"Less\" for uncountable nouns. \"Fewer\" for countable items.'),
('Grammar and Structure', 'Correct  Comparative Form', 'busy', 'EDSA is _____ during rush hour than other highways.', 'busier', 'busyer', 'more busy', 'bussier', '-y adjectives become -ier (busy → busier).'),
('Grammar and Structure', 'Correct  Comparative Form', 'humid', 'July is _____ than March in the Philippines.', 'more humid', 'humidier', 'humider', 'most humid', '2-syllable adjectives not ending in -y use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'old', 'Traditional farming techniques are _____ than modern ones.', 'older', 'elder', 'more old', 'oldest', '\"Older\" for objects/age. \"Elder\" for family hierarchy.'),
('Grammar and Structure', 'Correct  Comparative Form', 'smart', 'The new AI system is _____ than its predecessor.', 'smarter', 'more smart', 'smartter', 'smartest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'dangerous', 'Mountain rescue is _____ than office work.', 'more dangerous', 'dangerouser', 'dangerous', 'most dangerous', '3+ syllable adjectives require \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'thin', 'Modern smartphones are _____ than older models.', 'thinner', 'thiner', 'more thin', 'thinnest', 'CVC words double final consonant.'),
('Grammar and Structure', 'Correct  Comparative Form', 'common', 'Typhoons are becoming _____ in the Pacific.', 'more common', 'commoner', 'common', 'commonest', 'Formal preference: \"more\" for 2-syllable adjectives.'),
('Grammar and Structure', 'Correct  Comparative Form', 'early', 'Government employees arrive _____ than private sector workers.', 'earlier', 'more early', 'early', 'earliest', '\"Early\" → \"earlier\" (exception to -ly rule).'),
('Grammar and Structure', 'Correct  Comparative Form', 'well', 'Trained responders perform _____ in emergencies.', 'better', 'gooder', 'more well', 'best', 'Irregular form: well → better.'),
('Grammar and Structure', 'Correct  Comparative Form', 'heavy', 'Monsoon rains are _____ this year than last.', 'heavier', 'heavyer', 'more heavy', 'heaviest', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'reliable', 'Fiber internet is _____ than satellite connections.', 'more reliable', 'reliableer', 'reliabler', 'most reliable', '3+ syllable adjectives use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'big', 'Metro Manila has _____ population density than Cebu.', 'bigger', 'biger', 'more big', 'biggest', 'CVC words double final consonant.'),
('Grammar and Structure', 'Correct  Comparative Form', 'polite', 'Written complaints should be _____ than verbal ones.', 'more polite', 'politer', 'politest', 'polite', '2-syllable adjectives often use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'soon', 'Digital services will be implemented _____ than expected.', 'sooner', 'more soon', 'soonest', 'early', 'One-syllable adverb: soon → sooner.'),
('Grammar and Structure', 'Correct  Comparative Form', 'few', 'Island municipalities have _____ resources than mainland cities.', 'fewer', 'less', 'few', 'least', '\"Fewer\" for countable nouns.'),
('Grammar and Structure', 'Correct  Comparative Form', 'sad', 'The audit results were _____ than predicted.', 'sadder', 'sader', 'more sad', 'saddest', 'CVC words double final consonant.'),
('Grammar and Structure', 'Correct  Comparative Form', 'clean', 'Renewable energy is _____ than fossil fuels.', 'cleaner', 'more clean', 'cleanest', 'cleanner', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'wise', 'Veteran employees give _____ advice than new hires.', 'wiser', 'more wise', 'wise', 'wisest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'expensive', 'Imported goods are _____ than local products.', 'more expensive', 'expensiver', 'expensive', 'most expensive', '3+ syllable adjectives use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'hot', 'April is _____ than December in the Philippines.', 'hotter', 'hoter', 'more hot', 'hottest', 'CVC words double final consonant.'),
('Grammar and Structure', 'Correct  Comparative Form', 'loud', 'City centers are _____ at night than rural areas.', 'louder', 'loud', 'more loud', 'loudest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'peaceful', 'Provincial life is _____ than city living.', 'more peaceful', 'peacefuller', 'peacefuler', 'most peaceful', '3+ syllable adjectives require \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'quick', 'Online applications process _____ than paper forms.', 'quicker', 'more quick', 'quickly', 'quickest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'healthy', 'Organic produce is _____ than conventional alternatives.', 'healthier', 'healthyer', 'more healthy', 'more healthier', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'modern', 'The new facility is _____ than the old headquarters.', 'more modern', 'moderner', 'modern', 'most modern', '2-syllable adjectives often use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'bright', 'LED bulbs are _____ than incandescent lights.', 'brighter', 'brigher', 'more bright', 'brightest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'calm', 'Coastal areas are _____ during off-season months.', 'calmer', 'calm', 'more calm', 'calmest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'shallow', 'Beaches in Boracay are _____ than in Siargao.', 'shallower', 'shallow', 'more shallow', 'shallowest', '2-syllable adjectives ending in -ow add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'dry', 'Summer months are _____ than rainy season.', 'drier', 'dryer', 'more dry', 'driest', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'strict', 'Banking regulations are _____ than before.', 'stricter', 'strict', 'more strict', 'strictest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'noisy', 'Urban markets are _____ than suburban malls.', 'noisier', 'noisy', 'more noisy', 'more noisier', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'safe', 'Gated communities are _____ than open neighborhoods.', 'safer', 'safe', 'more safe', 'safest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'important', 'Data privacy is _____ than ever before.', 'more important', 'importanter', 'important', 'most important', '3+ syllable adjectives require \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'cold', 'Baguio is _____ than Manila during December.', 'colder', 'cold', 'more cold', 'coldest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'friendly', 'Provincial locals are _____ than city residents.', 'friendlier', 'friendlyer', 'more friendly', 'more friendlier', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'long', 'Coastal highways are _____ than inland routes.', 'longer', 'long', 'more long', 'longest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'brave', 'Frontline workers are _____ than we acknowledge.', 'braver', 'brave', 'more brave', 'bravest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'often', 'Digital natives use apps _____ than seniors.', 'more often', 'oftener', 'often', 'oftenest', 'Formal preference: \"more\" for 2-syllable adverbs.'),
('Grammar and Structure', 'Correct  Comparative Form', 'risky', 'Construction work is _____ than administrative jobs.', 'riskier', 'risky', 'more risky', 'more riskier', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'smooth', 'The new system runs _____ than the legacy software.', 'smoother', 'smooth', 'more smooth', 'smoothest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'gentle', 'Revised policies are _____ than previous versions.', 'gentler', 'gentle', 'more gentle', 'gentlest', '2-syllable adjectives often take -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'clever', 'The new algorithm is _____ than traditional methods.', 'cleverer', 'clever', 'more clever', 'cleverest', 'Some 2-syllable adjectives take -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'near', 'Provincial capitals are _____ to rural areas than national offices.', 'nearer', 'near', 'more near', 'nearest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'wide', 'Expressways are _____ than provincial roads.', 'wider', 'wide', 'more wide', 'widest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'young', 'New recruits are _____ than retiring officers.', 'younger', 'young', 'more young', 'youngest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'high', 'Mount Mayon is _____ than Taal Volcano.', 'higher', 'more high', 'high', 'most high', 'One-syllable adjectives add -er (high → higher).'),
('Grammar and Structure', 'Correct  Comparative Form', 'efficient', 'E-governance is _____ than traditional systems.', 'more efficient', 'efficienter', 'efficient', 'most efficient', '3+ syllable adjectives use \"more\" (efficient → more efficient).'),
('Grammar and Structure', 'Correct  Comparative Form', 'far', 'Tawi-Tawi is _____ from Manila than Palawan.', 'farther', 'further', 'more far', 'farer', '\"Farther\" for physical distance.'),
('Grammar and Structure', 'Correct  Comparative Form', 'wealthy', 'Fort Bonifacio has _____ residents than Tondo.', 'wealthier', 'wealthyer', 'more wealthy', 'more wealthier', '-y adjectives change to -ier (wealthy → wealthier).'),
('Grammar and Structure', 'Correct  Comparative Form', 'complex', 'Tax codes are _____ than before.', 'more complex', 'complexer', 'complexxer', 'most complex', '3+ syllable adjectives require \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'simple', 'Online voting is _____ to implement.', 'simpler', 'more simple', 'simplest', 'more simpler', '2-syllable adjectives often take -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'bad', 'Traffic congestion is _____ during holidays.', 'worse', 'more bad', 'badder', 'worst', 'Irregular comparative: bad → worse.'),
('Grammar and Structure', 'Correct  Comparative Form', 'little', 'Rural schools have _____ funding than city schools.', 'less', 'fewer', 'littler', 'least', '\"Less\" for uncountable nouns.'),
('Grammar and Structure', 'Correct  Comparative Form', 'busy', 'Makati CBD is _____ than Ortigas Center.', 'busier', 'busyer', 'more busy', 'bussier', '-y adjectives become -ier (busy → busier).'),
('Grammar and Structure', 'Correct  Comparative Form', 'humid', 'August is _____ than May in the Philippines.', 'more humid', 'humidier', 'humider', 'most humid', '2-syllable adjectives not ending in -y use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'old', 'Intramuros is _____ than Bonifacio Global City.', 'older', 'elder', 'more old', 'oldest', '\"Older\" for objects/age.'),
('Grammar and Structure', 'Correct  Comparative Form', 'smart', 'New biometric systems are _____ than passwords.', 'smarter', 'more smart', 'smartter', 'smartest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'dangerous', 'Mining sites are _____ than office environments.', 'more dangerous', 'dangerouser', 'dangerous', 'most dangerous', '3+ syllable adjectives require \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'thin', 'New government IDs are _____ than old ones.', 'thinner', 'thiner', 'more thin', 'thinnest', 'CVC words double final consonant.'),
('Grammar and Structure', 'Correct  Comparative Form', 'common', 'Cybersecurity threats are _____ than before.', 'more common', 'commoner', 'common', 'commonest', '\"More\" preferred for 2-syllable adjectives.'),
('Grammar and Structure', 'Correct  Comparative Form', 'early', 'Farmers start work _____ than office workers.', 'earlier', 'more early', 'early', 'earliest', '\"Early\" → \"earlier\" (adverb exception).'),
('Grammar and Structure', 'Correct  Comparative Form', 'well', 'Trained nurses perform _____ during crises.', 'better', 'gooder', 'more well', 'best', 'Irregular form: well → better.'),
('Grammar and Structure', 'Correct  Comparative Form', 'heavy', 'Typhoon rains are _____ in Luzon than Visayas.', 'heavier', 'heavyer', 'more heavy', 'heaviest', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'reliable', 'Fiber internet is _____ than 4G networks.', 'more reliable', 'reliableer', 'reliabler', 'most reliable', '3+ syllable adjectives use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'big', 'Quezon City has _____ population than Davao City.', 'bigger', 'biger', 'more big', 'biggest', 'CVC words double final consonant.'),
('Grammar and Structure', 'Correct  Comparative Form', 'polite', 'Written requests should be _____ than emails.', 'more polite', 'politer', 'politest', 'polite', '2-syllable adjectives often use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'soon', 'E-passports will arrive _____ than expected.', 'sooner', 'more soon', 'soonest', 'early', 'One-syllable adverb: soon → sooner.'),
('Grammar and Structure', 'Correct  Comparative Form', 'few', 'Island provinces have _____ hospitals than regions.', 'fewer', 'less', 'few', 'least', '\"Fewer\" for countable nouns.'),
('Grammar and Structure', 'Correct  Comparative Form', 'sad', 'Poverty statistics are _____ than last year.', 'sadder', 'sader', 'more sad', 'saddest', 'CVC words double final consonant.'),
('Grammar and Structure', 'Correct  Comparative Form', 'clean', 'Solar power is _____ than coal energy.', 'cleaner', 'more clean', 'cleanest', 'cleanner', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'wise', 'Elders give _____ advice than youth.', 'wiser', 'more wise', 'wise', 'wisest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'expensive', 'Imported rice is _____ than local varieties.', 'more expensive', 'expensiver', 'expensive', 'most expensive', '3+ syllable adjectives use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'hot', 'Pampanga is _____ than Baguio in summer.', 'hotter', 'hoter', 'more hot', 'hottest', 'CVC words double final consonant.'),
('Grammar and Structure', 'Correct  Comparative Form', 'loud', 'City festivals are _____ than town fiestas.', 'louder', 'loud', 'more loud', 'loudest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'peaceful', 'Siquijor is _____ than Metro Manila.', 'more peaceful', 'peacefuller', 'peacefuler', 'most peaceful', '3+ syllable adjectives require \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'quick', 'E-transactions process _____ than manual.', 'quicker', 'more quick', 'quickly', 'quickest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'healthy', 'Organic rice is _____ than hybrid varieties.', 'healthier', 'healthyer', 'more healthy', 'more healthier', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'modern', 'New airports are _____ than old terminals.', 'more modern', 'moderner', 'modern', 'most modern', '2-syllable adjectives often use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'bright', 'LED streetlights are _____ than sodium lamps.', 'brighter', 'brigher', 'more bright', 'brightest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'calm', 'Batanes seas are _____ in summer than winter.', 'calmer', 'calm', 'more calm', 'calmest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'useful', 'Mobile banking is _____ than branch visits.', 'more useful', 'usefuller', 'useful', 'usefullest', '2-syllable adjectives ending in -ful use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'shallow', 'Boracay waters are _____ than Coron.', 'shallower', 'shallow', 'more shallow', 'shallowest', '2-syllable adjectives ending in -ow add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'dry', 'Ilocos region is _____ than Bicol.', 'drier', 'dryer', 'more dry', 'driest', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'strict', 'Bank regulations are _____ than before.', 'stricter', 'strict', 'more strict', 'strictest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'noisy', 'Manila streets are _____ than Cebu streets.', 'noisier', 'noisy', 'more noisy', 'more noisier', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'safe', 'Gated villages are _____ than open areas.', 'safer', 'safe', 'more safe', 'safest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'important', 'Data security is _____ than ever.', 'more important', 'importanter', 'important', 'most important', '3+ syllable adjectives require \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'cold', 'Sagada is _____ than Tagaytay.', 'colder', 'cold', 'more cold', 'coldest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'friendly', 'Provincial folk are _____ than city dwellers.', 'friendlier', 'friendlyer', 'more friendly', 'more friendlier', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'long', 'Pan-Philippine Highway is _____ than NLEX.', 'longer', 'long', 'more long', 'longest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'brave', 'Coast guards are _____ than recognized.', 'braver', 'brave', 'more brave', 'bravest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'late', 'Night markets close _____ than malls.', 'later', 'late', 'more late', 'latest', 'One-syllable adjectives/adverbs add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'often', 'Youth use apps _____ than elders.', 'more often', 'oftener', 'often', 'oftenest', '\"More often\" preferred for 2-syllable adverbs.'),
('Grammar and Structure', 'Correct  Comparative Form', 'risky', 'Fishing jobs are _____ than farming.', 'riskier', 'risky', 'more risky', 'more riskier', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'smooth', 'New systems run _____ than old ones.', 'smoother', 'smooth', 'more smooth', 'smoothest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'gentle', 'New laws are _____ than previous.', 'gentler', 'gentle', 'more gentle', 'gentlest', '2-syllable adjectives often take -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'clever', 'New algorithms are _____ than old methods.', 'cleverer', 'clever', 'more clever', 'cleverest', 'Some 2-syllable adjectives take -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'near', 'Provincial capitals are _____ than regional offices.', 'nearer', 'near', 'more near', 'nearest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'convenient', 'Online banking is _____ than branch transactions.', 'more convenient', 'convenienter', 'convenient than', 'most convenient', '3+ syllable adjectives use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'bad', 'Manila traffic is _____ during rush hour.', 'worse', 'badder', 'more bad', 'worst', 'Irregular comparative: bad → worse.'),
('Grammar and Structure', 'Correct  Comparative Form', 'little', 'Rural clinics need _____ equipment than hospitals.', 'less', 'fewer', 'littler', 'least', '\"Less\" for uncountable nouns.'),
('Grammar and Structure', 'Correct  Comparative Form', 'busy', 'EDSA is _____ than Commonwealth Avenue.', 'busier', 'busyer', 'more busy', 'bussier', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'efficient', 'Digital systems are _____ than manual processes.', 'more efficient', 'efficienter', 'efficient', 'most efficient', '3+ syllable adjectives require \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'far', 'Palawan is _____ from Manila than Boracay.', 'farther', 'further', 'more far', 'farer', '\"Farther\" for physical distance.'),
('Grammar and Structure', 'Correct  Comparative Form', 'good', 'E-governance yields _____ results.', 'better', 'gooder', 'more good', 'best', 'Irregular comparative: good → better.'),
('Grammar and Structure', 'Correct  Comparative Form', 'wealthy', 'Makati has _____ residents than Navotas.', 'wealthier', 'wealthyer', 'more wealthy', 'more wealthier', '-y adjectives change to -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'simple', 'Mobile apps are _____ to use.', 'simpler', 'more simple', 'simplest', 'more simpler', '2-syllable adjectives often take -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'old', 'Intramuros is _____ than BGC.', 'older', 'elder', 'more old', 'oldest', '\"Older\" for objects/age.'),
('Grammar and Structure', 'Correct  Comparative Form', 'smart', 'New security systems are _____ than old ones.', 'smarter', 'more smart', 'smartter', 'smartest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'humid', 'July is _____ than January.', 'more humid', 'humidier', 'humider', 'most humid', '2-syllable adjectives use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'dangerous', 'Firefighting is _____ than desk jobs.', 'more dangerous', 'dangerouser', 'dangerous', 'most dangerous', '3+ syllable adjectives require \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'thin', 'Modern laptops are _____ than older models.', 'thinner', 'thiner', 'more thin', 'thinnest', 'CVC words double final consonant.'),
('Grammar and Structure', 'Correct  Comparative Form', 'common', 'Cyberattacks are _____ now.', 'more common', 'commoner', 'common', 'commonest', '\"More\" preferred for 2-syllable adjectives.'),
('Grammar and Structure', 'Correct  Comparative Form', 'heavy', 'Monsoon rains are _____ this year.', 'heavier', 'heavyer', 'more heavy', 'heaviest', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'big', 'Quezon City has _____ population than Iloilo.', 'bigger', 'biger', 'more big', 'biggest', 'CVC words double final consonant.'),
('Grammar and Structure', 'Correct  Comparative Form', 'reliable', 'Fiber internet is _____ than wireless.', 'more reliable', 'reliableer', 'reliabler', 'most reliable', '3+ syllable adjectives use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'well', 'Trained responders perform _____.', 'better', 'gooder', 'more well', 'best', 'Irregular form: well → better.'),
('Grammar and Structure', 'Correct  Comparative Form', 'polite', 'Written complaints should be _____ than verbal.', 'more polite', 'politer', 'politest', 'polite', '2-syllable adjectives often use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'soon', 'E-services launch _____ than planned.', 'sooner', 'more soon', 'soonest', 'early', 'One-syllable adverb: soon → sooner.'),
('Grammar and Structure', 'Correct  Comparative Form', 'few', 'Island towns have _____ resources.', 'fewer', 'less', 'few', 'least', '\"Fewer\" for countable nouns.'),
('Grammar and Structure', 'Correct  Comparative Form', 'sad', 'Poverty data is _____ than expected.', 'sadder', 'sader', 'more sad', 'saddest', 'CVC words double final consonant.'),
('Grammar and Structure', 'Correct  Comparative Form', 'clean', 'Solar energy is _____ than coal.', 'cleaner', 'more clean', 'cleanest', 'cleanner', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'expensive', 'Imported goods are _____ than local.', 'more expensive', 'expensiver', 'expensive', 'most expensive', '3+ syllable adjectives use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'hot', 'Pampanga is _____ than Tagaytay.', 'hotter', 'hoter', 'more hot', 'hottest', 'CVC words double final consonant.'),
('Grammar and Structure', 'Correct  Comparative Form', 'loud', 'City centers are _____ at night.', 'louder', 'loud', 'more loud', 'loudest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'peaceful', 'Siquijor is _____ than Manila.', 'more peaceful', 'peacefuller', 'peacefuler', 'most peaceful', '3+ syllable adjectives require \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'quick', 'E-transactions are _____ than manual.', 'quicker', 'more quick', 'quickly', 'quickest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'healthy', 'Organic food is _____ than processed.', 'healthier', 'healthyer', 'more healthy', 'more healthier', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'modern', 'New airports are _____ than old.', 'more modern', 'moderner', 'modern', 'most modern', '2-syllable adjectives often use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'bright', 'LED lights are _____ than bulbs.', 'brighter', 'brigher', 'more bright', 'brightest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'calm', 'Seas are _____ in summer.', 'calmer', 'calm', 'more calm', 'calmest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'useful', 'Mobile apps are _____ than books.', 'more useful', 'usefuller', 'useful', 'usefullest', '2-syllable adjectives ending in -ful use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'dry', 'Ilocos is _____ than Bicol.', 'drier', 'dryer', 'more dry', 'driest', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'strict', 'Bank rules are _____ now.', 'stricter', 'strict', 'more strict', 'strictest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'noisy', 'Markets are _____ than malls.', 'noisier', 'noisy', 'more noisy', 'more noisier', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'safe', 'Gated areas are _____ than open.', 'safer', 'safe', 'more safe', 'safest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'important', 'Data privacy is _____ than ever.', 'more important', 'importanter', 'important', 'most important', '3+ syllable adjectives require \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'cold', 'Baguio is _____ than Manila.', 'colder', 'cold', 'more cold', 'coldest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'friendly', 'Provincial people are _____ than city.', 'friendlier', 'friendlyer', 'more friendly', 'more friendlier', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'long', 'Coastal roads are _____ than highways.', 'longer', 'long', 'more long', 'longest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'brave', 'Frontliners are _____ than acknowledged.', 'braver', 'brave', 'more brave', 'bravest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'late', 'Night shifts end _____ than day.', 'later', 'late', 'more late', 'latest', 'One-syllable adjectives/adverbs add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'often', 'Youth use apps _____ than seniors.', 'more often', 'oftener', 'often', 'oftenest', '\"More often\" preferred for adverbs.'),
('Grammar and Structure', 'Correct  Comparative Form', 'risky', 'Construction is _____ than admin work.', 'riskier', 'risky', 'more risky', 'more riskier', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'wise', 'Elders give _____ advice.', 'wiser', 'more wise', 'wise', 'wisest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'gentle', 'New policies are _____ than old.', 'gentler', 'gentle', 'more gentle', 'gentlest', '2-syllable adjectives often take -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'clever', 'New systems are _____ than traditional.', 'cleverer', 'clever', 'more clever', 'cleverest', 'Some 2-syllable adjectives take -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'dangerous', 'Mining sites are _____ than office work.', 'more dangerous', 'dangerouser', 'dangerous', 'most dangerous', '3+ syllable adjectives use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'thin', 'Modern IDs are _____ than old versions.', 'thinner', 'thiner', 'more thin', 'thinnest', 'CVC words double final consonant.'),
('Grammar and Structure', 'Correct  Comparative Form', 'common', 'Cyber threats are _____ than before.', 'more common', 'commoner', 'common', 'commonest', '\"More\" preferred for 2-syllable adjectives.'),
('Grammar and Structure', 'Correct  Comparative Form', 'early', 'Farmers start work _____ than clerks.', 'earlier', 'more early', 'early', 'earliest', '\"Early\" → \"earlier\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'big', 'Quezon City has _____ population than Iloilo City.', 'bigger', 'biger', 'more big', 'biggest', 'CVC words double final consonant.'),
('Grammar and Structure', 'Correct  Comparative Form', 'reliable', 'Fiber internet is _____ than satellite.', 'more reliable', 'reliableer', 'reliabler', 'most reliable', '3+ syllable adjectives use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'few', 'Island towns have _____ hospitals than cities.', 'fewer', 'less', 'few', 'least', '\"Fewer\" for countable nouns.'),
('Grammar and Structure', 'Correct  Comparative Form', 'hot', 'Pampanga is _____ than Tagaytay in summer.', 'hotter', 'hoter', 'more hot', 'hottest', 'CVC words double final consonant.'),
('Grammar and Structure', 'Correct  Comparative Form', 'loud', 'City fiestas are _____ than town celebrations.', 'louder', 'loud', 'more loud', 'loudest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'healthy', 'Organic rice is _____ than hybrid rice.', 'healthier', 'healthyer', 'more healthy', 'more healthier', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'calm', 'Batanes seas are _____ in summer.', 'calmer', 'calm', 'more calm', 'calmest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'dry', 'Ilocos region is _____ than Quezon province.', 'drier', 'dryer', 'more dry', 'driest', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'strict', 'Bank regulations are _____ now.', 'stricter', 'strict', 'more strict', 'strictest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'important', 'Cyber security is _____ than ever.', 'more important', 'importanter', 'important', 'most important', '3+ syllable adjectives require \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'cold', 'Sagada is _____ than Baguio.', 'colder', 'cold', 'more cold', 'coldest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'friendly', 'Provincial residents are _____ than city dwellers.', 'friendlier', 'friendlyer', 'more friendly', 'more friendlier', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'risky', 'Construction work is _____ than office jobs.', 'riskier', 'risky', 'more risky', 'more riskier', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'gentle', 'New policies are _____ than old ones.', 'gentler', 'gentle', 'more gentle', 'gentlest', '2-syllable adjectives often take -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'clever', 'New systems are _____ than traditional methods.', 'cleverer', 'clever', 'more clever', 'cleverest', 'Some 2-syllable adjectives take -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'near', 'Provincial capitals are _____ to villages than Manila.', 'nearer', 'near', 'more near', 'nearest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'little', 'Rural schools need _____ funding than urban schools.', 'less', 'fewer', 'littler', 'least', '\"Less\" for uncountable nouns.'),
('Grammar and Structure', 'Correct  Comparative Form', 'busy', 'EDSA is _____ than C5 during peak hours.', 'busier', 'busyer', 'more busy', 'bussier', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'far', 'Batanes is _____ from Manila than Palawan.', 'farther', 'further', 'more far', 'farer', '\"Farther\" for physical distance.'),
('Grammar and Structure', 'Correct  Comparative Form', 'good', 'Digital systems yield _____ results than manual.', 'better', 'gooder', 'more good', 'best', 'Irregular: good → better.'),
('Grammar and Structure', 'Correct  Comparative Form', 'simple', 'Mobile apps are _____ to navigate.', 'simpler', 'more simple', 'simplest', 'more simpler', '2-syllable adjectives often take -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'humid', 'August is _____ than March in the Philippines.', 'more humid', 'humidier', 'humider', 'most humid', '2-syllable adjectives use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'dangerous', 'Firefighting is _____ than clerical work.', 'more dangerous', 'dangerouser', 'dangerous', 'most dangerous', '3+ syllable adjectives require \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'thin', 'Modern IDs are _____ than previous versions.', 'thinner', 'thiner', 'more thin', 'thinnest', 'CVC words double final consonant.'),
('Grammar and Structure', 'Correct  Comparative Form', 'early', 'Farmers begin work _____ than office workers.', 'earlier', 'more early', 'early', 'earliest', '\"Early\" → \"earlier\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'heavy', 'Typhoon rains are _____ in Northern Luzon.', 'heavier', 'heavyer', 'more heavy', 'heaviest', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'reliable', 'Fiber connections are _____ than wireless.', 'more reliable', 'reliableer', 'reliabler', 'most reliable', '3+ syllable adjectives use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'well', 'Trained responders perform _____ in crises.', 'better', 'gooder', 'more well', 'best', 'Irregular: well → better.'),
('Grammar and Structure', 'Correct  Comparative Form', 'polite', 'Written communications should be _____ than verbal.', 'more polite', 'politer', 'politest', 'polite', '2-syllable adjectives often use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'few', 'Island provinces have _____ hospitals than Luzon.', 'fewer', 'less', 'few', 'least', '\"Fewer\" for countable nouns.'),
('Grammar and Structure', 'Correct  Comparative Form', 'sad', 'Unemployment figures are _____ than projected.', 'sadder', 'sader', 'more sad', 'saddest', 'CVC words double final consonant.'),
('Grammar and Structure', 'Correct  Comparative Form', 'hot', 'Pampanga is _____ than Tagaytay in April.', 'hotter', 'hoter', 'more hot', 'hottest', 'CVC words double final consonant.'),
('Grammar and Structure', 'Correct  Comparative Form', 'healthy', 'Organic food is _____ than processed food.', 'healthier', 'healthyer', 'more healthy', 'more healthier', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'calm', 'Batanes seas are _____ during summer months.', 'calmer', 'calm', 'more calm', 'calmest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'useful', 'Mobile apps are _____ than printed guides.', 'more useful', 'usefuller', 'useful', 'usefullest', '2-syllable adjectives ending in -ful use \"more\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'shallow', 'Boracay waters are _____ than El Nido.', 'shallower', 'shallow', 'more shallow', 'shallowest', '2-syllable adjectives ending in -ow add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'dry', 'Ilocos region is _____ than Bicol region.', 'drier', 'dryer', 'more dry', 'driest', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'safe', 'Gated villages are _____ than open neighborhoods.', 'safer', 'safe', 'more safe', 'safest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'cold', 'Sagada is _____ than Baguio in December.', 'colder', 'cold', 'more cold', 'coldest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'brave', 'Frontline workers are _____ than recognized.', 'braver', 'brave', 'more brave', 'bravest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'late', 'Night markets operate _____ than malls.', 'later', 'late', 'more late', 'latest', 'One-syllable adjectives/adverbs add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'often', 'Young adults use apps _____ than seniors.', 'more often', 'oftener', 'often', 'oftenest', '\"More often\" preferred for adverbs.'),
('Grammar and Structure', 'Correct  Comparative Form', 'risky', 'Fishing occupations are _____ than farming.', 'riskier', 'risky', 'more risky', 'more riskier', '-y adjectives become -ier.'),
('Grammar and Structure', 'Correct  Comparative Form', 'wise', 'Elders offer _____ advice than youth.', 'wiser', 'more wise', 'wise', 'wisest', 'One-syllable adjectives add -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'gentle', 'New regulations are _____ than previous.', 'gentler', 'gentle', 'more gentle', 'gentlest', '2-syllable adjectives often take -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'clever', 'Algorithms are _____ than manual methods.', 'cleverer', 'clever', 'more clever', 'cleverest', 'Some 2-syllable adjectives take -er.'),
('Grammar and Structure', 'Correct  Comparative Form', 'efficient', 'E-governance is _____ than manual processing.', 'more efficient', 'efficienter', 'efficient', 'most efficient', '3+ syllable adjectives use \"more\"'),
('Grammar and Structure', 'Correct  Comparative Form', 'busy', 'EDSA is _____ during rush hour than off-peak.', 'busier', 'busyer', 'more busy', 'bussier', '-y adjectives become -ier'),
('Grammar and Structure', 'Correct  Comparative Form', 'bad', 'Traffic congestion is _____ on Fridays.', 'worse', 'badder', 'more bad', 'worst', 'Irregular: bad → worse'),
('Grammar and Structure', 'Correct  Comparative Form', 'little', 'Rural clinics have _____ equipment than hospitals.', 'less', 'fewer', 'littler', 'least', '\"Less\" for uncountable nouns'),
('Grammar and Structure', 'Correct  Comparative Form', 'humid', 'July is _____ than January in the Philippines.', 'more humid', 'humidier', 'humider', 'most humid', '2-syllable adjectives use \"more\"');
INSERT INTO `verbal` (`category`, `type`, `word`, `question`, `correct_answer`, `wrong_answer1`, `wrong_answer2`, `wrong_answer3`, `explanation`) VALUES
('Grammar and Structure', 'Correct  Comparative Form', 'smart', 'Biometric systems are _____ than passwords.', 'smarter', 'more smart', 'smartter', 'smartest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'dangerous', 'Mining is _____ than office work.', 'more dangerous', 'dangerouser', 'dangerous', 'most dangerous', '3+ syllable adjectives use \"more\"'),
('Grammar and Structure', 'Correct  Comparative Form', 'polite', 'Written requests should be _____ than verbal complaints.', 'more polite', 'politer', 'politest', 'polite', '2-syllable adjectives use \"more\"'),
('Grammar and Structure', 'Correct  Comparative Form', 'few', 'Island towns have _____ resources than cities.', 'fewer', 'less', 'few', 'least', '\"Fewer\" for countable nouns'),
('Grammar and Structure', 'Correct  Comparative Form', 'sad', 'Poverty statistics are _____ than projected.', 'sadder', 'sader', 'more sad', 'saddest', 'CVC words double final consonant'),
('Grammar and Structure', 'Correct  Comparative Form', 'clean', 'Solar energy is _____ than coal power.', 'cleaner', 'more clean', 'cleanest', 'cleanner', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'bright', 'LED lights are _____ than incandescent bulbs.', 'brighter', 'brigher', 'more bright', 'brightest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'safe', 'Gated communities are _____ than open areas.', 'safer', 'safe', 'more safe', 'safest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'long', 'Pan-Philippine Highway is _____ than SLEX.', 'longer', 'long', 'more long', 'longest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'gentle', 'New policies are _____ than previous ones.', 'gentler', 'gentle', 'more gentle', 'gentlest', '2-syllable adjectives often take -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'clever', 'New algorithms are _____ than traditional methods.', 'cleverer', 'clever', 'more clever', 'cleverest', 'Some 2-syllable adjectives take -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'tall', 'The Mayon Volcano is _____ than Taal Volcano.', 'taller', 'more tall', 'tallest', 'most tall', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'efficient', 'E-filing is _____ than paper submissions.', 'more efficient', 'efficienter', 'efficient', 'most efficient', '3+ syllable adjectives use \"more\"'),
('Grammar and Structure', 'Correct  Comparative Form', 'busy', 'Makati CBD is _____ than Alabang during rush hour.', 'busier', 'busyer', 'more busy', 'bussier', '-y adjectives become -ier'),
('Grammar and Structure', 'Correct  Comparative Form', 'bad', 'Traffic is _____ during holiday seasons.', 'worse', 'badder', 'more bad', 'worst', 'Irregular: bad → worse'),
('Grammar and Structure', 'Correct  Comparative Form', 'little', 'Rural clinics have _____ medical equipment.', 'less', 'fewer', 'littler', 'least', '\"Less\" for uncountable nouns'),
('Grammar and Structure', 'Correct  Comparative Form', 'humid', 'September is _____ than February in the Philippines.', 'more humid', 'humidier', 'humider', 'most humid', '2-syllable adjectives use \"more\"'),
('Grammar and Structure', 'Correct  Comparative Form', 'smart', 'New security systems are _____ than previous versions.', 'smarter', 'more smart', 'smartter', 'smartest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'common', 'Online scams are _____ than before.', 'more common', 'commoner', 'common', 'commonest', '\"More\" preferred for 2-syllable adjectives'),
('Grammar and Structure', 'Correct  Comparative Form', 'early', 'Farm workers start _____ than office employees.', 'earlier', 'more early', 'early', 'earliest', '\"Early\" → \"earlier\"'),
('Grammar and Structure', 'Correct  Comparative Form', 'well', 'Trained responders perform _____ during drills.', 'better', 'gooder', 'more well', 'best', 'Irregular: well → better'),
('Grammar and Structure', 'Correct  Comparative Form', 'heavy', 'Monsoon rains are _____ in Luzon than Visayas.', 'heavier', 'heavyer', 'more heavy', 'heaviest', '-y adjectives become -ier'),
('Grammar and Structure', 'Correct  Comparative Form', 'big', 'Quezon City has _____ population than Cebu City.', 'bigger', 'biger', 'more big', 'biggest', 'CVC words double final consonant'),
('Grammar and Structure', 'Correct  Comparative Form', 'reliable', 'Fiber internet is _____ than mobile data.', 'more reliable', 'reliableer', 'reliabler', 'most reliable', '3+ syllable adjectives use \"more\"'),
('Grammar and Structure', 'Correct  Comparative Form', 'soon', 'E-passports will be available _____ than expected.', 'sooner', 'more soon', 'soonest', 'early', 'One-syllable adverb: soon → sooner'),
('Grammar and Structure', 'Correct  Comparative Form', 'few', 'Island municipalities have _____ hospitals than cities.', 'fewer', 'less', 'few', 'least', '\"Fewer\" for countable nouns'),
('Grammar and Structure', 'Correct  Comparative Form', 'sad', 'Unemployment numbers are _____ than projected.', 'sadder', 'sader', 'more sad', 'saddest', 'CVC words double final consonant'),
('Grammar and Structure', 'Correct  Comparative Form', 'expensive', 'Imported electronics are _____ than local brands.', 'more expensive', 'expensiver', 'expensive', 'most expensive', '3+ syllable adjectives use \"more\"'),
('Grammar and Structure', 'Correct  Comparative Form', 'peaceful', 'Siquijor beaches are _____ than Manila Bay.', 'more peaceful', 'peacefuller', 'peacefuler', 'most peaceful', '3+ syllable adjectives require \"more\"'),
('Grammar and Structure', 'Correct  Comparative Form', 'healthy', 'Organic produce is _____ than conventional.', 'healthier', 'healthyer', 'more healthy', 'more healthier', '-y adjectives become -ier'),
('Grammar and Structure', 'Correct  Comparative Form', 'bright', 'LED streetlights are _____ than traditional lamps.', 'brighter', 'brigher', 'more bright', 'brightest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'calm', 'Provincial seas are _____ during summer.', 'calmer', 'calm', 'more calm', 'calmest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'strict', 'Bank regulations are _____ this year.', 'stricter', 'strict', 'more strict', 'strictest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'noisy', 'Manila streets are _____ than Iloilo streets.', 'noisier', 'noisy', 'more noisy', 'more noisier', '-y adjectives become -ier'),
('Grammar and Structure', 'Correct  Comparative Form', 'safe', 'Gated subdivisions are _____ than open areas.', 'safer', 'safe', 'more safe', 'safest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'brave', 'Coast guard personnel are _____ than recognized.', 'braver', 'brave', 'more brave', 'bravest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'late', 'Night markets operate _____ than shopping malls.', 'later', 'late', 'more late', 'latest', 'One-syllable adjectives/adverbs add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'often', 'Young professionals use apps _____ than seniors.', 'more often', 'oftener', 'often', 'oftenest', '\"More often\" preferred for adverbs'),
('Grammar and Structure', 'Correct  Comparative Form', 'risky', 'Deep-sea fishing is _____ than farming.', 'riskier', 'risky', 'more risky', 'more riskier', '-y adjectives become -ier'),
('Grammar and Structure', 'Correct  Comparative Form', 'wise', 'Community elders give _____ advice.', 'wiser', 'more wise', 'wise', 'wisest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'gentle', 'New guidelines are _____ than previous versions.', 'gentler', 'gentle', 'more gentle', 'gentlest', '2-syllable adjectives often take -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'clever', 'Security algorithms are _____ than passwords.', 'cleverer', 'clever', 'more clever', 'cleverest', 'Some 2-syllable adjectives take -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'near', 'Provincial centers are _____ to villages than Manila.', 'nearer', 'near', 'more near', 'nearest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'wide', 'Express lanes are _____ than service roads.', 'wider', 'wide', 'more wide', 'widest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'young', 'New police recruits are _____ than retiring officers.', 'younger', 'young', 'more young', 'youngest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'efficient', 'Online systems are _____ than manual processes.', 'more efficient', 'efficienter', 'efficient', 'most efficient', '3+ syllable adjectives use \"more\"'),
('Grammar and Structure', 'Correct  Comparative Form', 'bad', 'Air quality is _____ in summer than rainy season.', 'worse', 'badder', 'more bad', 'worst', 'Irregular: bad → worse'),
('Grammar and Structure', 'Correct  Comparative Form', 'smart', 'New security systems are _____ than old methods.', 'smarter', 'more smart', 'smartter', 'smartest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'well', 'Trained responders perform _____ during emergencies.', 'better', 'gooder', 'more well', 'best', 'Irregular: well → better'),
('Grammar and Structure', 'Correct  Comparative Form', 'few', 'Island municipalities have _____ hospitals than mainland cities.', 'fewer', 'less', 'few', 'least', '\"Fewer\" for countable nouns'),
('Grammar and Structure', 'Correct  Comparative Form', 'quick', 'Digital transactions are _____ than manual processing.', 'quicker', 'more quick', 'quickly', 'quickest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'healthy', 'Organic vegetables are _____ than conventional produce.', 'healthier', 'healthyer', 'more healthy', 'more healthier', '-y adjectives become -ier'),
('Grammar and Structure', 'Correct  Comparative Form', 'late', 'Night markets close _____ than shopping malls.', 'later', 'late', 'more late', 'latest', 'One-syllable adjectives/adverbs add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'gentle', 'New policies are _____ than previous versions.', 'gentler', 'gentle', 'more gentle', 'gentlest', '2-syllable adjectives often take -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'clever', 'Security systems are _____ than traditional methods.', 'cleverer', 'clever', 'more clever', 'cleverest', 'Some 2-syllable adjectives take -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'near', 'Provincial capitals are _____ to rural areas than Manila.', 'nearer', 'near', 'more near', 'nearest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'busy', 'Makati CBD is _____ than Ortigas during rush hour.', 'busier', 'busyer', 'more busy', 'bussier', '-y adjectives become -ier'),
('Grammar and Structure', 'Correct  Comparative Form', 'humid', 'August is _____ than January in the Philippines.', 'more humid', 'humidier', 'humider', 'most humid', '2-syllable adjectives use \"more\"'),
('Grammar and Structure', 'Correct  Comparative Form', 'early', 'Farm workers start _____ than office staff.', 'earlier', 'more early', 'early', 'earliest', '\"Early\" → \"earlier\"'),
('Grammar and Structure', 'Correct  Comparative Form', 'well', 'Trained nurses perform _____ in crises.', 'better', 'gooder', 'more well', 'best', 'Irregular: well → better'),
('Grammar and Structure', 'Correct  Comparative Form', 'heavy', 'Typhoon rains are _____ in Luzon.', 'heavier', 'heavyer', 'more heavy', 'heaviest', '-y adjectives become -ier'),
('Grammar and Structure', 'Correct  Comparative Form', 'soon', 'E-passports arrive _____ than expected.', 'sooner', 'more soon', 'soonest', 'early', 'One-syllable adverb: soon → sooner'),
('Grammar and Structure', 'Correct  Comparative Form', 'sad', 'Poverty data is _____ than projected.', 'sadder', 'sader', 'more sad', 'saddest', 'CVC words double final consonant'),
('Grammar and Structure', 'Correct  Comparative Form', 'calm', 'Summer seas are _____ than monsoon seas.', 'calmer', 'calm', 'more calm', 'calmest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'useful', 'Mobile apps are _____ than manuals.', 'more useful', 'usefuller', 'useful', 'usefullest', '2-syllable adjectives ending in -ful use \"more\"'),
('Grammar and Structure', 'Correct  Comparative Form', 'safe', 'Gated areas are _____ than open areas.', 'safer', 'safe', 'more safe', 'safest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'friendly', 'Provincial people are _____ than city residents.', 'friendlier', 'friendlyer', 'more friendly', 'more friendlier', '-y adjectives become -ier'),
('Grammar and Structure', 'Correct  Comparative Form', 'near', 'Provincial capitals are _____ than Manila.', 'nearer', 'near', 'more near', 'nearest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'wide', 'Expressways are _____ than local roads.', 'wider', 'wide', 'more wide', 'widest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'efficient', 'Digital processing is _____ than manual filing.', 'more efficient', 'efficienter', 'efficient', 'most efficient', '3+ syllable adjectives use \"more\"'),
('Grammar and Structure', 'Correct  Comparative Form', 'busy', 'EDSA is _____ during rush hour than late night.', 'busier', 'busyer', 'more busy', 'bussier', '-y adjectives become -ier'),
('Grammar and Structure', 'Correct  Comparative Form', 'little', 'Rural schools have _____ funding than urban schools.', 'less', 'fewer', 'littler', 'least', '\"Less\" for uncountable nouns'),
('Grammar and Structure', 'Correct  Comparative Form', 'humid', 'August is _____ than February in the Philippines.', 'more humid', 'humidier', 'humider', 'most humid', '2-syllable adjectives use \"more\"'),
('Grammar and Structure', 'Correct  Comparative Form', 'smart', 'Biometric systems are _____ than password systems.', 'smarter', 'more smart', 'smartter', 'smartest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'dangerous', 'Mining work is _____ than office work.', 'more dangerous', 'dangerouser', 'dangerous', 'most dangerous', '3+ syllable adjectives use \"more\"'),
('Grammar and Structure', 'Correct  Comparative Form', 'thin', 'Modern IDs are _____ than old IDs.', 'thinner', 'thiner', 'more thin', 'thinnest', 'CVC words double final consonant'),
('Grammar and Structure', 'Correct  Comparative Form', 'well', 'Trained responders perform _____ in drills.', 'better', 'gooder', 'more well', 'best', 'Irregular: well → better'),
('Grammar and Structure', 'Correct  Comparative Form', 'heavy', 'Monsoon rains are _____ in Northern Luzon.', 'heavier', 'heavyer', 'more heavy', 'heaviest', '-y adjectives become -ier'),
('Grammar and Structure', 'Correct  Comparative Form', 'soon', 'E-passports will be issued _____ than scheduled.', 'sooner', 'more soon', 'soonest', 'early', 'One-syllable adverb: soon → sooner'),
('Grammar and Structure', 'Correct  Comparative Form', 'sad', 'Unemployment figures are _____ than expected.', 'sadder', 'sader', 'more sad', 'saddest', 'CVC words double final consonant'),
('Grammar and Structure', 'Correct  Comparative Form', 'clean', 'Solar power is _____ than coal power.', 'cleaner', 'more clean', 'cleanest', 'cleanner', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'quick', 'E-transactions are _____ than manual processing.', 'quicker', 'more quick', 'quickly', 'quickest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'bright', 'LED lights are _____ than fluorescent lights.', 'brighter', 'brigher', 'more bright', 'brightest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'calm', 'Summer seas are _____ than typhoon seasons.', 'calmer', 'calm', 'more calm', 'most calm', 'For short adjectives like \"calm\", add \"-er\" to form the comparative: \"calmer\".'),
('Grammar and Structure', 'Correct  Comparative Form', 'busy', 'Makati CBD is _____ during rush hour than off-peak.', 'busier', 'busyer', 'more busy', 'bussier', '-y adjectives become -ier'),
('Grammar and Structure', 'Correct  Comparative Form', 'bad', 'Traffic congestion is _____ on payday Fridays.', 'worse', 'badder', 'more bad', 'worst', 'Irregular: bad → worse'),
('Grammar and Structure', 'Correct  Comparative Form', 'humid', 'September is _____ than March in the Philippines.', 'more humid', 'humidier', 'humider', 'most humid', '2-syllable adjectives use \"more\"'),
('Grammar and Structure', 'Correct  Comparative Form', 'thin', 'Modern IDs are _____ than older versions.', 'thinner', 'thiner', 'more thin', 'thinnest', 'CVC words double final consonant'),
('Grammar and Structure', 'Correct  Comparative Form', 'common', 'Cybersecurity threats are _____ now.', 'more common', 'commoner', 'common', 'commonest', '\"More\" preferred for 2-syllable adjectives'),
('Grammar and Structure', 'Correct  Comparative Form', 'soon', 'E-passports will arrive _____ than scheduled.', 'sooner', 'more soon', 'soonest', 'early', 'One-syllable adverb: soon → sooner'),
('Grammar and Structure', 'Correct  Comparative Form', 'sad', 'Poverty statistics are _____ than expected.', 'sadder', 'sader', 'more sad', 'saddest', 'CVC words double final consonant'),
('Grammar and Structure', 'Correct  Comparative Form', 'clean', 'Solar power is _____ than fossil fuels.', 'cleaner', 'more clean', 'cleanest', 'cleanner', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'quick', 'Digital transactions are _____ than manual.', 'quicker', 'more quick', 'quickly', 'quickest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'healthy', 'Organic vegetables are _____ than conventional.', 'healthier', 'healthyer', 'more healthy', 'more healthier', '-y adjectives become -ier'),
('Grammar and Structure', 'Correct  Comparative Form', 'calm', 'Summer seas are _____ than typhoon season.', 'calmer', 'calm', 'more calm', 'calmest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'brave', 'Frontline workers are _____ than acknowledged.', 'braver', 'brave', 'more brave', 'bravest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'efficient', 'E-governance is _____ than manual systems.', 'more efficient', 'efficienter', 'efficient', 'most efficient', '3+ syllable adjectives use \"more\"'),
('Grammar and Structure', 'Correct  Comparative Form', 'bad', 'Manila traffic is _____ during holidays.', 'worse', 'badder', 'more bad', 'worst', 'Irregular: bad → worse'),
('Grammar and Structure', 'Correct  Comparative Form', 'soon', 'E-passports arrive _____ than scheduled.', 'sooner', 'more soon', 'soonest', 'early', 'One-syllable adverb: soon → sooner'),
('Grammar and Structure', 'Correct  Comparative Form', 'gentle', 'New policies are _____ than previous.', 'gentler', 'gentle', 'more gentle', 'gentlest', '2-syllable adjectives often take -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'clever', 'Security systems are _____ than passwords.', 'cleverer', 'clever', 'more clever', 'cleverest', 'Some 2-syllable adjectives take -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'busy', 'Makati CBD is _____ than Ortigas during peak hours.', 'busier', 'busyer', 'more busy', 'bussier', '-y adjectives become -ier'),
('Grammar and Structure', 'Correct  Comparative Form', 'little', 'Rural clinics have _____ equipment than city hospitals.', 'less', 'fewer', 'littler', 'least', '\"Less\" for uncountable nouns'),
('Grammar and Structure', 'Correct  Comparative Form', 'soon', 'E-passports will be available _____ than planned.', 'sooner', 'more soon', 'soonest', 'early', 'One-syllable adverb: soon → sooner'),
('Grammar and Structure', 'Correct  Comparative Form', 'few', 'Island municipalities have _____ resources than cities.', 'fewer', 'less', 'few', 'least', '\"Fewer\" for countable nouns'),
('Grammar and Structure', 'Correct  Comparative Form', 'high', 'Mount Apo is _____ than Mount Pulag.', 'higher', 'more high', 'high', 'most high', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'bad', 'Air pollution is _____ during dry season.', 'worse', 'badder', 'more bad', 'worst', 'Irregular: bad → worse'),
('Grammar and Structure', 'Correct  Comparative Form', 'few', 'Island provinces have _____ hospitals than cities.', 'fewer', 'less', 'few', 'least', '\"Fewer\" for countable nouns'),
('Grammar and Structure', 'Correct  Comparative Form', 'calm', 'Batanes seas are _____ during summer.', 'calmer', 'calm', 'more calm', 'calmest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'shallow', 'Boracay waters are _____ than Coron waters.', 'shallower', 'shallow', 'more shallow', 'shallowest', '2-syllable adjectives ending in -ow add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'bad', 'Traffic congestion is _____ on holidays.', 'worse', 'badder', 'more bad', 'worst', 'Irregular: bad → worse'),
('Grammar and Structure', 'Correct  Comparative Form', 'common', 'Cyber threats are _____ now.', 'more common', 'commoner', 'common', 'commonest', '\"More\" preferred for 2-syllable adjectives'),
('Grammar and Structure', 'Correct  Comparative Form', 'well', 'Trained responders perform _____ during crises.', 'better', 'gooder', 'more well', 'best', 'Irregular: well → better'),
('Grammar and Structure', 'Correct  Comparative Form', 'calm', 'Summer seas are _____ than stormy seas.', 'calmer', 'calm', 'more calm', 'calmest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'safe', 'Gated areas are _____ than open neighborhoods.', 'safer', 'safe', 'more safe', 'safest', 'One-syllable adjectives add -er'),
('Grammar and Structure', 'Correct  Comparative Form', 'brave', 'Frontliners are _____ than recognized.', 'braver', 'brave', 'more brave', 'bravest', 'One-syllable adjectives add -er');
