
INSERT INTO `verbal` (`category`, `type`, `word`, `question`, `correct_answer`, `wrong_answer1`, `wrong_answer2`, `wrong_answer3`, `explanation`) VALUES
('Grammar and Structure', 'Noun Form', 'improvement', 'The new software shows significant _____ in processing speed.', 'improvement', 'improve', 'improved', 'improving', '\"Improvement\" is the noun form; \"improve\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'agreement', 'Both parties signed the _____ yesterday.', 'agreement', 'agree', 'agreed', 'agreeing', '\"Agreement\" is the correct noun; \"agree\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'payment', 'Online _____ must be completed before delivery.', 'payment', 'pay', 'paid', 'paying', '\"Payment\" is the noun form; \"pay\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'argument', 'Their _____ lasted for hours without resolution.', 'argument', 'argue', 'argued', 'arguing', '\"Argument\" is the noun; \"argue\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'development', 'The _____ of new vaccines takes years of research.', 'development', 'develop', 'developed', 'developing', '\"Development\" is the noun referring to the process of creating something.'),
('Grammar and Structure', 'Noun Form', 'government', 'The _____ announced new economic policies.', 'government', 'govern', 'governed', 'governing', '\"Government\" is the noun form; \"govern\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'investment', 'Her wise _____ yielded high returns.', 'investment', 'invest', 'invested', 'investing', '\"Investment\" is the noun; \"invest\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'judgment', 'The court will announce its _____ next week.', 'judgment', 'judge', 'judged', 'judging', '\"Judgment\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'management', 'Effective _____ is crucial for business success.', 'management', 'manage', 'managed', 'managing', '\"Management\" is the noun; \"manage\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'measurement', 'Accurate _____ is essential in scientific experiments.', 'measurement', 'measure', 'measured', 'measuring', '\"Measurement\" is the noun form of \"measure\".'),
('Grammar and Structure', 'Noun Form', 'punishment', 'The _____ for violating rules was severe.', 'punishment', 'punish', 'punished', 'punishing', '\"Punishment\" is the noun; \"punish\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'requirement', 'The main _____ for the job is a college degree.', 'requirement', 'require', 'required', 'requiring', '\"Requirement\" is the noun form of \"require\".'),
('Grammar and Structure', 'Noun Form', 'settlement', 'The labor dispute reached a peaceful _____.', 'settlement', 'settle', 'settled', 'settling', '\"Settlement\" is the correct noun; \"settle\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'statement', 'His official _____ clarified the misunderstanding.', 'statement', 'state', 'stated', 'stating', '\"Statement\" is the noun; \"state\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'treatment', 'Early _____ improved the patient\'s condition.', 'treatment', 'treat', 'treated', 'treating', '\"Treatment\" is the noun form of \"treat\".'),
('Grammar and Structure', 'Noun Form', 'amazement', 'To our _____, the magician escaped unharmed.', 'amazement', 'amaze', 'amazed', 'amazing', '\"Amazement\" is the noun; \"amaze\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'enjoyment', 'Her _____ of classical music is evident.', 'enjoyment', 'enjoy', 'enjoyed', 'enjoying', '\"Enjoyment\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'employment', '_____ rates increased last quarter.', 'Employment', 'employ', 'employed', 'employing', '\"Employment\" is the noun; \"employ\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'engagement', 'Their _____ was announced yesterday.', 'engagement', 'engage', 'engaged', 'engaging', '\"Engagement\" is the noun form of \"engage\".'),
('Grammar and Structure', 'Noun Form', 'fulfillment', 'Job _____ matters more than salary for many.', 'fulfillment', 'fulfill', 'fulfilled', 'fulfilling', '\"Fulfillment\" is the noun; \"fulfill\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'assessment', 'The teacher\'s _____ of the project was fair.', 'assessment', 'assess', 'assessed', 'assessing', '\"Assessment\" is the noun form of \"assess\".'),
('Grammar and Structure', 'Noun Form', 'commitment', 'His _____ to the cause is admirable.', 'commitment', 'commit', 'committed', 'committing', '\"Commitment\" is the noun; \"commit\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'replacement', 'We need a _____ for the damaged part.', 'replacement', 'replace', 'replaced', 'replacing', '\"Replacement\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'adjustment', 'The machine needs minor _____.', 'adjustment', 'adjust', 'adjusted', 'adjusting', '\"Adjustment\" is the noun; \"adjust\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'establishment', 'The _____ of new policies took months.', 'establishment', 'establish', 'established', 'establishing', '\"Establishment\" is the noun form of \"establish\".'),
('Grammar and Structure', 'Noun Form', 'containment', '_____ of the virus required strict measures.', 'Containment', 'contain', 'contained', 'containing', '\"Containment\" is the noun; \"contain\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'endorsement', 'The celebrity _____ boosted sales.', 'endorsement', 'endorse', 'endorsed', 'endorsing', '\"Endorsement\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'enforcement', 'Law _____ is essential for public safety.', 'enforcement', 'enforce', 'enforced', 'enforcing', '\"Enforcement\" is the noun; \"enforce\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'achievement', 'Completing the marathon was her greatest _____.', 'achievement', 'achieve', 'achieved', 'achieving', '\"Achievement\" is the noun form of \"achieve\".'),
('Grammar and Structure', 'Noun Form', 'amusement', 'The children\'s _____ was evident at the circus.', 'amusement', 'amuse', 'amused', 'amusing', '\"Amusement\" is the noun; \"amuse\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'announcement', 'An official _____ is expected soon.', 'announcement', 'announce', 'announced', 'announcing', '\"Announcement\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'appointment', 'Please confirm your doctor\'s _____.', 'appointment', 'appoint', 'appointed', 'appointing', '\"Appointment\" is the noun; \"appoint\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'assignment', 'The _____ must be submitted by Friday.', 'assignment', 'assign', 'assigned', 'assigning', '\"Assignment\" is the noun form of \"assign\".'),
('Grammar and Structure', 'Noun Form', 'basement', 'The _____ flooded during heavy rains.', 'basement', 'base', 'based', 'basing', '\"Basement\" is the noun; \"base\" is a verb/adjective.'),
('Grammar and Structure', 'Noun Form', 'contentment', 'Simple living often brings _____.', 'contentment', 'content', 'contented', 'contenting', '\"Contentment\" is the noun; \"content\" is an adjective.'),
('Grammar and Structure', 'Noun Form', 'encouragement', 'His teacher\'s _____ helped him succeed.', 'encouragement', 'encourage', 'encouraged', 'encouraging', '\"Encouragement\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'equipment', 'The laboratory _____ needs calibration.', 'equipment', 'equip', 'equipped', 'equipping', '\"Equipment\" is the noun; \"equip\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'fulfillment', 'Career _____ is more important than wealth.', 'fulfillment', 'fulfill', 'fulfilled', 'fulfilling', '\"Fulfillment\" is the noun form of \"fulfill\".'),
('Grammar and Structure', 'Noun Form', 'improvement', 'There\'s noticeable _____ in her writing skills.', 'improvement', 'improve', 'improved', 'improving', '\"Improvement\" is the noun; \"improve\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'involvement', 'Community _____ strengthens neighborhoods.', 'involvement', 'involve', 'involved', 'involving', '\"Involvement\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'judgment', 'The panel\'s _____ was unanimous.', 'judgment', 'judge', 'judged', 'judging', '\"Judgment\" is the noun; \"judge\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'movement', 'The civil rights _____ changed history.', 'movement', 'move', 'moved', 'moving', '\"Movement\" is the noun form of \"move\".'),
('Grammar and Structure', 'Noun Form', 'retirement', 'He\'s planning for _____ next year.', 'retirement', 'retire', 'retired', 'retiring', '\"Retirement\" is the noun; \"retire\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'shipment', 'The _____ arrives tomorrow.', 'shipment', 'ship', 'shipped', 'shipping', '\"Shipment\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'statement', 'The witness gave a sworn _____.', 'statement', 'state', 'stated', 'stating', '\"Statement\" is the noun; \"state\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'treatment', 'The new medical _____ shows promise.', 'treatment', 'treat', 'treated', 'treating', '\"Treatment\" is the noun form of \"treat\".'),
('Grammar and Structure', 'Noun Form', 'agreement', 'The peace _____ was signed today.', 'agreement', 'agree', 'agreed', 'agreeing', '\"Agreement\" is the noun; \"agree\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'argument', 'Their _____ lasted all night.', 'argument', 'argue', 'argued', 'arguing', '\"Argument\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'assessment', 'The property _____ determined its value.', 'assessment', 'assess', 'assessed', 'assessing', '\"Assessment\" is the noun; \"assess\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'commitment', 'The team showed strong _____.', 'commitment', 'commit', 'committed', 'committing', '\"Commitment\" is the noun form of \"commit\".'),
('Grammar and Structure', 'Noun Form', 'development', 'Economic _____ requires investment.', 'development', 'develop', 'developed', 'developing', '\"Development\" is the noun; \"develop\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'employment', '_____ opportunities are increasing.', 'Employment', 'employ', 'employed', 'employing', '\"Employment\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'engagement', 'The couple announced their _____.', 'engagement', 'engage', 'engaged', 'engaging', '\"Engagement\" is the noun; \"engage\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'enjoyment', 'The audience\'s _____ was obvious.', 'enjoyment', 'enjoy', 'enjoyed', 'enjoying', '\"Enjoyment\" is the noun form of \"enjoy\".'),
('Grammar and Structure', 'Noun Form', 'fulfillment', 'Personal _____ comes from meaningful work.', 'fulfillment', 'fulfill', 'fulfilled', 'fulfilling', '\"Fulfillment\" is the noun; \"fulfill\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'government', 'The _____ launched a new initiative.', 'government', 'govern', 'governed', 'governing', '\"Government\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'investment', 'Foreign _____ grew by 15%.', 'investment', 'invest', 'invested', 'investing', '\"Investment\" is the noun; \"invest\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'judgment', 'Use your best _____.', 'judgment', 'judge', 'judged', 'judging', '\"Judgment\" is the noun form of \"judge\".'),
('Grammar and Structure', 'Noun Form', 'payment', 'Online _____ is required.', 'payment', 'pay', 'paid', 'paying', '\"Payment\" is the noun; \"pay\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'requirement', 'The basic _____ is a high school diploma.', 'requirement', 'require', 'required', 'requiring', '\"Requirement\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'settlement', 'The legal _____ was reached out of court.', 'settlement', 'settle', 'settled', 'settling', '\"Settlement\" is the noun; \"settle\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'acceptance', 'The _____ of the new policy took three months.', 'acceptance', 'accept', 'accepted', 'accepting', '\"Acceptance\" is the noun form; \"accept\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'productivity', 'Workplace _____ increased by 20%.', 'productivity', 'produce', 'productive', 'producing', '\"Productivity\" is the noun; \"productive\" is an adjective.'),
('Grammar and Structure', 'Noun Form', 'legislature', 'The national _____ passed the bill yesterday.', 'legislature', 'legislate', 'legislative', 'legislating', '\"Legislature\" refers to the law-making body.'),
('Grammar and Structure', 'Noun Form', 'dependence', 'Economic _____ on imports worries analysts.', 'dependence', 'depend', 'dependent', 'depending', '\"Dependence\" is the noun form of \"depend\".'),
('Grammar and Structure', 'Noun Form', 'effectiveness', 'The _____ of the program will be evaluated.', 'effectiveness', 'effect', 'effective', 'effecting', '\"Effectiveness\" is the noun; \"effective\" is an adjective.'),
('Grammar and Structure', 'Noun Form', 'leadership', 'Her _____ during the crisis was commendable.', 'leadership', 'lead', 'leader', 'leading', '\"Leadership\" is the abstract noun; \"leader\" is a person.'),
('Grammar and Structure', 'Noun Form', 'failure', 'The project\'s _____ resulted from poor planning.', 'failure', 'fail', 'failed', 'failing', '\"Failure\" is the noun; \"fail\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'approval', 'Committee _____ is required for funding.', 'approval', 'approve', 'approved', 'approving', '\"Approval\" is the noun form of \"approve\".'),
('Grammar and Structure', 'Noun Form', 'resistance', 'The proposal met strong _____.', 'resistance', 'resist', 'resistant', 'resisting', '\"Resistance\" is the noun; \"resist\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'compliance', 'Strict _____ with regulations is mandatory.', 'compliance', 'comply', 'compliant', 'complying', '\"Compliance\" is the noun form.'),
('Grammar and Structure', 'Noun Form', 'discovery', 'The scientific _____ made headlines.', 'discovery', 'discover', 'discovered', 'discovering', '\"Discovery\" is the noun; \"discover\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'delivery', 'The _____ of services improved significantly.', 'delivery', 'deliver', 'delivered', 'delivering', '\"Delivery\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'recovery', 'Economic _____ remains slow.', 'recovery', 'recover', 'recovered', 'recovering', '\"Recovery\" is the noun; \"recover\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'survival', 'The species\' _____ is now ensured.', 'survival', 'survive', 'survived', 'surviving', '\"Survival\" is the noun form of \"survive\".'),
('Grammar and Structure', 'Noun Form', 'refusal', 'His _____ to cooperate surprised everyone.', 'refusal', 'refuse', 'refused', 'refusing', '\"Refusal\" is the noun; \"refuse\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'removal', 'The _____ of outdated rules is necessary.', 'removal', 'remove', 'removed', 'removing', '\"Removal\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'arrival', 'The _____ of the delegation was delayed.', 'arrival', 'arrive', 'arrived', 'arriving', '\"Arrival\" is the noun; \"arrive\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'proposal', 'The _____ was submitted to the council.', 'proposal', 'propose', 'proposed', 'proposing', '\"Proposal\" is the noun form of \"propose\".'),
('Grammar and Structure', 'Noun Form', 'renewal', 'License _____ requires documentation.', 'renewal', 'renew', 'renewed', 'renewing', '\"Renewal\" is the noun; \"renew\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'approval', 'The board granted final _____.', 'approval', 'approve', 'approved', 'approving', '\"Approval\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'denial', 'His _____ of the allegations was expected.', 'denial', 'deny', 'denied', 'denying', '\"Denial\" is the noun; \"deny\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'trial', 'The _____ lasted six months.', 'trial', 'try', 'tried', 'trying', '\"Trial\" is the noun form of \"try\".'),
('Grammar and Structure', 'Noun Form', 'dismissal', 'The _____ of the case disappointed many.', 'dismissal', 'dismiss', 'dismissed', 'dismissing', '\"Dismissal\" is the noun; \"dismiss\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'rehearsal', 'The wedding _____ went smoothly.', 'rehearsal', 'rehearse', 'rehearsed', 'rehearsing', '\"Rehearsal\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'disposal', 'Proper _____ of hazardous waste is crucial.', 'disposal', 'dispose', 'disposed', 'disposing', '\"Disposal\" is the noun; \"dispose\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'reversal', 'The court ordered a _____ of the decision.', 'reversal', 'reverse', 'reversed', 'reversing', '\"Reversal\" is the noun form of \"reverse\".'),
('Grammar and Structure', 'Noun Form', 'approval', 'The director gave verbal _____.', 'approval', 'approve', 'approved', 'approving', '\"Approval\" is the noun; \"approve\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'arrival', 'Early _____ is recommended.', 'arrival', 'arrive', 'arrived', 'arriving', '\"Arrival\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'refusal', 'Her _____ was polite but firm.', 'refusal', 'refuse', 'refused', 'refusing', '\"Refusal\" is the noun; \"refuse\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'proposal', 'The budget _____ was rejected.', 'proposal', 'propose', 'proposed', 'proposing', '\"Proposal\" is the noun form of \"propose\".'),
('Grammar and Structure', 'Noun Form', 'removal', '_____ of the statue caused controversy.', 'Removal', 'Remove', 'Removed', 'Removing', '\"Removal\" is the noun; \"remove\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'survival', 'Basic _____ skills are taught.', 'survival', 'survive', 'survived', 'surviving', '\"Survival\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'trial', 'The free _____ period ends Friday.', 'trial', 'try', 'tried', 'trying', '\"Trial\" is the noun; \"try\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'dismissal', 'Unfair _____ claims were filed.', 'dismissal', 'dismiss', 'dismissed', 'dismissing', '\"Dismissal\" is the noun form of \"dismiss\".'),
('Grammar and Structure', 'Noun Form', 'renewal', 'Passport _____ takes two weeks.', 'renewal', 'renew', 'renewed', 'renewing', '\"Renewal\" is the noun; \"renew\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'disposal', 'Waste _____ systems were upgraded.', 'disposal', 'dispose', 'disposed', 'disposing', '\"Disposal\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'reversal', 'Policy _____ confused stakeholders.', 'reversal', 'reverse', 'reversed', 'reversing', '\"Reversal\" is the noun; \"reverse\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'denial', 'The official _____ stopped rumors.', 'denial', 'deny', 'denied', 'denying', '\"Denial\" is the noun form of \"deny\".'),
('Grammar and Structure', 'Noun Form', 'arrival', 'The _____ gate changed unexpectedly.', 'arrival', 'arrive', 'arrived', 'arriving', '\"Arrival\" is the noun; \"arrive\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'rehearsal', 'Dress _____ begins at 7 PM.', 'rehearsal', 'rehearse', 'rehearsed', 'rehearsing', '\"Rehearsal\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'approval', 'The _____ rating reached 75%.', 'approval', 'approve', 'approved', 'approving', '\"Approval\" is the noun; \"approve\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'dependence', 'Energy _____ decreased by 10%.', 'dependence', 'depend', 'dependent', 'depending', '\"Dependence\" is the noun form of \"depend\".'),
('Grammar and Structure', 'Noun Form', 'discovery', 'The archaeological _____ rewrote history.', 'discovery', 'discover', 'discovered', 'discovering', '\"Discovery\" is the noun; \"discover\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'delivery', 'The _____ schedule was disrupted.', 'delivery', 'deliver', 'delivered', 'delivering', '\"Delivery\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'recovery', 'Patient _____ exceeded expectations.', 'recovery', 'recover', 'recovered', 'recovering', '\"Recovery\" is the noun; \"recover\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'legislation', 'New _____ on data privacy was enacted.', 'legislation', 'legislate', 'legislative', 'legislating', '\"Legislation\" is the noun; \"legislate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'compliance', 'Strict _____ with protocols is mandatory.', 'compliance', 'comply', 'compliant', 'complying', '\"Compliance\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'implementation', 'The _____ plan starts next quarter.', 'implementation', 'implement', 'implemented', 'implementing', '\"Implementation\" is the noun form of \"implement\".'),
('Grammar and Structure', 'Noun Form', 'accountability', 'Public _____ ensures transparency.', 'accountability', 'account', 'accountable', 'accounting', '\"Accountability\" is the abstract noun; \"accountable\" is an adjective.'),
('Grammar and Structure', 'Noun Form', 'regulation', 'Financial _____ prevent fraud.', 'regulations', 'regulate', 'regulatory', 'regulating', '\"Regulations\" is the noun; \"regulate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'verification', 'Document _____ takes 48 hours.', 'verification', 'verify', 'verified', 'verifying', '\"Verification\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'cooperation', 'International _____ strengthened the initiative.', 'cooperation', 'cooperate', 'cooperative', 'cooperating', '\"Cooperation\" is the noun; \"cooperate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'representation', 'Fair _____ of minorities improved.', 'representation', 'represent', 'representative', 'representing', '\"Representation\" is the noun form.'),
('Grammar and Structure', 'Noun Form', 'accreditation', 'The _____ process requires site visits.', 'accreditation', 'accredit', 'accredited', 'accrediting', '\"Accreditation\" is the noun; \"accredit\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'notification', 'Immediate _____ is sent via SMS.', 'notification', 'notify', 'notified', 'notifying', '\"Notification\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'endorsement', 'The mayor\'s _____ boosted the program.', 'endorsement', 'endorse', 'endorsed', 'endorsing', '\"Endorsement\" is the noun; \"endorse\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'enforcement', 'Traffic _____ reduced accidents.', 'enforcement', 'enforce', 'enforced', 'enforcing', '\"Enforcement\" is the noun form of \"enforce\".'),
('Grammar and Structure', 'Noun Form', 'assessment', 'Tax _____ occurs annually.', 'assessments', 'assess', 'assessed', 'assessing', '\"Assessments\" is the plural noun; \"assess\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'clearance', 'Security _____ is required for access.', 'clearance', 'clear', 'cleared', 'clearing', '\"Clearance\" is the noun; \"clear\" is a verb/adjective.'),
('Grammar and Structure', 'Noun Form', 'disbursement', 'Fund _____ follows strict guidelines.', 'disbursement', 'disburse', 'disbursed', 'disbursing', '\"Disbursement\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'establishment', 'The _____ of new offices was approved.', 'establishment', 'establish', 'established', 'establishing', '\"Establishment\" is the noun; \"establish\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'governance', 'Corporate _____ standards improved.', 'governance', 'govern', 'governing', 'governed', '\"Governance\" is the abstract noun; \"govern\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'maintenance', 'Infrastructure _____ is ongoing.', 'maintenance', 'maintain', 'maintained', 'maintaining', '\"Maintenance\" is the noun form of \"maintain\".'),
('Grammar and Structure', 'Noun Form', 'procurement', 'The _____ process was streamlined.', 'procurement', 'procure', 'procured', 'procuring', '\"Procurement\" is the noun; \"procure\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'renewal', 'License _____ requires biometrics.', 'renewal', 'renew', 'renewed', 'renewing', '\"Renewal\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'surveillance', 'Enhanced _____ improved security.', 'surveillance', 'surveil', 'surveilled', 'surveilling', '\"Surveillance\" is the noun; \"surveil\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'validation', 'Data _____ ensures accuracy.', 'validation', 'validate', 'validated', 'validating', '\"Validation\" is the noun form.'),
('Grammar and Structure', 'Noun Form', 'acquisition', 'Asset _____ followed protocols.', 'acquisition', 'acquire', 'acquired', 'acquiring', '\"Acquisition\" is the noun; \"acquire\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'adjudication', 'Case _____ took six months.', 'adjudication', 'adjudicate', 'adjudicated', 'adjudicating', '\"Adjudication\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'compilation', 'The _____ of reports is complete.', 'compilation', 'compile', 'compiled', 'compiling', '\"Compilation\" is the noun; \"compile\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'conciliation', 'Labor _____ resolved disputes.', 'conciliation', 'conciliate', 'conciliated', 'conciliating', '\"Conciliation\" is the noun form of \"conciliate\".'),
('Grammar and Structure', 'Noun Form', 'delegation', 'The _____ visited Manila last week.', 'delegation', 'delegate', 'delegated', 'delegating', '\"Delegation\" is the noun; \"delegate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'evaluation', 'Performance _____ occurs quarterly.', 'evaluation', 'evaluate', 'evaluated', 'evaluating', '\"Evaluation\" is the noun; \"evaluate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'formulation', 'Policy _____ involved stakeholders.', 'formulation', 'formulate', 'formulated', 'formulating', '\"Formulation\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'inspection', 'Safety _____ prevented accidents.', 'inspections', 'inspect', 'inspected', 'inspecting', '\"Inspections\" is the plural noun; \"inspect\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'modification', 'Document _____ requires approval.', 'modification', 'modify', 'modified', 'modifying', '\"Modification\" is the noun; \"modify\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'notification', 'Emergency _____ systems were tested.', 'notification', 'notify', 'notified', 'notifying', '\"Notification\" is the noun form.'),
('Grammar and Structure', 'Noun Form', 'registration', 'Online _____ simplified enrollment.', 'registration', 'register', 'registered', 'registering', '\"Registration\" is the noun; \"register\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'restoration', 'Heritage _____ preserved history.', 'restoration', 'restore', 'restored', 'restoring', '\"Restoration\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'supervision', 'Direct _____ ensured quality.', 'supervision', 'supervise', 'supervised', 'supervising', '\"Supervision\" is the noun; \"supervise\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'transaction', 'The _____ was recorded digitally.', 'transaction', 'transact', 'transacted', 'transacting', '\"Transaction\" is the noun form of \"transact\".'),
('Grammar and Structure', 'Noun Form', 'utilization', 'Resource _____ reached 90%.', 'utilization', 'utilize', 'utilized', 'utilizing', '\"Utilization\" is the noun; \"utilize\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'verification', 'Identity _____ prevented fraud.', 'verification', 'verify', 'verified', 'verifying', '\"Verification\" is the noun; \"verify\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'authorization', 'Prior _____ is required.', 'authorization', 'authorize', 'authorized', 'authorizing', '\"Authorization\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'certification', 'The _____ process takes two weeks.', 'certification', 'certify', 'certified', 'certifying', '\"Certification\" is the noun; \"certify\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'classification', 'Data _____ protects privacy.', 'classification', 'classify', 'classified', 'classifying', '\"Classification\" is the noun form.'),
('Grammar and Structure', 'Noun Form', 'compensation', 'Employee _____ was reviewed.', 'compensation', 'compensate', 'compensated', 'compensating', '\"Compensation\" is the noun; \"compensate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'consolidation', 'Department _____ improved efficiency.', 'consolidation', 'consolidate', 'consolidated', 'consolidating', '\"Consolidation\" is the noun; \"consolidate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'coordination', 'Inter-agency _____ succeeded.', 'coordination', 'coordinate', 'coordinated', 'coordinating', '\"Coordination\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'documentation', 'Proper _____ avoided disputes.', 'documentation', 'document', 'documented', 'documenting', '\"Documentation\" is the noun; \"document\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'identification', 'Photo _____ is mandatory.', 'identification', 'identify', 'identified', 'identifying', '\"Identification\" is the noun form of \"identify\".'),
('Grammar and Structure', 'Noun Form', 'justification', 'The _____ was accepted.', 'justification', 'justify', 'justified', 'justifying', '\"Justification\" is the noun; \"justify\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'qualification', 'Job _____ were updated.', 'qualifications', 'qualify', 'qualified', 'qualifying', '\"Qualifications\" is the plural noun; \"qualify\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'ratification', 'Treaty _____ occurred yesterday.', 'ratification', 'ratify', 'ratified', 'ratifying', '\"Ratification\" is the noun; \"ratify\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'standardization', 'Process _____ ensured consistency.', 'standardization', 'standardize', 'standardized', 'standardizing', '\"Standardization\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'submission', 'Report _____ deadlines are strict.', 'submission', 'submit', 'submitted', 'submitting', '\"Submission\" is the noun; \"submit\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'violation', 'Any _____ incurs penalties.', 'violation', 'violate', 'violated', 'violating', '\"Violation\" is the noun form of \"violate\".'),
('Grammar and Structure', 'Noun Form', 'allocation', 'Budget _____ was equitable.', 'allocation', 'allocate', 'allocated', 'allocating', '\"Allocation\" is the noun; \"allocate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'legislation', 'The new _____ on cybercrime passed unanimously.', 'legislation', 'legislate', 'legislative', 'legislating', '\"Legislation\" is the noun; \"legislate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'compliance', 'Strict _____ with tax laws is mandatory.', 'compliance', 'comply', 'compliant', 'complying', '\"Compliance\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'implementation', 'The _____ of the policy starts Monday.', 'implementation', 'implement', 'implemented', 'implementing', '\"Implementation\" is the noun form of \"implement\".'),
('Grammar and Structure', 'Noun Form', 'accountability', 'Public officer _____ is non-negotiable.', 'accountability', 'account', 'accountable', 'accounting', '\"Accountability\" is the abstract noun; \"accountable\" is an adjective.'),
('Grammar and Structure', 'Noun Form', 'regulation', 'Safety _____ prevent workplace accidents.', 'regulations', 'regulate', 'regulatory', 'regulating', '\"Regulations\" is the noun; \"regulate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'verification', 'Document _____ requires two signatures.', 'verification', 'verify', 'verified', 'verifying', '\"Verification\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'cooperation', 'Inter-agency _____ solved the case.', 'cooperation', 'cooperate', 'cooperative', 'cooperating', '\"Cooperation\" is the noun; \"cooperate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'representation', 'Fair ethnic _____ in government is vital.', 'representation', 'represent', 'representative', 'representing', '\"Representation\" is the noun form.'),
('Grammar and Structure', 'Noun Form', 'accreditation', 'The _____ process includes audits.', 'accreditation', 'accredit', 'accredited', 'accrediting', '\"Accreditation\" is the noun; \"accredit\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'notification', 'Immediate _____ of changes is required.', 'notification', 'notify', 'notified', 'notifying', '\"Notification\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'endorsement', 'The governor\'s _____ boosted tourism.', 'endorsement', 'endorse', 'endorsed', 'endorsing', '\"Endorsement\" is the noun; \"endorse\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'enforcement', 'Traffic law _____ reduces accidents.', 'enforcement', 'enforce', 'enforced', 'enforcing', '\"Enforcement\" is the noun form of \"enforce\".'),
('Grammar and Structure', 'Noun Form', 'assessment', 'Property tax _____ occurs quarterly.', 'assessments', 'assess', 'assessed', 'assessing', '\"Assessments\" is the plural noun; \"assess\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'clearance', 'Security _____ is needed for entry.', 'clearance', 'clear', 'cleared', 'clearing', '\"Clearance\" is the noun; \"clear\" is a verb/adjective.'),
('Grammar and Structure', 'Noun Form', 'disbursement', 'Fund _____ follows strict protocols.', 'disbursement', 'disburse', 'disbursed', 'disbursing', '\"Disbursement\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'maintenance', 'Infrastructure _____ prevents decay.', 'maintenance', 'maintain', 'maintained', 'maintaining', '\"Maintenance\" is the noun form of \"maintain\".'),
('Grammar and Structure', 'Noun Form', 'procurement', 'The _____ of equipment was transparent.', 'procurement', 'procure', 'procured', 'procuring', '\"Procurement\" is the noun; \"procure\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'acquisition', 'Asset _____ followed regulations.', 'acquisition', 'acquire', 'acquired', 'acquiring', '\"Acquisition\" is the noun; \"acquire\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'compilation', 'The _____ of reports took weeks.', 'compilation', 'compile', 'compiled', 'compiling', '\"Compilation\" is the noun; \"compile\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'conciliation', 'Labor _____ resolved conflicts.', 'conciliation', 'conciliate', 'conciliated', 'conciliating', '\"Conciliation\" is the noun form of \"conciliate\".'),
('Grammar and Structure', 'Noun Form', 'delegation', 'The diplomatic _____ arrived today.', 'delegation', 'delegate', 'delegated', 'delegating', '\"Delegation\" is the noun; \"delegate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'evaluation', 'Performance _____ occurs annually.', 'evaluation', 'evaluate', 'evaluated', 'evaluating', '\"Evaluation\" is the noun; \"evaluate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'formulation', 'Policy _____ involved experts.', 'formulation', 'formulate', 'formulated', 'formulating', '\"Formulation\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'inspection', 'Safety _____ prevented disasters.', 'inspections', 'inspect', 'inspected', 'inspecting', '\"Inspections\" is the plural noun; \"inspect\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'modification', 'Contract _____ requires consent.', 'modification', 'modify', 'modified', 'modifying', '\"Modification\" is the noun; \"modify\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'registration', 'Voter _____ increased this year.', 'registration', 'register', 'registered', 'registering', '\"Registration\" is the noun form.'),
('Grammar and Structure', 'Noun Form', 'restoration', 'Historical _____ preserved heritage.', 'restoration', 'restore', 'restored', 'restoring', '\"Restoration\" is the noun; \"restore\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'supervision', 'Direct _____ improved outcomes.', 'supervision', 'supervise', 'supervised', 'supervising', '\"Supervision\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'transaction', 'The financial _____ was recorded.', 'transaction', 'transact', 'transacted', 'transacting', '\"Transaction\" is the noun form of \"transact\".'),
('Grammar and Structure', 'Noun Form', 'utilization', 'Resource _____ reached 95%.', 'utilization', 'utilize', 'utilized', 'utilizing', '\"Utilization\" is the noun; \"utilize\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'certification', 'Professional _____ enhances credibility.', 'certification', 'certify', 'certified', 'certifying', '\"Certification\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'consolidation', 'Department _____ saved costs.', 'consolidation', 'consolidate', 'consolidated', 'consolidating', '\"Consolidation\" is the noun; \"consolidate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'coordination', 'Project _____ succeeded.', 'coordination', 'coordinate', 'coordinated', 'coordinating', '\"Coordination\" is the noun; \"coordinate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'justification', 'The budgetary _____ was accepted.', 'justification', 'justify', 'justified', 'justifying', '\"Justification\" is the noun; \"justify\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'ratification', 'The treaty\'s _____ occurred today.', 'ratification', 'ratify', 'ratified', 'ratifying', '\"Ratification\" is the noun; \"ratify\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'standardization', 'Process _____ ensured quality.', 'standardization', 'standardize', 'standardized', 'standardizing', '\"Standardization\" is the noun; \"standardize\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'submission', 'Report _____ deadlines are fixed.', 'submission', 'submit', 'submitted', 'submitting', '\"Submission\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'establishment', 'The _____ of new agencies was approved.', 'establishment', 'establish', 'established', 'establishing', '\"Establishment\" is the noun form.'),
('Grammar and Structure', 'Noun Form', 'compliance', 'Strict _____ with tax laws is enforced.', 'compliance', 'comply', 'compliant', 'complying', '\"Compliance\" is the correct noun form; \"comply\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'implementation', 'The policy\'s _____ begins next month.', 'implementation', 'implement', 'implemented', 'implementing', '\"Implementation\" is the noun form of \"implement\".'),
('Grammar and Structure', 'Noun Form', 'accountability', 'Public officer _____ is essential.', 'accountability', 'account', 'accountable', 'accounting', '\"Accountability\" is the abstract noun; \"accountable\" is an adjective.'),
('Grammar and Structure', 'Noun Form', 'regulation', 'Safety _____ prevent accidents.', 'regulations', 'regulate', 'regulatory', 'regulating', '\"Regulations\" is the plural noun; \"regulate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'cooperation', 'Inter-agency _____ solved the crisis.', 'cooperation', 'cooperate', 'cooperative', 'cooperating', '\"Cooperation\" is the noun; \"cooperate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'representation', 'Fair _____ in government is crucial.', 'representation', 'represent', 'representative', 'representing', '\"Representation\" is the noun form.'),
('Grammar and Structure', 'Noun Form', 'notification', 'Immediate _____ is required.', 'notification', 'notify', 'notified', 'notifying', '\"Notification\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'endorsement', 'The mayor\'s _____ helped the project.', 'endorsement', 'endorse', 'endorsed', 'endorsing', '\"Endorsement\" is the noun; \"endorse\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'enforcement', 'Law _____ reduced violations.', 'enforcement', 'enforce', 'enforced', 'enforcing', '\"Enforcement\" is the noun form of \"enforce\".'),
('Grammar and Structure', 'Noun Form', 'clearance', 'Security _____ is mandatory.', 'clearance', 'clear', 'cleared', 'clearing', '\"Clearance\" is the noun; \"clear\" is a verb/adjective.'),
('Grammar and Structure', 'Noun Form', 'disbursement', 'Fund _____ follows protocols.', 'disbursement', 'disburse', 'disbursed', 'disbursing', '\"Disbursement\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'governance', 'Corporate _____ improved.', 'governance', 'govern', 'governing', 'governed', '\"Governance\" is the abstract noun; \"govern\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'procurement', 'Equipment _____ was transparent.', 'procurement', 'procure', 'procured', 'procuring', '\"Procurement\" is the noun; \"procure\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'renewal', 'License _____ requires documents.', 'renewal', 'renew', 'renewed', 'renewing', '\"Renewal\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'acquisition', 'Asset _____ followed rules.', 'acquisition', 'acquire', 'acquired', 'acquiring', '\"Acquisition\" is the noun; \"acquire\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'compilation', 'Report _____ took weeks.', 'compilation', 'compile', 'compiled', 'compiling', '\"Compilation\" is the noun; \"compile\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'conciliation', 'Labor _____ resolved issues.', 'conciliation', 'conciliate', 'conciliated', 'conciliating', '\"Conciliation\" is the noun form of \"conciliate\".'),
('Grammar and Structure', 'Noun Form', 'delegation', 'The _____ arrived yesterday.', 'delegation', 'delegate', 'delegated', 'delegating', '\"Delegation\" is the noun; \"delegate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'evaluation', 'Performance _____ is annual.', 'evaluation', 'evaluate', 'evaluated', 'evaluating', '\"Evaluation\" is the noun; \"evaluate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'modification', 'Contract _____ needs approval.', 'modification', 'modify', 'modified', 'modifying', '\"Modification\" is the noun; \"modify\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'registration', 'Voter _____ increased.', 'registration', 'register', 'registered', 'registering', '\"Registration\" is the noun form.'),
('Grammar and Structure', 'Noun Form', 'restoration', 'Heritage _____ preserved culture.', 'restoration', 'restore', 'restored', 'restoring', '\"Restoration\" is the noun; \"restore\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'supervision', 'Direct _____ improved quality.', 'supervision', 'supervise', 'supervised', 'supervising', '\"Supervision\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'transaction', 'The _____ was recorded.', 'transaction', 'transact', 'transacted', 'transacting', '\"Transaction\" is the noun form of \"transact\".'),
('Grammar and Structure', 'Noun Form', 'authorization', 'Prior _____ is needed.', 'authorization', 'authorize', 'authorized', 'authorizing', '\"Authorization\" is the noun; \"authorize\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'certification', 'Professional _____ adds credibility.', 'certification', 'certify', 'certified', 'certifying', '\"Certification\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'classification', 'Data _____ protects information.', 'classification', 'classify', 'classified', 'classifying', '\"Classification\" is the noun form.'),
('Grammar and Structure', 'Noun Form', 'documentation', 'Proper _____ prevented disputes.', 'documentation', 'document', 'documented', 'documenting', '\"Documentation\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'identification', 'Photo _____ is required.', 'identification', 'identify', 'identified', 'identifying', '\"Identification\" is the noun form of \"identify\".'),
('Grammar and Structure', 'Noun Form', 'ratification', 'Treaty _____ occurred.', 'ratification', 'ratify', 'ratified', 'ratifying', '\"Ratification\" is the noun; \"ratify\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'allocation', 'Budget _____ was fair.', 'allocation', 'allocate', 'allocated', 'allocating', '\"Allocation\" is the noun; \"allocate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'establishment', 'New agency _____ was approved.', 'establishment', 'establish', 'established', 'establishing', '\"Establishment\" is the noun form.'),
('Grammar and Structure', 'Noun Form', 'legislation', 'New _____ on cybersecurity was passed.', 'legislation', 'legislate', 'legislative', 'legislating', '\"Legislation\" is the noun; \"legislate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'implementation', 'Policy _____ begins next quarter.', 'implementation', 'implement', 'implemented', 'implementing', '\"Implementation\" is the noun form of \"implement\".'),
('Grammar and Structure', 'Noun Form', 'accountability', 'Public official _____ is crucial.', 'accountability', 'account', 'accountable', 'accounting', '\"Accountability\" is the abstract noun; \"accountable\" is an adjective.'),
('Grammar and Structure', 'Noun Form', 'regulation', 'Banking _____ prevent fraud.', 'regulations', 'regulate', 'regulatory', 'regulating', '\"Regulations\" is the plural noun; \"regulate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'verification', 'Document _____ requires authorization.', 'verification', 'verify', 'verified', 'verifying', '\"Verification\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'cooperation', 'Inter-agency _____ improved efficiency.', 'cooperation', 'cooperate', 'cooperative', 'cooperating', '\"Cooperation\" is the noun; \"cooperate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'representation', 'Fair political _____ is essential.', 'representation', 'represent', 'representative', 'representing', '\"Representation\" is the noun form.'),
('Grammar and Structure', 'Noun Form', 'accreditation', 'The _____ process includes evaluation.', 'accreditation', 'accredit', 'accredited', 'accrediting', '\"Accreditation\" is the noun; \"accredit\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'notification', 'Immediate _____ is sent via email.', 'notification', 'notify', 'notified', 'notifying', '\"Notification\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'endorsement', 'The senator\'s _____ boosted the bill.', 'endorsement', 'endorse', 'endorsed', 'endorsing', '\"Endorsement\" is the noun; \"endorse\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'assessment', 'Property _____ occurs annually.', 'assessments', 'assess', 'assessed', 'assessing', '\"Assessments\" is the plural noun; \"assess\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'clearance', 'Security _____ is required.', 'clearance', 'clear', 'cleared', 'clearing', '\"Clearance\" is the noun; \"clear\" is a verb/adjective.'),
('Grammar and Structure', 'Noun Form', 'disbursement', 'Fund _____ follows guidelines.', 'disbursement', 'disburse', 'disbursed', 'disbursing', '\"Disbursement\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'governance', 'Corporate _____ standards rose.', 'governance', 'govern', 'governing', 'governed', '\"Governance\" is the abstract noun; \"govern\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'maintenance', 'Road _____ prevents deterioration.', 'maintenance', 'maintain', 'maintained', 'maintaining', '\"Maintenance\" is the noun form of \"maintain\".'),
('Grammar and Structure', 'Noun Form', 'validation', 'Data _____ ensures reliability.', 'validation', 'validate', 'validated', 'validating', '\"Validation\" is the noun form.'),
('Grammar and Structure', 'Noun Form', 'compilation', 'Report _____ took two weeks.', 'compilation', 'compile', 'compiled', 'compiling', '\"Compilation\" is the noun; \"compile\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'delegation', 'The official _____ arrived.', 'delegation', 'delegate', 'delegated', 'delegating', '\"Delegation\" is the noun; \"delegate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'formulation', 'Policy _____ involved consultation.', 'formulation', 'formulate', 'formulated', 'formulating', '\"Formulation\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'inspection', 'Safety _____ prevented incidents.', 'inspections', 'inspect', 'inspected', 'inspecting', '\"Inspections\" is the plural noun; \"inspect\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'supervision', 'Direct _____ ensured compliance.', 'supervision', 'supervise', 'supervised', 'supervising', '\"Supervision\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'transaction', 'The financial _____ was logged.', 'transaction', 'transact', 'transacted', 'transacting', '\"Transaction\" is the noun form of \"transact\".'),
('Grammar and Structure', 'Noun Form', 'certification', 'Professional _____ enhances trust.', 'certification', 'certify', 'certified', 'certifying', '\"Certification\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'classification', 'Data _____ protects confidentiality.', 'classification', 'classify', 'classified', 'classifying', '\"Classification\" is the noun form.'),
('Grammar and Structure', 'Noun Form', 'compensation', 'Employee _____ was fair.', 'compensation', 'compensate', 'compensated', 'compensating', '\"Compensation\" is the noun; \"compensate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'consolidation', 'Department _____ saved funds.', 'consolidation', 'consolidate', 'consolidated', 'consolidating', '\"Consolidation\" is the noun; \"consolidate\" is a verb.');
INSERT INTO `verbal` (`category`, `type`, `word`, `question`, `correct_answer`, `wrong_answer1`, `wrong_answer2`, `wrong_answer3`, `explanation`) VALUES
('Grammar and Structure', 'Noun Form', 'documentation', 'Proper _____ resolved issues.', 'documentation', 'document', 'documented', 'documenting', '\"Documentation\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'identification', 'Photo _____ is compulsory.', 'identification', 'identify', 'identified', 'identifying', '\"Identification\" is the noun form of \"identify\".'),
('Grammar and Structure', 'Noun Form', 'qualification', 'Job _____ were revised.', 'qualifications', 'qualify', 'qualified', 'qualifying', '\"Qualifications\" is the plural noun; \"qualify\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'ratification', 'The treaty\'s _____ occurred.', 'ratification', 'ratify', 'ratified', 'ratifying', '\"Ratification\" is the noun; \"ratify\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'violation', 'Any _____ incurs fines.', 'violation', 'violate', 'violated', 'violating', '\"Violation\" is the noun form of \"violate\".'),
('Grammar and Structure', 'Noun Form', 'surveillance', 'Security _____ was enhanced.', 'surveillance', 'surveil', 'surveilled', 'surveilling', '\"Surveillance\" is the noun; \"surveil\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'adjudication', 'Case _____ took months.', 'adjudication', 'adjudicate', 'adjudicated', 'adjudicating', '\"Adjudication\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'compliance', 'Strict _____ with regulations is enforced.', 'compliance', 'comply', 'compliant', 'complying', '\"Compliance\" is the correct noun form; \"comply\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'legislation', 'New _____ on cybersecurity was enacted.', 'legislation', 'legislate', 'legislative', 'legislating', '\"Legislation\" is the noun; \"legislate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'accountability', 'Public official _____ is non-negotiable.', 'accountability', 'account', 'accountable', 'accounting', '\"Accountability\" is the abstract noun; \"accountable\" is an adjective.'),
('Grammar and Structure', 'Noun Form', 'regulation', 'Banking _____ prevent financial fraud.', 'regulations', 'regulate', 'regulatory', 'regulating', '\"Regulations\" is the plural noun; \"regulate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'cooperation', 'Inter-agency _____ improved services.', 'cooperation', 'cooperate', 'cooperative', 'cooperating', '\"Cooperation\" is the noun; \"cooperate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'representation', 'Fair _____ in governance is essential.', 'representation', 'represent', 'representative', 'representing', '\"Representation\" is the noun form.'),
('Grammar and Structure', 'Noun Form', 'accreditation', 'Institutional _____ ensures standards.', 'accreditation', 'accredit', 'accredited', 'accrediting', '\"Accreditation\" is the noun; \"accredit\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'notification', 'Emergency _____ is sent via SMS.', 'notification', 'notify', 'notified', 'notifying', '\"Notification\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'endorsement', 'The mayor\'s _____ supported the project.', 'endorsement', 'endorse', 'endorsed', 'endorsing', '\"Endorsement\" is the noun; \"endorse\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'assessment', 'Tax _____ occurs biannually.', 'assessments', 'assess', 'assessed', 'assessing', '\"Assessments\" is the plural noun; \"assess\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'delegation', 'The diplomatic _____ arrived.', 'delegation', 'delegate', 'delegated', 'delegating', '\"Delegation\" is the noun; \"delegate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'transaction', 'Financial _____ were recorded.', 'transactions', 'transact', 'transacted', 'transacting', '\"Transactions\" is the plural noun; \"transact\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'coordination', 'Interdepartmental _____ succeeded.', 'coordination', 'coordinate', 'coordinated', 'coordinating', '\"Coordination\" is the noun; \"coordinate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'documentation', 'Proper _____ resolved disputes.', 'documentation', 'document', 'documented', 'documenting', '\"Documentation\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'distribution', 'Resource _____ was equitable.', 'distribution', 'distribute', 'distributed', 'distributing', '\"Distribution\" is the noun form.'),
('Grammar and Structure', 'Noun Form', 'nomination', 'The _____ deadline is Friday.', 'nomination', 'nominate', 'nominated', 'nominating', '\"Nomination\" is the noun; \"nominate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'verification', 'Document _____ requires signatures.', 'verification', 'verify', 'verified', 'verifying', '\"Verification\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'notification', 'Emergency _____ is sent immediately.', 'notification', 'notify', 'notified', 'notifying', '\"Notification\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'endorsement', 'The governor\'s _____ supported the initiative.', 'endorsement', 'endorse', 'endorsed', 'endorsing', '\"Endorsement\" is the noun; \"endorse\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'utilization', 'Resource _____ reached 98%.', 'utilization', 'utilize', 'utilized', 'utilizing', '\"Utilization\" is the noun; \"utilize\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'distribution', 'Resource _____ was fair.', 'distribution', 'distribute', 'distributed', 'distributing', '\"Distribution\" is the noun form.'),
('Grammar and Structure', 'Noun Form', 'regulation', 'Environmental _____ were strengthened.', 'regulations', 'regulate', 'regulatory', 'regulating', '\"Regulations\" is the plural noun; \"regulate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'legislation', 'New _____ on cybercrime was enacted.', 'legislation', 'legislate', 'legislative', 'legislating', '\"Legislation\" is the noun; \"legislate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'accountability', 'Public official _____ is essential.', 'accountability', 'account', 'accountable', 'accounting', '\"Accountability\" is the abstract noun; \"accountable\" is an adjective.'),
('Grammar and Structure', 'Noun Form', 'representation', 'Fair political _____ is crucial.', 'representation', 'represent', 'representative', 'representing', '\"Representation\" is the noun form.'),
('Grammar and Structure', 'Noun Form', 'accreditation', 'Institutional _____ maintains standards.', 'accreditation', 'accredit', 'accredited', 'accrediting', '\"Accreditation\" is the noun; \"accredit\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'endorsement', 'The mayor\'s _____ helped the initiative.', 'endorsement', 'endorse', 'endorsed', 'endorsing', '\"Endorsement\" is the noun; \"endorse\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'enforcement', 'Law _____ reduced crime.', 'enforcement', 'enforce', 'enforced', 'enforcing', '\"Enforcement\" is the noun form of \"enforce\".'),
('Grammar and Structure', 'Noun Form', 'maintenance', 'Infrastructure _____ prevents deterioration.', 'maintenance', 'maintain', 'maintained', 'maintaining', '\"Maintenance\" is the noun form of \"maintain\".'),
('Grammar and Structure', 'Noun Form', 'nomination', 'The _____ deadline is tomorrow.', 'nomination', 'nominate', 'nominated', 'nominating', '\"Nomination\" is the noun; \"nominate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'implementation', 'Policy _____ begins next month.', 'implementation', 'implement', 'implemented', 'implementing', '\"Implementation\" is the noun form of \"implement\".'),
('Grammar and Structure', 'Noun Form', 'endorsement', 'The governor\'s _____ supported the project.', 'endorsement', 'endorse', 'endorsed', 'endorsing', '\"Endorsement\" is the noun; \"endorse\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'enforcement', 'Traffic law _____ reduced accidents.', 'enforcement', 'enforce', 'enforced', 'enforcing', '\"Enforcement\" is the noun form of \"enforce\".'),
('Grammar and Structure', 'Noun Form', 'acceptance', 'The _____ rate increased to 85%.', 'acceptance', 'accept', 'accepted', 'accepting', '\"Acceptance\" is the noun; \"accept\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'appointment', 'The _____ was confirmed.', 'appointment', 'appoint', 'appointed', 'appointing', '\"Appointment\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'requirement', 'Basic _____ must be met.', 'requirements', 'require', 'required', 'requiring', '\"Requirements\" is the plural noun; \"require\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'endorsement', 'The governor\'s _____ helped the project.', 'endorsement', 'endorse', 'endorsed', 'endorsing', '\"Endorsement\" is the noun; \"endorse\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'endorsement', 'The senator\'s _____ helped the bill.', 'endorsement', 'endorse', 'endorsed', 'endorsing', '\"Endorsement\" is the noun; \"endorse\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'evaluation', 'Performance _____ is quarterly.', 'evaluation', 'evaluate', 'evaluated', 'evaluating', '\"Evaluation\" is the noun; \"evaluate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'registration', 'Voter _____ reached record levels.', 'registration', 'register', 'registered', 'registering', '\"Registration\" is the noun form.'),
('Grammar and Structure', 'Noun Form', 'transaction', 'Financial _____ were logged.', 'transactions', 'transact', 'transacted', 'transacting', '\"Transactions\" is the plural noun; \"transact\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'compensation', 'Employee _____ packages were revised.', 'compensation', 'compensate', 'compensated', 'compensating', '\"Compensation\" is the noun; \"compensate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'consolidation', 'Department _____ saved ₱2M annually.', 'consolidation', 'consolidate', 'consolidated', 'consolidating', '\"Consolidation\" is the noun; \"consolidate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'coordination', 'Interagency _____ succeeded.', 'coordination', 'coordinate', 'coordinated', 'coordinating', '\"Coordination\" is the noun; \"coordinate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'identification', 'Biometric _____ is mandatory.', 'identification', 'identify', 'identified', 'identifying', '\"Identification\" is the noun form of \"identify\".'),
('Grammar and Structure', 'Noun Form', 'qualification', 'Job _____ were upgraded.', 'qualifications', 'qualify', 'qualified', 'qualifying', '\"Qualifications\" is the plural noun; \"qualify\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'ratification', 'Treaty _____ was completed.', 'ratification', 'ratify', 'ratified', 'ratifying', '\"Ratification\" is the noun; \"ratify\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'adjudication', 'Case _____ took 180 days.', 'adjudication', 'adjudicate', 'adjudicated', 'adjudicating', '\"Adjudication\" is the correct noun form.'),
('Grammar and Structure', 'Noun Form', 'nomination', 'The _____ period closes Friday.', 'nomination', 'nominate', 'nominated', 'nominating', '\"Nomination\" is the noun; \"nominate\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'acceptance', 'The _____ rate was 90%.', 'acceptance', 'accept', 'accepted', 'accepting', '\"Acceptance\" is the noun; \"accept\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'requirement', 'Basic _____ must be fulfilled.', 'requirements', 'require', 'required', 'requiring', '\"Requirements\" is the plural noun; \"require\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'discovery', 'The scientific _____ was groundbreaking.', 'discovery', 'discover', 'discovered', 'discovering', '\"Discovery\" is the noun; \"discover\" is a verb.'),
('Grammar and Structure', 'Noun Form', 'improvement', 'Significant _____ was observed.', 'improvement', 'improve', 'improved', 'improving', '\"Improvement\" is the noun form of \"improve\".');




