INSERT INTO `2_Root_Word` ( `word`, `type`, `question`, `correct_answer`, `wrong_answer1`, `wrong_answer2`, `wrong_answer3`, `explanation`) VALUES
( 'abolish', 'Root Word', 'What is the root word of "abolish"?', 'abol', 'al', 'bish', 'ish', 'The root word of "abolish" is "abol," which comes from Latin meaning "to do away with."'),
( 'abortion', 'Root Word', 'What is the root word of "abortion"?', 'abort', 'ab', 'tion', 'ort', 'The root word of "abortion" is "abort," which comes from the Latin word "abortus," meaning "to miscarry or fail."'),
( 'absence', 'Root Word', 'What is the root word of "absence"?', 'absent', 'abs', 'ence', 'absentia', 'The root word of "absence" is "absent," which comes from Latin, meaning "not present."'),
( 'absent', 'Root Word', 'What is the root word of "absent"?', 'abs', 'absen', 'ent', 'absence', 'The root word of "absent" is "abs," which comes from Latin meaning "away" or "from."'),
( 'absurd', 'Root Word', 'What is the root word of "absurd"?', 'surd', 'ab', 'abs', 'absent', 'The root word of "absurd" is "surd," which comes from Latin meaning "deaf or unintelligible."'),
( 'abuse', 'Root Word', 'What is the root word of "abuse"?', 'use', 'ab', 'buse', 'abus', 'The root word of "abuse" is "use," which comes from Latin meaning "to employ or utilize."'),
( 'academy', 'Root Word', 'What is the root word of "academy"?', 'acad', 'academy', 'ac', 'ademy', 'The root word of "academy" is "acad," which comes from the Greek word "Akademos," the name of a Greek philosopher after whom the academy was named.'),
( 'accelerate', 'Root Word', 'What is the root word of "accelerate"?', 'celer', 'ac', 'rate', 'celerate', 'The root word of "accelerate" is "celer," which comes from Latin meaning "quick or fast."'),
( 'acceptance', 'Root Word', 'What is the root word of "acceptance"?', 'accept', 'accepta', 'ance', 'cept', 'The root word of "acceptance" is "accept," which comes from Latin meaning "to take or receive."'),
( 'accessible', 'Root Word', 'What is the root word of "accessible"?', 'access', 'able', 'acce', 'ible', 'The root word of "accessible" is "access," which comes from Latin meaning "to approach or enter."'),
( 'accomplishment', 'Root Word', 'What is the root word of "accomplishment"?', 'accomplish', 'ment', 'com', 'accom', 'The root word of "accomplishment" is "accomplish," which comes from Latin meaning "to complete or achieve."'),
( 'accordingly', 'Root Word', 'What is the root word of "accordingly"?', 'accord', 'ingly', 'accorda', 'cor', 'The root word of "accordingly" is "accord," which comes from Latin meaning "to agree or be in harmony."'),
( 'accountability', 'Root Word', 'What is the root word of "accountability"?', 'account', 'ability', 'acount', 'able', 'The root word of "accountability" is "account," which comes from Latin meaning "to reckon or consider."'),
( 'accountable', 'Root Word', 'What is the root word of "accountable"?', 'account', 'able', 'count', 'accoun', 'The root word of "accountable" is "account," which comes from Latin meaning "to count or reckon."'),
( 'accumulate', 'Root Word', 'What is the root word of "accumulate"?', 'accumul', 'cumul', 'ate', 'accum', 'The root word of "accumulate" is "cumul," which comes from Latin meaning "heap or pile."'),
( 'accumulation', 'Root Word', 'What is the root word of "accumulation"?', 'accumul', 'pile', 'ation', 'cumul', 'The root word of "accumulation" is "accumul," which comes from Latin meaning "to gather or pile up."'),
( 'accusation', 'Root Word', 'What is the root word of "accusation"?', 'accuse', 'ation', 'accus', 'sation', 'The root word of "accusation" is "accuse," which comes from Latin meaning "to charge or blame."'),
( 'accused', 'Root Word', 'What is the root word of "accused"?', 'accuse', 'ed', 'accus', 'ase', 'The root word of "accused" is "accuse," which comes from Latin meaning "to charge or blame."'),
( 'acid', 'Root Word', 'What is the root word of "acid"?', 'ac', 'cid', 'acidus', 'cide', 'The root word of "acid" is "acidus," which comes from Latin meaning "sour or sharp."'),
( 'acquisition', 'Root Word', 'What is the root word of "acquisition"?', 'acquire', 'acqu', 'ition', 'acquis', 'The root word of "acquisition" is "acquire," which comes from Latin meaning "to obtain or gain."'),
( 'activation', 'Root Word', 'What is the root word of "activation"?', 'activate', 'action', 'ate', 'acti', 'The root word of "activation" is "activate," which comes from Latin meaning "to make active or bring to life."'),
( 'activist', 'Root Word', 'What is the root word of "activist"?', 'active', 'ist', 'act', 'vis', 'The root word of "activist" is "active," which comes from Latin meaning "to act or take action."'),
( 'acute', 'Root Word', 'What is the root word of "acute"?', 'acu', 'cute', 'acute', 'acut', 'The root word of "acute" is "acu," which comes from Latin meaning "sharp or pointed."');

INSERT INTO `2_Root_Word` ( `word`, `type`, `question`, `correct_answer`, `wrong_answer1`, `wrong_answer2`, `wrong_answer3`, `explanation`) VALUES
( 'adaptation', 'Root Word', 'What is the root word of "adaptation"?', 'adapt', 'adap', 'adapted', 'ation', 'The root word of "adaptation" is "adapt," which comes from Latin meaning "to adjust or modify."'),
( 'adhere', 'Root Word', 'What is the root word of "adhere"?', 'her', 'ad', 'here', 'adhere', 'The root word of "adhere" is "her," which comes from Latin meaning "to stick or cling."'),
( 'adjacent', 'Root Word', 'What is the root word of "adjacent"?', 'jacere', 'ad', 'cent', 'jacent', 'The root word of "adjacent" is "jacere," which comes from Latin meaning "to lie or rest."'),
( 'adjustment', 'Root Word', 'What is the root word of "adjustment"?', 'adjust', 'ment', 'ad', 'just', 'The root word of "adjustment" is "adjust," which comes from Latin meaning "to modify or alter."'),
( 'administer', 'Root Word', 'What is the root word of "administer"?', 'minister', 'ad', 'admin', 'ster', 'The root word of "administer" is "minister," which comes from Latin meaning "to serve or manage."'),
( 'administrative', 'Root Word', 'What is the root word of "administrative"?', 'administer', 'admin', 'ate', 'ative', 'The root word of "administrative" is "administer," which comes from Latin meaning "to manage or supervise."'),
( 'administrator', 'Root Word', 'What is the root word of "administrator"?', 'administer', 'admin', 'ate', 'or', 'The root word of "administrator" is "administer," which comes from Latin meaning "to manage or supervise."'),
( 'admission', 'Root Word', 'What is the root word of "admission"?', 'admit', 'mission', 'ad', 'miss', 'The root word of "admission" is "admit," which comes from Latin meaning "to allow or let in."'),
( 'adolescent', 'Root Word', 'What is the root word of "adolescent"?', 'adolescere', 'adoles', 'sent', 'teen', 'The root word of "adolescent" is "adolescere," which comes from Latin meaning "to grow or mature."'),
( 'adoption', 'Root Word', 'What is the root word of "adoption"?', 'adopt', 'adop', 'tion', 'opt', 'The root word of "adoption" is "adopt," which comes from Latin meaning "to take as one\'s own."'),
( 'adverse', 'Root Word', 'What is the root word of "adverse"?', 'vers', 'ad', 'versus', 'verse', 'The root word of "adverse" is "vers," which comes from Latin meaning "to turn or change."'),
( 'advocate', 'Root Word', 'What is the root word of "advocate"?', 'vocare', 'ad', 'vocate', 'av', 'The root word of "advocate" is "vocare," which comes from Latin meaning "to call or summon."'),
( 'aesthetic', 'Root Word', 'What is the root word of "aesthetic"?', 'aesthet', 'etic', 'es', 'ae', 'The root word of "aesthetic" is "aesthet," which comes from Greek meaning "to perceive or sense."'),
( 'affection', 'Root Word', 'What is the root word of "affection"?', 'affect', 'tion', 'af', 'fect', 'The root word of "affection" is "affect," which comes from Latin meaning "to influence or move."'),
( 'aftermath', 'Root Word', 'What is the root word of "aftermath"?', 'math', 'af', 'after', 'mat', 'The root word of "aftermath" is "math," which comes from Old English meaning "consequence or result."'),
( 'aggression', 'Root Word', 'What is the root word of "aggression"?', 'gress', 'aggress', 'ag', 'ess', 'The root word of "aggression" is "gress," which comes from Latin meaning "to step or go."'),
( 'agricultural', 'Root Word', 'What is the root word of "agricultural"?', 'agri', 'culture', 'agriculture', 'cultural', 'The root word of "agricultural" is "agri," which comes from Latin meaning "field or soil."'),
( 'aide', 'Root Word', 'What is the root word of "aide"?', 'aid', 'de', 'a', 'e', 'The root word of "aide" is "aid," which comes from Latin meaning "help or assistance."'),
( 'alert', 'Root Word', 'What is the root word of "alert"?', 'al', 'ert', 'all', 'er', 'The root word of "alert" is "al," which comes from Latin meaning "to warn or bring attention."'),
( 'align', 'Root Word', 'What is the root word of "align"?', 'line', 'align', 'al', 'ign', 'The root word of "align" is "line," which comes from Latin meaning "a straight or extended mark."');

INSERT INTO `2_Root_Word` ( `word`, `type`, `question`, `correct_answer`, `wrong_answer1`, `wrong_answer2`, `wrong_answer3`, `explanation`) VALUES
( 'alignment', 'Root Word', 'What is the root word of "alignment"?', 'align', 'ment', 'line', 'al', 'The root word of "alignment" is "align," which comes from Latin meaning "to place in a straight line or proper order."'),
( 'alike', 'Root Word', 'What is the root word of "alike"?', 'like', 'al', 'ilk', 'likea', 'The root word of "alike" is "like," which comes from Old English meaning "similar or comparable."'),
( 'allegation', 'Root Word', 'What is the root word of "allegation"?', 'allege', 'ation', 'al', 'leg', 'The root word of "allegation" is "allege," which comes from Latin meaning "to assert or claim."'),
( 'allege', 'Root Word', 'What is the root word of "allege"?', 'leg', 'al', 'alge', 'legge', 'The root word of "allege" is "leg," which comes from Latin meaning "to read or gather," often used in a legal context.'),
( 'allegedly', 'Root Word', 'What is the root word of "allegedly"?', 'allege', 'ly', 'led', 'ged', 'The root word of "allegedly" is "allege," which comes from Latin meaning "to claim or state as a fact without proof."'),
( 'alliance', 'Root Word', 'What is the root word of "alliance"?', 'ally', 'ance', 'all', 'lian', 'The root word of "alliance" is "ally," which comes from Old French meaning "to unite or join."'),
( 'allocate', 'Root Word', 'What is the root word of "allocate"?', 'locate', 'al', 'ate', 'alloc', 'The root word of "allocate" is "locate," which comes from Latin meaning "to place or position."'),
( 'allocation', 'Root Word', 'What is the root word of "allocation"?', 'locate', 'ation', 'al', 'alloc', 'The root word of "allocation" is "locate," which comes from Latin meaning "to place or assign."'),
( 'allowance', 'Root Word', 'What is the root word of "allowance"?', 'allow', 'ance', 'al', 'wance', 'The root word of "allowance" is "allow," which comes from Old French meaning "to permit or grant."'),
( 'ally', 'Root Word', 'What is the root word of "ally"?', 'all', 'al', 'ly', 'allia', 'The root word of "ally" is "all," which comes from Old French meaning "to unite or join."'),
( 'aluminium', 'Root Word', 'What is the root word of "aluminium"?', 'alum', 'inum', 'ium', 'al', 'The root word of "aluminium" is "alum," which comes from Latin meaning "potassium alum," a compound used in the production of aluminium.'),
( 'amateur', 'Root Word', 'What is the root word of "amateur"?', 'amare', 'am', 'a', 'tur', 'The root word of "amateur" is "amare," which comes from Latin meaning "to love or enjoy."'),
( 'ambassador', 'Root Word', 'What is the root word of "ambassador"?', 'bassador', 'ambas', 'ambass', 'amb', 'The root word of "ambassador" is "bassador," which comes from the Latin "ambactus," meaning "servant or emissary."'),
( 'amend', 'Root Word', 'What is the root word of "amend"?', 'mend', 'a', 'me', 'am', 'The root word of "amend" is "mend," which comes from Old French meaning "to correct or fix."'),
( 'amendment', 'Root Word', 'What is the root word of "amendment"?', 'mend', 'ment', 'amend', 'amend', 'The root word of "amendment" is "mend," which comes from Old French meaning "to improve or change."'),
( 'amid', 'Root Word', 'What is the root word of "amid"?', 'mid', 'a', 'id', 'am', 'The root word of "amid" is "mid," which comes from Old English meaning "in the middle of."'),
( 'analogy', 'Root Word', 'What is the root word of "analogy"?', 'logos', 'ana', 'alog', 'logy', 'The root word of "analogy" is "logos," which comes from Greek meaning "word, speech, or reason."'),
( 'anchor', 'Root Word', 'What is the root word of "anchor"?', 'anch', 'or', 'ch', 'an', 'The root word of "anchor" is "anch," which comes from Greek meaning "to fasten or secure."'),
( 'angel', 'Root Word', 'What is the root word of "angel"?', 'angelos', 'angel', 'ang', 'el', 'The root word of "angel" is "angelos," which comes from Greek meaning "messenger."'),
( 'anonymous', 'Root Word', 'What is the root word of "anonymous"?', 'onym', 'an', 'nym', 'onymous', 'The root word of "anonymous" is "onym," which comes from Greek meaning "name."');

INSERT INTO `2_Root_Word` ( `word`, `type`, `question`, `correct_answer`, `wrong_answer1`, `wrong_answer2`, `wrong_answer3`, `explanation`) VALUES
( 'apparatus', 'Root Word', 'What is the root word of "apparatus"?', 'appar', 'us', 'a', 'rat', 'The root word of "apparatus" is "appar," which comes from Latin meaning "to prepare or make ready."'),
( 'apparel', 'Root Word', 'What is the root word of "apparel"?', 'par', 'app', 'era', 'ral', 'The root word of "apparel" is "par," which comes from Latin meaning "to arrange or prepare."'),
( 'appealing', 'Root Word', 'What is the root word of "appealing"?', 'appeal', 'app', 'peal', 'aling', 'The root word of "appealing" is "appeal," which comes from Latin meaning "to request or call for."'),
( 'appetite', 'Root Word', 'What is the root word of "appetite"?', 'appet', 'ite', 'pet', 'e', 'The root word of "appetite" is "appet," which comes from Latin meaning "desire or longing."'),
( 'applaud', 'Root Word', 'What is the root word of "applaud"?', 'plaud', 'ap', 'pla', 'aud', 'The root word of "applaud" is "plaud," which comes from Latin meaning "to strike or clap."'),
( 'applicable', 'Root Word', 'What is the root word of "applicable"?', 'apply', 'able', 'app', 'applyc', 'The root word of "applicable" is "apply," which comes from Latin meaning "to put to use or bring into action."'),
( 'appoint', 'Root Word', 'What is the root word of "appoint"?', 'point', 'app', 'int', 'oint', 'The root word of "appoint" is "point," which comes from Latin meaning "to indicate or direct."'),
( 'appreciation', 'Root Word', 'What is the root word of "appreciation"?', 'appreciate', 'ation', 'preci', 'ate', 'The root word of "appreciation" is "appreciate," which comes from Latin meaning "to value or recognize the worth of."'),
( 'arbitrary', 'Root Word', 'What is the root word of "arbitrary"?', 'arbitra', 'arbit', 'tary', 'ar', 'The root word of "arbitrary" is "arbitra," which comes from Latin meaning "to judge or decide."'),
( 'architectural', 'Root Word', 'What is the root word of "architectural"?', 'architect', 'ural', 'tect', 'archi', 'The root word of "architectural" is "architect," which comes from Greek meaning "master builder."'),
( 'archive', 'Root Word', 'What is the root word of "archive"?', 'arch', 'iv', 'archi', 'chive', 'The root word of "archive" is "arch," which comes from Greek meaning "chief" or "principal."'),
( 'arena', 'Root Word', 'What is the root word of "arena"?', 'aren', 'arena', 'ar', 'en', 'The root word of "arena" is "aren," which comes from Latin meaning "sand" or "place of combat."'),
( 'arm (v)', 'Root Word', 'What is the root word of "arm"?', 'arm', 'ar', 'am', 'armin', 'The root word of "arm" is "arm," which comes from Latin meaning "to equip with weapons."'),
( 'array', 'Root Word', 'What is the root word of "array"?', 'ray', 'arr', 'array', 'aray', 'The root word of "array" is "ray," which comes from Old French meaning "to arrange or set out."'),
( 'articulate', 'Root Word', 'What is the root word of "articulate"?', 'artic', 'ate', 'ulate', 'art', 'The root word of "articulate" is "artic," which comes from Latin meaning "to separate or divide."'),
( 'ash', 'Root Word', 'What is the root word of "ash"?', 'ash', 'a', 'sh', 'ashum', 'The root word of "ash" is "ash," which comes from Old English meaning "the residue left after burning."'),
( 'aspiration', 'Root Word', 'What is the root word of "aspiration"?', 'aspire', 'ation', 'spire', 'ate', 'The root word of "aspiration" is "aspire," which comes from Latin meaning "to seek or aim for."'),
( 'aspire', 'Root Word', 'What is the root word of "aspire"?', 'spir', 'asp', 'ire', 'aspi', 'The root word of "aspire" is "spir," which comes from Latin meaning "to breathe or blow."'),
( 'assassination', 'Root Word', 'What is the root word of "assassination"?', 'assass', 'ation', 'inate', 'sine', 'The root word of "assassination" is "assass," which comes from Arabic meaning "to murder or kill."'),
( 'assault', 'Root Word', 'What is the root word of "assault"?', 'salt', 'as', 'sult', 'sal', 'The root word of "assault" is "salt," which comes from Latin meaning "to leap or jump."'),
( 'assemble', 'Root Word', 'What is the root word of "assemble"?', 'sembl', 'as', 'sem', 'semble', 'The root word of "assemble" is "sembl," which comes from Latin meaning "to gather or bring together."');

INSERT INTO `2_Root_Word` ( `word`, `type`, `question`, `correct_answer`, `wrong_answer1`, `wrong_answer2`, `wrong_answer3`, `explanation`) VALUES
( 'assembly', 'Root Word', 'What is the root word of "assembly"?', 'assemble', 'ment', 'sem', 'a', 'The root word of "assembly" is "assemble," which comes from Latin meaning "to gather or bring together."'),
( 'assert', 'Root Word', 'What is the root word of "assert"?', 'sert', 'assert', 'ser', 'ert', 'The root word of "assert" is "sert," which comes from Latin meaning "to join or connect."'),
( 'assertion', 'Root Word', 'What is the root word of "assertion"?', 'assert', 'tion', 'sert', 'serted', 'The root word of "assertion" is "assert," which comes from Latin meaning "to state or declare positively."'),
( 'assurance', 'Root Word', 'What is the root word of "assurance"?', 'assure', 'ance', 'sur', 'surance', 'The root word of "assurance" is "assure," which comes from Old French meaning "to make certain or guarantee."'),
( 'asylum', 'Root Word', 'What is the root word of "asylum"?', 'syl', 'sy', 'sylum', 'a', 'The root word of "asylum" is "syl," which comes from Greek meaning "to flee or escape."'),
( 'atrocity', 'Root Word', 'What is the root word of "atrocity"?', 'atroc', 'ity', 'atrocious', 'cious', 'The root word of "atrocity" is "atroc," which comes from Latin meaning "cruel or brutal."'),
( 'attain', 'Root Word', 'What is the root word of "attain"?', 'tain', 'at', 'ain', 'tainable', 'The root word of "attain" is "tain," which comes from Latin meaning "to hold or keep."'),
( 'attendance', 'Root Word', 'What is the root word of "attendance"?', 'attend', 'ance', 'tend', 'attendancy', 'The root word of "attendance" is "attend," which comes from Latin meaning "to be present or take care of."'),
( 'attribute', 'Root Word', 'What is the root word of "attribute"?', 'tribute', 'tribu', 'trib', 'attri', 'The root word of "attribute" is "tribute," which comes from Latin meaning "to give or assign."'),
( 'auction', 'Root Word', 'What is the root word of "auction"?', 'auct', 'action', 'auctionary', 'uct', 'The root word of "auction" is "auct," which comes from Latin meaning "to increase or raise."'),
( 'audit', 'Root Word', 'What is the root word of "audit"?', 'aud', 'it', 'audition', 'udi', 'The root word of "audit" is "aud," which comes from Latin meaning "to hear or listen."'),
( 'authentic', 'Root Word', 'What is the root word of "authentic"?', 'authent', 'ic', 'authen', 'enti', 'The root word of "authentic" is "authent," which comes from Greek meaning "genuine or real."'),
( 'authorise', 'Root Word', 'What is the root word of "authorise"?', 'author', 'ise', 'auth', 'thor', 'The root word of "authorise" is "author," which comes from Greek meaning "creator or originator."'),
( 'auto', 'Root Word', 'What is the root word of "auto"?', 'aut', 'auto', 'tu', 'atom', 'The root word of "auto" is "aut," which comes from Greek meaning "self."'),
( 'autonomy', 'Root Word', 'What is the root word of "autonomy"?', 'nomy', 'auto', 'tonom', 'auton', 'The root word of "autonomy" is "auto," which comes from Greek meaning "self" and "nomy," which comes from Greek meaning "law or rule."'),
( 'autumn', 'Root Word', 'What is the root word of "autumn"?', 'aut', 'umn', 'um', 'aut', 'The root word of "autumn" is "aut," which comes from Latin meaning "fall" or "season."'),
( 'availability', 'Root Word', 'What is the root word of "availability"?', 'avail', 'ability', 'able', 'ability', 'The root word of "availability" is "avail," which comes from Latin meaning "to be useful or effective."'),
( 'await', 'Root Word', 'What is the root word of "await"?', 'wait', 'aw', 'waiter', 'ate', 'The root word of "await" is "wait," which comes from Old English meaning "to remain or stay."'),
