INSERT INTO `verbal` 
(`category`, `type`, `sub_type`, `instruction`, `word`, `question`, `correct_answer`, `wrong_answer1`, `wrong_answer2`, `wrong_answer3`, `explanation`) VALUES
('Sentence Usage and Construction', 'Error Identification', 'Grammar',
'Identify the part of the sentence that contains an error.',
NULL,
'Each of the students have submitted their assignments on time.',
'Each of the students have', 'submitted', 'their assignments', 'on time',
'"Each" is singular, so it should be followed by "has" instead of "have".'),

('Sentence Usage and Construction', 'Error Identification', 'Grammar',
'Identify the part of the sentence that contains an error.',
NULL,
'Neither of the options are acceptable to the committee.',
'are acceptable', 'Neither of the options', 'to the committee', 'acceptable',
'"Neither" is singular, so the correct verb is "is" instead of "are".'),

('Sentence Usage and Construction', 'Error Identification', 'Grammar',
'Identify the part of the sentence that contains an error.',
NULL,
'The teacher, along with her students, are attending the seminar.',
'are attending', 'The teacher', 'along with her students', 'the seminar',
'The subject is "The teacher" (singular), so the correct verb is "is attending".'),

('Sentence Usage and Construction', 'Error Identification', 'Tense',
'Identify the part of the sentence that contains an error.',
NULL,
'By next week, she will completed the training program.',
'will completed', 'By next week', 'she', 'the training program',
'The correct future perfect tense is "will have completed".'),

('Sentence Usage and Construction', 'Error Identification', 'Pronoun Agreement',
'Identify the part of the sentence that contains an error.',
NULL,
'Everyone should bring their own notebook to the meeting.',
'their own notebook', 'Everyone', 'should bring', 'to the meeting',
'In formal grammar, "Everyone" is singular, so it should be "his or her own notebook".'),

('Sentence Usage and Construction', 'Error Identification', 'Preposition Usage',
'Identify the part of the sentence that contains an error.',
NULL,
'We will discuss about the proposal in the next meeting.',
'discuss about', 'We will', 'the proposal', 'in the next meeting',
'"Discuss" already implies "about", so the preposition is unnecessary.'),

('Sentence Usage and Construction', 'Error Identification', 'Word Form',
'Identify the part of the sentence that contains an error.',
NULL,
'She sings good, even when she is tired.',
'sings good', 'She', 'even when', 'she is tired',
'An adverb should be used here; the correct form is "sings well".'),

('Sentence Usage and Construction', 'Error Identification', 'Parallelism',
'Identify the part of the sentence that contains an error.',
NULL,
'The project requires planning, coordination, and to execute efficiently.',
'to execute', 'The project requires', 'planning', 'coordination',
'Parallel structure requires all items in the list to be the same form: "execution" instead of "to execute".'),

('Sentence Usage and Construction', 'Error Identification', 'Modifier Placement',
'Identify the part of the sentence that contains an error.',
NULL,
'Walking down the street, the flowers were in full bloom.',
'Walking down the street', 'the flowers', 'were in full bloom', 'street, the flowers',
'The modifier is misplaced; it seems the flowers were walking. It should modify the person walking.'),

('Sentence Usage and Construction', 'Error Identification', 'Article Usage',
'Identify the part of the sentence that contains an error.',
NULL,
'She is an honest and intelligent woman.',
'No error', 'She is', 'an honest', 'and intelligent woman',
'This sentence has no grammatical error.');
