INSERT INTO `verbal` 
(`category`, `type`, `sub_type`, `instruction`, `word`, `question`, `correct_answer`, `wrong_answer1`, `wrong_answer2`, `wrong_answer3`, `explanation`) VALUES
-- 1
('Sentence Usage and Construction', 'Sentence Transformation', 'Active to Passive',
'Transform the given sentence without changing its meaning.',
'write',
'She writes the report every week.',
'The report is written by her every week.',
'The report was written by her every week.',
'The report is writing by her every week.',
'The report has been written by her every week.',
'Present simple active changes to present simple passive: "writes" → "is written".'),
-- 2
('Sentence Usage and Construction', 'Sentence Transformation', 'Passive to Active',
'Transform the given sentence without changing its meaning.',
'complete',
'The project was completed by the team on time.',
'The team completed the project on time.',
'The team completes the project on time.',
'The team is completing the project on time.',
'The project completes the team on time.',
'Past simple passive changes to past simple active: "was completed" → "completed".'),
-- 3
('Sentence Usage and Construction', 'Sentence Transformation', 'Direct to Indirect Speech',
'Transform the given direct speech to indirect speech.',
'say',
'He said, "I am busy now."',
'He said that he was busy then.',
'He said that he is busy now.',
'He said he was busy now.',
'He said he had been busy now.',
'Time shift: present "am" → past "was", "now" → "then".'),
-- 4
('Sentence Usage and Construction', 'Sentence Transformation', 'Indirect to Direct Speech',
'Transform the given indirect speech to direct speech.',
'tell',
'She told me that she would call later.',
'She said, "I will call later."',
'She says, "I will call later."',
'She said, "I would call later."',
'She says, "I would call later."',
'"would" in reported speech returns to "will" in direct speech when context allows.'),
-- 5
('Sentence Usage and Construction', 'Sentence Transformation', 'Affirmative to Negative',
'Transform the sentence to its negative form without changing the meaning.',
'like',
'I like reading books.',
'I do not like reading books.',
'I am not like reading books.',
'I have not liked reading books.',
'I will not like reading books.',
'Present simple affirmative → present simple negative with "do not".'),
-- 6
('Sentence Usage and Construction', 'Sentence Transformation', 'Negative to Affirmative',
'Transform the sentence to its affirmative form without changing the meaning.',
'want',
'She does not want to join the meeting.',
'She refuses to join the meeting.',
'She wants not to join the meeting.',
'She did not want to join the meeting.',
'She will not join the meeting.',
'Using "refuses" expresses the same meaning in an affirmative structure.'),
-- 7
('Sentence Usage and Construction', 'Sentence Transformation', 'Exclamatory to Assertive',
'Transform the sentence into an assertive sentence without changing its meaning.',
'beautiful',
'What a beautiful day it is!',
'It is a very beautiful day.',
'It was a beautiful day.',
'It has been a beautiful day.',
'It will be a beautiful day.',
'Exclamatory sentences can be transformed into assertive ones by rephrasing.'),
-- 8
('Sentence Usage and Construction', 'Sentence Transformation', 'Assertive to Exclamatory',
'Transform the sentence into an exclamatory sentence without changing its meaning.',
'bright',
'It is a bright morning.',
'What a bright morning it is!',
'How bright the morning is!',
'What bright morning is!',
'How is a bright morning!',
'Assertive → exclamatory using "What a" or "How".'),
-- 9
('Sentence Usage and Construction', 'Sentence Transformation', 'Positive to Comparative',
'Transform the sentence into a comparative degree sentence without changing the meaning.',
'tall',
'She is the tallest girl in the class.',
'She is taller than any other girl in the class.',
'She is taller than every girl in the class.',
'She is taller than all girls in the class.',
'She is tall than any other girl in the class.',
'Superlative "tallest" changes to comparative "taller than any other".'),
-- 10
('Sentence Usage and Construction', 'Sentence Transformation', 'Comparative to Superlative',
'Transform the sentence into a superlative degree sentence without changing the meaning.',
'fast',
'He is faster than all the other runners.',
'He is the fastest runner.',
'He is the most fast runner.',
'He is fastly than all runners.',
'He is fastest of all runners.',
'Comparative → superlative: "faster than all others" → "the fastest".'),
-- 11
('Sentence Usage and Construction', 'Sentence Transformation', 'Simple to Complex',
'Transform the sentence from simple to complex without changing its meaning.',
'illness',
'Due to his illness, he stayed home.',
'He stayed home because he was ill.',
'He stayed home and he was ill.',
'He stayed home for he was ill.',
'He stayed home while he was ill.',
'The prepositional phrase "due to" becomes a dependent clause with "because".'),
-- 12
('Sentence Usage and Construction', 'Sentence Transformation', 'Complex to Simple',
'Transform the sentence from complex to simple without changing its meaning.',
'rain',
'He stayed home because it was raining.',
'Due to the rain, he stayed home.',
'Because of rain, he stayed home.',
'He stayed home for rain.',
'He stayed home while rain.',
'Complex clause → simple phrase using "due to".'),
-- 13
('Sentence Usage and Construction', 'Sentence Transformation', 'Active to Passive',
'Transform the given sentence without changing its meaning.',
'clean',
'They clean the office every morning.',
'The office is cleaned every morning by them.',
'The office was cleaned every morning by them.',
'The office cleaning every morning by them.',
'The office will be cleaned every morning by them.',
'Present simple active changes to present simple passive: "clean" → "is cleaned".'),
-- 14
('Sentence Usage and Construction', 'Sentence Transformation', 'Passive to Active',
'Transform the given sentence without changing its meaning.',
'invite',
'The guests were invited by the host.',
'The host invited the guests.',
'The host invites the guests.',
'The host inviting the guests.',
'The host was inviting the guests.',
'Past simple passive changes to past simple active.'),
-- 15
('Sentence Usage and Construction', 'Sentence Transformation', 'Direct to Indirect Speech',
'Transform the given direct speech to indirect speech.',
'ask',
'She asked, "Where are you going?"',
'She asked where I was going.',
'She asked where I am going.',
'She asked where was I going.',
'She asked where am I going.',
'Present continuous in direct → past continuous in reported speech.'),
-- 16
('Sentence Usage and Construction', 'Sentence Transformation', 'Indirect to Direct Speech',
'Transform the given indirect speech to direct speech.',
'mention',
'He mentioned that he had finished his work.',
'He said, "I have finished my work."',
'He says, "I had finished my work."',
'He said, "I had finished my work."',
'He says, "I have been finishing my work."',
'Past perfect in reported speech → present perfect in direct speech when time reference allows.'),
-- 17
('Sentence Usage and Construction', 'Sentence Transformation', 'Negative to Affirmative',
'Transform the sentence to its affirmative form without changing the meaning.',
'fail',
'He did not pass the exam.',
'He failed the exam.',
'He was failing the exam.',
'He fails the exam.',
'He had failed the exam.',
'"Did not pass" is directly replaced with "failed".'),
-- 18
('Sentence Usage and Construction', 'Sentence Transformation', 'Affirmative to Negative',
'Transform the sentence to its negative form without changing the meaning.',
'understand',
'I understand the instructions.',
'I do not understand the instructions.',
'I am not understand the instructions.',
'I was not understanding the instructions.',
'I cannot understand the instructions.',
'Present simple affirmative → present simple negative with "do not".'),
-- 19
('Sentence Usage and Construction', 'Sentence Transformation', 'Assertive to Exclamatory',
'Transform the sentence into an exclamatory sentence without changing its meaning.',
'happy',
'She is very happy today.',
'How happy she is today!',
'What a happy she is today!',
'She is happy today!',
'How is happy she today!',
'Use "How" for exclamatory emphasis.'),
-- 20
('Sentence Usage and Construction', 'Sentence Transformation', 'Exclamatory to Assertive',
'Transform the sentence into an assertive sentence without changing its meaning.',
'surprise',
'What a surprise this gift is!',
'This gift is a great surprise.',
'This gift was a surprise.',
'This gift has been a surprise.',
'This gift will be a surprise.',
'Exclamatory → assertive by removing emotional structure.');
