INSERT INTO `verbal` 
(`category`, `type`, `sub_type`, `instruction`, `word`, `question`, `correct_answer`, `wrong_answer1`, `wrong_answer2`, `wrong_answer3`, `explanation`) VALUES
('Sentence Usage and Construction', 'Correct Usage in Sentences', 'Word Order Accuracy',
'Rearrange the words to form a grammatically correct sentence.',
'celebration',
'Arrange the words: was / the / yesterday / celebration / grand',
'The celebration was grand yesterday.',
'Grand was the celebration yesterday.',
'Yesterday the grand celebration was.',
'The grand yesterday celebration was.',
'The correct word order follows the subject-verb-complement structure: Subject ("The celebration") + Verb ("was") + Complement ("grand") + Time ("yesterday").'),

('Sentence Usage and Construction', 'Correct Usage in Sentences', 'Word Order Accuracy',
'Rearrange the words to form a grammatically correct sentence.',
'library',
'Arrange the words: books / the / many / library / in / are',
'There are many books in the library.',
'Many books are there in library the.',
'The library in are many books.',
'Library many in books there are.',
'The correct sentence begins with "There are" for existence, followed by the subject "many books" and the location phrase "in the library."'),

('Sentence Usage and Construction', 'Correct Usage in Sentences', 'Word Order Accuracy',
'Rearrange the words to form a grammatically correct sentence.',
'festival',
'Arrange the words: starts / at / tomorrow / 8 a.m. / the / festival',
'The festival starts at 8 a.m. tomorrow.',
'Tomorrow the starts festival at 8 a.m.',
'The starts festival at tomorrow 8 a.m.',
'Festival the tomorrow starts at 8 a.m.',
'The standard word order is Subject ("The festival") + Verb ("starts") + Time/Place ("at 8 a.m. tomorrow").'),

('Sentence Usage and Construction', 'Correct Usage in Sentences', 'Word Order Accuracy',
'Rearrange the words to form a grammatically correct sentence.',
'meeting',
'Arrange the words: cancelled / was / the / due / meeting / storm / the / to',
'The meeting was cancelled due to the storm.',
'The meeting was storm cancelled to due the.',
'Due to the storm was cancelled the meeting.',
'Cancelled was the meeting due storm to the.',
'The phrase "due to" introduces the cause, and it should follow the verb phrase "was cancelled".'),

('Sentence Usage and Construction', 'Correct Usage in Sentences', 'Word Order Accuracy',
'Rearrange the words to form a grammatically correct sentence.',
'science',
'Arrange the words: science / her / loves / brother',
'Her brother loves science.',
'Loves her brother science.',
'Her loves brother science.',
'Science loves her brother.',
'The correct structure is Subject ("Her brother") + Verb ("loves") + Object ("science").'),

('Sentence Usage and Construction', 'Correct Usage in Sentences', 'Word Order Accuracy',
'Rearrange the words to form a grammatically correct sentence.',
'package',
'Arrange the words: delivered / was / package / your / yesterday',
'Your package was delivered yesterday.',
'Was delivered yesterday your package.',
'Your was package delivered yesterday.',
'Yesterday delivered was your package.',
'The correct structure is Subject ("Your package") + Passive Verb ("was delivered") + Time ("yesterday").'),

('Sentence Usage and Construction', 'Correct Usage in Sentences', 'Word Order Accuracy',
'Rearrange the words to form a grammatically correct sentence.',
'train',
'Arrange the words: left / the / station / the / at / 6 a.m.',
'The train left the station at 6 a.m.',
'The train at 6 a.m. left the station.',
'Left the station the train at 6 a.m.',
'At 6 a.m. left the station the train.',
'The standard word order is Subject ("The train") + Verb ("left") + Object ("the station") + Time ("at 6 a.m.").'),

('Sentence Usage and Construction', 'Correct Usage in Sentences', 'Word Order Accuracy',
'Rearrange the words to form a grammatically correct sentence.',
'park',
'Arrange the words: children / playing / the / are / park / in / the',
'The children are playing in the park.',
'Children are playing in park the the.',
'In the park the children playing are.',
'Playing are the children in the park.',
'The correct word order follows Subject ("The children") + Verb ("are playing") + Place ("in the park").'),

('Sentence Usage and Construction', 'Correct Usage in Sentences', 'Word Order Accuracy',
'Rearrange the words to form a grammatically correct sentence.',
'announcement',
'Arrange the words: made / principal / announcement / important / the / an',
'The principal made an important announcement.',
'An important announcement made the principal.',
'The principal announcement made important an.',
'Important made announcement principal the an.',
'The correct structure is Subject ("The principal") + Verb ("made") + Object ("an important announcement").'),

('Sentence Usage and Construction', 'Correct Usage in Sentences', 'Word Order Accuracy',
'Rearrange the words to form a grammatically correct sentence.',
'report',
'Arrange the words: submitted / report / the / was / on / Monday',
'The report was submitted on Monday.',
'Submitted the report was Monday on.',
'On Monday was submitted the report.',
'The was report submitted Monday on.',
'The correct structure is Subject ("The report") + Passive Verb ("was submitted") + Time ("on Monday").');
