INSERT INTO `verbal` (`category`, `type`, `word`, `question`, `correct_answer`, `wrong_answer1`, `wrong_answer2`, `wrong_answer3`, `explanation`) VALUES
('Word Meaning and Usage', 'Word Intensity', 'Anger', 'Which word expresses the STRONGEST degree of anger?', 'Livid', 'Annoyed', 'Irritated', 'Upset', '"Livid" implies uncontrollable rage (strongest), while "annoyed" is mild irritation.'),
('Word Meaning and Usage', 'Word Intensity', 'Urgency', 'In government memos, which term denotes the HIGHEST priority?', 'Imperative', 'Important', 'Necessary', 'Significant', '"Imperative" means absolutely essential (strongest urgency for public service).'),
('Word Meaning and Usage', 'Word Intensity', 'Force', 'Which term describes the MOST SEVERE level of physical force?', 'Brutal', 'Firm', 'Assertive', 'Controlling', '"Brutal" implies extreme/excessive force (beyond professional policing standards).'),
('Word Meaning and Usage', 'Word Intensity', 'Happiness', 'Which word indicates the MOST INTENSE student joy?', 'Ecstatic', 'Pleased', 'Content', 'Cheerful', '"Ecstatic" means overwhelming delight (strongest for positive learning experiences).'),
('Word Meaning and Usage', 'Word Intensity', 'Difficulty', 'Which term means EXTREMELY DIFFICULT in administrative tasks?', 'Arduous', 'Hard', 'Challenging', 'Tough', '"Arduous" implies exhausting effort (strongest for bureaucratic complexity).'),
('Word Meaning and Usage', 'Word Intensity', 'Threat', 'Which word describes the GRAVEST danger to officers?', 'Perilous', 'Risky', 'Unsafe', 'Hazardous', '"Perilous" means life-threatening (strongest for on-duty situations).'),
('Word Meaning and Usage', 'Word Intensity', 'Sadness', 'Which term shows DEEPEST student distress?', 'Despondent', 'Sad', 'Upset', 'Disappointed', '"Despondent" implies hopelessness (strongest emotional impact on learning).'),
('Word Meaning and Usage', 'Word Intensity', 'Size', 'Which word means LARGEST scale in public projects?', 'Colossal', 'Big', 'Large', 'Massive', '"Colossal" suggests extraordinary size (strongest for infrastructure descriptions).'),
('Word Meaning and Usage', 'Word Intensity', 'Corruption', 'Which term implies the MOST SEVERE ethical violation?', 'Nefarious', 'Wrong', 'Improper', 'Unethical', '"Nefarious" describes extreme wickedness (strongest for graft cases under RA 3019).'),
('Word Meaning and Usage', 'Word Intensity', 'Feedback', 'Which word indicates STRONGEST disapproval of student behavior?', 'Castigate', 'Correct', 'Admonish', 'Reprimand', '"Castigate" means severe punishment (strongest corrective action in classrooms).');