INSERT INTO analytical (category, type, question, chart_data, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Data Interpretation', 'bar', 'Which café showed a consistent increase in monthly sales?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Sunset Grill","data":[180,170,160,150,140],"backgroundColor":"#FFA726"},{"label":"Riverside Café","data":[100,120,140,160,180],"backgroundColor":"#42A5F5"}]}', 'Riverside Café', 'Sunset Grill', 'Mountain Pizzeria', 'Valley Diner', 'Riverside Café rises steadily from 100 to 180.'),
('Data Interpretation', 'bar', 'Which pizzeria experienced a steady decline over five months?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Valley Diner","data":[120,130,140,150,160],"backgroundColor":"#66BB6A"},{"label":"Mountain Pizzeria","data":[200,180,160,140,120],"backgroundColor":"#EF5350"}]}', 'Mountain Pizzeria', 'Valley Diner', 'City Bistro', 'Harbor Seafood', 'Mountain Pizzeria falls each month from 200 to 120.'),
('Data Interpretation', 'bar', 'Which bar had alternating high and low foot traffic?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Countryside Inn","data":[250,260,270,280,290],"backgroundColor":"#26A69A"},{"label":"Beachside Bar","data":[300,200,300,200,300],"backgroundColor":"#8D6E63"}]}', 'Beachside Bar', 'Countryside Inn', 'Sunset Grill', 'Forest Tea House', 'Beachside Bar alternates between 300 and 200 each month.'),
('Data Interpretation', 'bar', 'Which tea house peaked in March before declining?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Harbor Seafood","data":[100,110,120,130,140],"backgroundColor":"#FF7043"},{"label":"Forest Tea House","data":[80,90,150,130,110],"backgroundColor":"#AB47BC"}]}', 'Forest Tea House', 'Harbor Seafood', 'Downtown Grill', 'City Bistro', 'Forest Tea House reaches 150 in March, then drops afterward.'),
('Data Interpretation', 'bar', 'Which grill hit its lowest point in April?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"City Bistro","data":[150,155,160,165,170],"backgroundColor":"#42A5F5"},{"label":"Downtown Grill","data":[200,180,170,140,160],"backgroundColor":"#EF5350"}]}', 'Downtown Grill', 'City Bistro', 'Riverside Café', 'Valley Diner', 'Downtown Grill dips to 140 in April, lowest of the series.'),
('Data Interpretation', 'bar', 'Which café held steady in February and March?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Garden Restaurant","data":[110,115,120,125,130],"backgroundColor":"#8D6E63"},{"label":"Metro Café","data":[100,120,120,130,140],"backgroundColor":"#26A69A"}]}', 'Metro Café', 'Garden Restaurant', 'Harbor Seafood', 'Beachside Bar', 'Metro Café remains at 120 in Feb–Mar before rising.'),
('Data Interpretation', 'bar', 'Which bistro overtook its rival in May?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Suburban Eatery","data":[120,125,130,135,140],"backgroundColor":"#66BB6A"},{"label":"Urban Bistro","data":[100,110,120,130,150],"backgroundColor":"#AB47BC"}]}', 'Urban Bistro', 'Suburban Eatery', 'Metro Café', 'Garden Restaurant', 'Urban Bistro reaches 150 in May, surpassing Suburban Eatery’s 140.'),
('Data Interpretation', 'bar', 'Which café recorded the same sales in January and May?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Coastal Bakery","data":[95,105,115,125,135],"backgroundColor":"#EF5350"},{"label":"Prairie Café","data":[90,100,110,120,90],"backgroundColor":"#FF7043"}]}', 'Prairie Café', 'Coastal Bakery', 'Sunset Grill', 'Riverside Café', 'Prairie Café is 90 in both Jan and May.'),
('Data Interpretation', 'bar', 'Which lounge posted the highest single‑month value?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Grove Lounge","data":[130,140,150,180,170],"backgroundColor":"#FFA726"},{"label":"Skyline Lounge","data":[140,150,160,170,180],"backgroundColor":"#42A5F5"}]}', 'Skyline Lounge', 'Grove Lounge', 'Suburban Eatery', 'Beachside Bar', 'Skyline Lounge peaks at 180 in May, the highest value.'),
('Data Interpretation', 'bar', 'Which market had the lowest sales in February?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Hilltop Café","data":[110,115,120,125,130],"backgroundColor":"#26A69A"},{"label":"Meadow Market","data":[100,90,110,120,130],"backgroundColor":"#8D6E63"}]}', 'Meadow Market', 'Hilltop Café', 'Prairie Café', 'Urban Bistro', 'Meadow Market drops to 90 in February, lower than Hilltop.'),
('Data Interpretation', 'bar', 'Which lounge had equal values in March?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Garden Restaurant","data":[130,135,140,145,150],"backgroundColor":"#AB47BC"},{"label":"Lakeside Lounge","data":[120,130,140,140,150],"backgroundColor":"#FF7043"}]}', 'Lakeside Lounge', 'Garden Restaurant', 'Suburban Eatery', 'City Bistro', 'Lakeside Lounge is 140 in March, matching Garden Restaurant.'),
('Data Interpretation', 'bar', 'Which market spiked mid‑period in February?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"City Bistro","data":[90,95,100,105,110],"backgroundColor":"#42A5F5"},{"label":"County Market","data":[100,150,120,130,140],"backgroundColor":"#EF5350"}]}', 'County Market', 'City Bistro', 'Harbor Seafood', 'Beachside Bar', 'County Market jumps to 150 in February then returns lower.'),
('Data Interpretation', 'bar', 'Which café showed minimal variance?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Sunset Grill","data":[100,110,120,130,140],"backgroundColor":"#FFA726"},{"label":"Hilltop Café","data":[100,102,101,103,102],"backgroundColor":"#26A69A"}]}', 'Hilltop Café', 'Sunset Grill', 'Meadow Market', 'Prairie Café', 'Hilltop Café fluctuates within a narrow range around 102.'),
('Data Interpretation', 'bar', 'Which bakery jumped sharply in May?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Meadow Market","data":[75,80,85,90,95],"backgroundColor":"#8D6E63"},{"label":"Coastal Bakery","data":[80,80,80,80,160],"backgroundColor":"#FF7043"}]}', 'Coastal Bakery', 'Meadow Market', 'County Market', 'Lakeside Lounge', 'Coastal Bakery holds at 80 then jumps to 160 in May.'),
('Data Interpretation', 'bar', 'Which café had an early spike in February?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Harbor Seafood","data":[180,170,160,150,140],"backgroundColor":"#FF7043"},{"label":"Bayfront Café","data":[150,200,150,150,150],"backgroundColor":"#66BB6A"}]}', 'Bayfront Café', 'Harbor Seafood', 'City Bistro', 'Garden Restaurant', 'Bayfront Café peaks at 200 in February then levels off.'),
('Data Interpretation', 'bar', 'Which inn crossed above its rival in March?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"City Bistro","data":[100,100,100,100,100],"backgroundColor":"#EF5350"},{"label":"Countryside Inn","data":[90,95,110,115,120],"backgroundColor":"#AB47BC"}]}', 'Countryside Inn', 'City Bistro', 'Metro Café', 'Garden Restaurant', 'Countryside Inn rises past City Bistro’s constant 100 in March.'),
('Data Interpretation', 'bar', 'Which bistro remained constant before declining?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Downtown Grill","data":[130,125,120,115,110],"backgroundColor":"#EF5350"},{"label":"Urban Bistro","data":[120,120,120,110,100],"backgroundColor":"#42A5F5"}]}', 'Urban Bistro', 'Downtown Grill', 'Sunset Grill', 'Riverside Café', 'Urban Bistro stays at 120 then drops to 100.'),
('Data Interpretation', 'bar', 'Which pizzeria declined then held steady?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Lakeside Lounge","data":[140,145,150,155,160],"backgroundColor":"#26A69A"},{"label":"Mountain Pizzeria","data":[150,140,130,130,130],"backgroundColor":"#8D6E63"}]}', 'Mountain Pizzeria', 'Lakeside Lounge', 'Prairie Café', 'Forest Tea House', 'Mountain Pizzeria falls to 130 then remains flat.'),
('Data Interpretation', 'bar', 'Which café’s trend is the reverse of its competitor?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Suburban Eatery","data":[100,110,120,130,140],"backgroundColor":"#42A5F5"},{"label":"Oakwood Café","data":[140,130,120,110,100],"backgroundColor":"#FFA726"}]}', 'Oakwood Café', 'Suburban Eatery', 'City Bistro', 'Harbor Seafood', 'Oakwood Café declines inversely as Suburban Eatery rises.'),
('Data Interpretation', 'bar', 'Which restaurant spiked then fell symmetrically?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Skyline Lounge","data":[90,95,100,105,110],"backgroundColor":"#AB47BC"},{"label":"Garden Restaurant","data":[100,105,110,105,100],"backgroundColor":"#EF5350"}]}', 'Garden Restaurant', 'Skyline Lounge', 'Coastal Bakery', 'Riverside Café', 'Garden Restaurant peaks at 110 in March then returns to 100.'),
('Data Interpretation', 'bar', 'Which deli saw a sharp rise in April?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Downtown Deli","data":[110,115,120,160,165],"backgroundColor":"#42A5F5"},{"label":"Uptown Deli","data":[100,105,110,115,120],"backgroundColor":"#EF5350"}]}', 'Downtown Deli', 'Uptown Deli', 'Bayfront Café', 'Mountain Pizzeria', 'Downtown Deli jumps from 120 in March to 160 in April.'),
('Data Interpretation', 'bar', 'Which bistro dipped then recovered by May?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Harbor Bistro","data":[140,135,130,125,145],"backgroundColor":"#66BB6A"},{"label":"Garden Bistro","data":[130,132,134,136,138],"backgroundColor":"#AB47BC"}]}', 'Harbor Bistro', 'Garden Bistro', 'City Bistro', 'Forest Tea House', 'Harbor Bistro falls to 125 in April then rises to 145 in May.'),
('Data Interpretation', 'bar', 'Which eatery held flat for three months?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Prairie Eatery","data":[100,100,100,110,120],"backgroundColor":"#26A69A"},{"label":"Coastal Café","data":[90,95,100,105,110],"backgroundColor":"#FFA726"}]}', 'Prairie Eatery', 'Coastal Café', 'Sunset Grill', 'Riverside Café', 'Prairie Eatery remains at 100 in Jan–Mar before climbing.'),
('Data Interpretation', 'bar', 'Which café overtook its competitor in February?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Valley Café","data":[120,110,115,120,125],"backgroundColor":"#FF7043"},{"label":"Hilltop Café","data":[115,120,118,122,130],"backgroundColor":"#8D6E63"}]}', 'Hilltop Café', 'Valley Café', 'Garden Restaurant', 'Urban Bistro', 'Hilltop Café rises above Valley Café in February (120 vs 110).'),
('Data Interpretation', 'bar', 'Which lounge showed consistent growth throughout?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Skyline Lounge","data":[150,155,160,165,170],"backgroundColor":"#AB47BC"},{"label":"Grove Lounge","data":[140,145,150,155,160],"backgroundColor":"#42A5F5"}]}', 'Skyline Lounge', 'Grove Lounge', 'Countryside Inn', 'Beachside Bar', 'Skyline Lounge increases each month from 150 to 170.'),
('Data Interpretation', 'bar', 'Which café saw a plateau in April?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Metro Café","data":[120,130,140,140,150],"backgroundColor":"#26A69A"},{"label":"Suburban Eatery","data":[110,120,130,140,150],"backgroundColor":"#FFA726"}]}', 'Metro Café', 'Suburban Eatery', 'Bayfront Café', 'Prairie Eatery', 'Metro Café remains at 140 in April before rising again.'),
('Data Interpretation', 'bar', 'Which inn dropped sharply in March?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Countryside Inn","data":[140,135,100,110,120],"backgroundColor":"#AB47BC"},{"label":"City Bistro","data":[130,132,134,136,138],"backgroundColor":"#42A5F5"}]}', 'Countryside Inn', 'City Bistro', 'Forest Tea House', 'Oakwood Café', 'Countryside Inn falls from 135 in February to 100 in March.'),
('Data Interpretation', 'bar', 'Which grill rose, fell, then rose again?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Downtown Grill","data":[150,160,140,150,160],"backgroundColor":"#EF5350"},{"label":"Garden Restaurant","data":[145,155,150,155,165],"backgroundColor":"#FF7043"}]}', 'Downtown Grill', 'Garden Restaurant', 'Skyline Lounge', 'Beachside Bar', 'Downtown Grill increases to 160, dips to 140 in March, then rises back.'),
('Data Interpretation', 'bar', 'Which bakery had uniform growth?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Coastal Bakery","data":[80,90,100,110,120],"backgroundColor":"#8D6E63"},{"label":"Prairie Café","data":[85,95,105,115,125],"backgroundColor":"#26A69A"}]}', 'Coastal Bakery', 'Prairie Café', 'Meadow Market', 'Hilltop Café', 'Coastal Bakery grows by 10 each month consistently.'),
('Data Interpretation', 'bar', 'Which market peaked twice?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"County Market","data":[100,150,120,150,130],"backgroundColor":"#EF5350"},{"label":"Urban Bistro","data":[110,120,130,140,150],"backgroundColor":"#AB47BC"}]}', 'County Market', 'Urban Bistro', 'Suburban Eatery', 'Valley Diner', 'County Market spikes to 150 in Feb and again in April.');


INSERT INTO analytical (category, type, question, chart_data, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Data Interpretation', 'bar', 'Which café saw sales dip in May after rising?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Harbor Seafood","data":[110,120,130,140,135],"backgroundColor":"#FF7043"},{"label":"Garden Restaurant","data":[100,110,120,130,140],"backgroundColor":"#AB47BC"}]}', 'Harbor Seafood', 'Garden Restaurant', 'City Bistro', 'Skyline Lounge', 'Harbor Seafood climbs to 140 in April then dips to 135 in May.'),
('Data Interpretation', 'bar', 'Which lounge had decreasing then increasing traffic?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Lakeside Lounge","data":[200,180,160,170,190],"backgroundColor":"#26A69A"},{"label":"Countryside Inn","data":[190,200,210,220,230],"backgroundColor":"#42A5F5"}]}', 'Lakeside Lounge', 'Countryside Inn', 'Suburban Eatery', 'Metro Café', 'Lakeside Lounge falls to 160 in March then recovers by May.'),
('Data Interpretation', 'bar', 'Which eatery had identical values in January and February?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Valley Diner","data":[115,115,120,125,130],"backgroundColor":"#66BB6A"},{"label":"Bayfront Café","data":[110,115,120,125,130],"backgroundColor":"#FFA726"}]}', 'Valley Diner', 'Bayfront Café', 'Forest Tea House', 'Downtown Grill', 'Valley Diner remains at 115 for both Jan and Feb.'),
('Data Interpretation', 'bar', 'Which market showed the sharpest drop between two consecutive months?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"County Market","data":[150,140,110,115,120],"backgroundColor":"#EF5350"},{"label":"Meadow Market","data":[140,135,130,125,120],"backgroundColor":"#8D6E63"}]}', 'County Market', 'Meadow Market', 'Sunset Grill', 'Oakwood Café', 'County Market falls from 140 in Feb to 110 in Mar, the largest two‑month drop.'),
('Data Interpretation', 'bar', 'Which bistro matched its competitor in April?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Urban Bistro","data":[130,135,140,145,150],"backgroundColor":"#AB47BC"},{"label":"Suburban Eatery","data":[125,130,135,145,155],"backgroundColor":"#42A5F5"}]}', 'Urban Bistro', 'Suburban Eatery', 'Metro Café', 'Garden Restaurant', 'Urban Bistro and Suburban Eatery both reach 145 in April.');

INSERT INTO analytical (category, type, question, chart_data, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Data Interpretation', 'bar', 'Which café had identical sales in April and May?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Metro Café","data":[100,110,120,130,130],"backgroundColor":"#26A69A"},{"label":"Valley Café","data":[90,100,110,120,125],"backgroundColor":"#FFA726"}]}', 'Metro Café', 'Valley Café', 'City Bistro', 'Garden Restaurant', 'Metro Café remains at 130 in both April and May.'),
('Data Interpretation', 'bar', 'Which bar declined then recovered by May?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Beachside Bar","data":[150,140,130,140,150],"backgroundColor":"#8D6E63"},{"label":"Countryside Inn","data":[200,190,180,170,160],"backgroundColor":"#42A5F5"}]}', 'Beachside Bar', 'Countryside Inn', 'Skyline Lounge', 'Grove Lounge', 'Beachside Bar falls to 130 in March then climbs back to 150 by May.'),
('Data Interpretation', 'bar', 'Which deli peaked in January and troughed in May?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Uptown Deli","data":[170,165,160,155,150],"backgroundColor":"#EF5350"},{"label":"Downtown Deli","data":[140,145,150,155,160],"backgroundColor":"#42A5F5"}]}', 'Uptown Deli', 'Downtown Deli', 'Bayfront Café', 'Harbor Bistro', 'Uptown Deli starts at 170 in Jan and falls to 150 in May.'),
('Data Interpretation', 'bar', 'Which market had only one two‑month growth streak?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"County Market","data":[100,110,120,115,130],"backgroundColor":"#EF5350"},{"label":"Meadow Market","data":[90,95,100,105,110],"backgroundColor":"#8D6E63"}]}', 'County Market', 'Meadow Market', 'Suburban Eatery', 'Urban Bistro', 'County Market grows Jan–Mar then dips in April before rising.'),
('Data Interpretation', 'bar', 'Which inn plateaued at its peak for three months?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Countryside Inn","data":[120,130,140,140,140],"backgroundColor":"#AB47BC"},{"label":"City Bistro","data":[115,120,125,130,135],"backgroundColor":"#42A5F5"}]}', 'Countryside Inn', 'City Bistro', 'Harbor Bistro', 'Garden Bistro', 'Countryside Inn stays at 140 from March through May.');

INSERT INTO analytical (category, type, question, chart_data, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Data Interpretation', 'bar', 'Which café experienced a mid‑period trough in March?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Coastal Bakery","data":[130,135,120,140,145],"backgroundColor":"#8D6E63"},{"label":"Prairie Café","data":[125,130,135,140,145],"backgroundColor":"#26A69A"}]}', 'Coastal Bakery', 'Prairie Café', 'Hilltop Café', 'Valley Diner', 'Coastal Bakery dips to 120 in March before rebounding.'),
('Data Interpretation', 'bar', 'Which deli led in sales every month?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Uptown Deli","data":[150,155,160,165,170],"backgroundColor":"#EF5350"},{"label":"Downtown Deli","data":[140,145,150,155,160],"backgroundColor":"#42A5F5"}]}', 'Uptown Deli', 'Downtown Deli', 'Bayfront Café', 'Garden Restaurant', 'Uptown Deli remains above Downtown Deli each month.'),
('Data Interpretation', 'bar', 'Which bistro saw a one‑month spike in April?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Garden Bistro","data":[110,115,120,160,125],"backgroundColor":"#AB47BC"},{"label":"Harbor Bistro","data":[115,120,125,130,135],"backgroundColor":"#66BB6A"}]}', 'Garden Bistro', 'Harbor Bistro', 'Countryside Inn', 'City Bistro', 'Garden Bistro jumps to 160 in April then falls.'),
('Data Interpretation', 'bar', 'Which café showed no change in May from April?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Metro Café","data":[100,110,120,130,130],"backgroundColor":"#26A69A"},{"label":"Suburban Eatery","data":[105,115,125,135,140],"backgroundColor":"#FFA726"}]}', 'Metro Café', 'Suburban Eatery', 'Forest Tea House', 'Skyline Lounge', 'Metro Café stays at 130 in April and May.'),
('Data Interpretation', 'bar', 'Which lounge had the steepest rise from January to February?', '{"labels":["Jan","Feb","Mar","Apr","May"],"datasets":[{"label":"Skyline Lounge","data":[120,150,160,170,180],"backgroundColor":"#AB47BC"},{"label":"Grove Lounge","data":[130,140,150,160,170],"backgroundColor":"#42A5F5"}]}', 'Skyline Lounge', 'Grove Lounge', 'Oceanview Bar', 'Countryside Inn', 'Skyline Lounge rises by 30 from Jan to Feb, more than Grove Lounge''s 10.');



