
Definition = [
    "Aberration", "Abeyance", "Abnegate", "abolish", "abortion", "Abrogate", "Abscond", "absence", "absent", "Abstemious",
    "Abstruse", "absurd", "abuse", "academy", "accelerate", "acceptance", "accessible", "Accolade", "accomplishment", "accordingly",
    "accountability", "accountable", "Accretion", "accumulate", "accumulation", "accusation", "accused", "acid", "acquisition", "Acrimonious",
    "activation", "activist", "Acumen", "acute", "adaptation", "adhere", "adjacent", "Adjudicate", "Adjure", "adjustment",
    "administer", "administrative", "administrator", "admission", "Admonish", "adolescent", "adoption", "Adroit", "Adulation", "adverse",
    "advocate", "aesthetic", "Affable", "affection", "aftermath", "aggression", "agricultural", "aide", "Alacrity", "alert",
    "align", "alignment", "alike", "allegation", "allege", "allegedly", "alliance", "allocate", "allocation", "allowance",
    "ally", "Aloof", "aluminium", "Amalgamate", "amateur", "ambassador", "Ambiguous", "Ambivalent", "Ameliorate", "Amenable",
    "amend", "amendment", "amid", "Anachronistic", "Analogous", "analogy", "Anarchy", "anchor", "Anecdote", "angel",
    "Animosity", "Anomaly", "anonymous", "Antagonize", "Antipathy", "Apathy", "Aplomb", "Apocryphal", "apparatus", "apparel",
    "appealing", "Appease", "appetite", "applaud", "applicable", "appoint", "appreciation", "Apprehension", "Approbation", "Appropriate",
    "Arbiter", "arbitrary", "Arbitrate", "Arcane", "Archaic", "architectural", "archive", "Arduous", "arena", "arm (v)",
    "array", "articulate", "Artifice", "Ascertain", "Ascetic", "ash", "Asperity", "aspiration", "aspire", "assassination",
    "assault", "assemble", "assembly", "assert", "assertion", "Assiduous", "Assuage", "assurance", "Astute", "asylum",
    "atrocity", "Atrophy", "attain", "attendance", "attribute", "Attrition", "auction", "Audacious", "audit", "Augment",
    "Auspicious", "Austere", "authentic", "authorise", "auto", "Autonomous", "autonomy", "autumn", "availability", "Avarice",
    "Aver", "Aversion", "await", "backdrop", "backing", "backup", "bail", "Baleful", "ballot", "Banal",
    "Bane", "bankruptcy", "banner", "bare", "barrel", "Bashful", "bass", "battlefield", "bay", "beam",
    "beast", "behalf", "behavioural", "Belie", "Bellicose", "Belligerent", "beloved", "bench", "benchmark", "beneath",
    "beneficiary", "Benevolent", "Bequeath", "Berate", "betray", "beverage", "Bewilder", "bind", "biography", "bishop",
    "bizarre", "blade", "Blandishment", "blast", "Blatant", "bleed", "blend", "bless", "blessing", "boast",
    "Bolster", "Bombastic", "bonus", "booking", "boom", "Boon", "Boorish", "bounce", "boundary", "bow",
    "breach", "breakdown", "breakthrough", "breed", "Brevity", "broadband", "browser", "brutal", "buddy", "buffer",
    "bulk", "burden", "bureaucracy", "Burgeon", "burial", "burst", "cabinet", "Cacophony", "Cajole", "Calamity",
    "calculation", "Callous", "Candor", "canvas", "capability", "capitalism", "capitalist", "Capricious", "Captious", "cargo",
    "carriage", "carve", "casino", "Castigate", "casualty", "catalogue", "Catalyst", "cater", "cattle", "Caustic",
    "caution", "cautious", "cease", "cemetery", "Censure", "chamber", "chaos", "characterise", "charm", "charter",
    "Chastise", "Chicanery", "choir", "chronic", "chunk", "circulate", "circulation", "Circumspect", "citizenship", "civic",
    "civilian", "Clairvoyant", "Clamor", "clarity", "clash", "classification", "Clemency", "cling", "clinical", "closure",
    "cluster", "coalition", "coastal", "cocktail", "Cogent", "cognitive", "Cognizant", "Coherent", "coincide", "collaborate",
    "collaboration", "collective", "collision", "Collusion", "colonial", "columnist", "combat", "commence", "Commensurate", "commentary",
    "commentator", "commerce", "commissioner", "commodity", "communist", "companion", "comparable", "compassion", "compel", "compelling",
    "Compendious", "compensate", "compensation", "competence", "competent", "compile", "Complacent", "complement", "complexity", "compliance",
    "complication", "Complicit", "comply", "composition", "compromise", "compute", "conceal", "concede", "conceive", "conception",
    "concession", "Conciliatory", "condemn", "Condone", "confer", "confession", "configuration", "confine", "confirmation", "Conflagration",
    "confront", "confrontation", "Congenial", "congratulate", "congregation", "congressional", "Conjecture", "Connoisseur", "conquer", "conscience",
    "consciousness", "Consecrate", "consecutive", "consensus", "consent", "conserve", "consistency", "consolidate", "constitute", "constitution",
    "constitutional", "constraint", "consultation", "contemplate", "contempt", "contend", "contender", "content", "Contention", "Contentious",
    "continually", "contractor", "contradiction", "contrary", "contributor", "Contrite", "Contusion", "Conundrum", "conversion", "convict",
    "conviction", "Convivial", "cooperate", "cooperative", "coordinate", "coordination", "coordinator", "copper", "copyright", "correction",
    "correlate", "correlation", "correspond", "correspondence", "correspondent", "corresponding", "Corroborate", "corrupt", "corruption", "costly",
    "councillor", "counselling", "counsellor", "Countenance", "counter (argue)", "counterpart", "countless", "coup", "courtesy", "Covet",
    "craft", "crawl", "creator", "credibility", "credible", "Credulous", "creep", "critique", "crown", "crude",
    "crush", "Cryptic", "crystal", "cult", "cultivate", "curiosity", "Cursory", "custody", "cutting", "cynical",
    "dam", "damaging", "Daunting", "dawn", "Debase", "Debilitate", "debris", "debut", "decision-making", "decisive",
    "declaration", "Decorous", "dedicated", "dedication", "deed", "deem", "default", "defect", "defensive", "Deference",
    "deficiency", "deficit", "defy", "delegate", "delegation", "Deleterious", "delicate", "Delineate", "Demagogue", "demon",
    "denial", "Denigrate", "denounce", "dense", "density", "dependence", "depict", "deploy", "deployment", "deprive",
    "deputy", "Deride", "Derivative", "descend", "descent", "Desecrate", "Desiccate", "designate", "desirable", "desktop",
    "Despot", "destructive", "detain", "detection", "detention", "deteriorate", "devastate", "devil", "devise", "diagnose"
    "diagnosis", "Diaphanous", "Diatribe", "Dichotomy", "dictate", "dictator", "differentiate", "Diffident", "dignity", "Digression",
    "Dilatory", "dilemma", "Dilettante", "dimension", "diminish", "dip", "diplomat", "diplomatic", "directory", "Dirge",
    "disastrous", "Disavow", "discard", "Discerning", "discharge", "disclose", "disclosure", "Discomfit", "Disconcert", "Discordant",
    "discourse", "Discredit", "Discrepancy", "discretion", "discrimination", "Disdain", "dismissal", "Disparate", "displace", "disposal",
    "dispose", "dispute", "disrupt", "disruption", "Disseminate", "Dissident", "dissolve", "Distend", "distinction", "distinctive",
    "distort", "distress", "disturbing", "Dither", "divert", "divine", "doctrine", "documentation", "Dogmatic", "domain",
    "dominance", "donor", "Dormant", "dose", "drain", "drift", "driving", "drown", "dual", "dub",
    "Dubious", "dumb", "duo", "Duplicity", "earnings", "ease", "Ebullient", "echo", "Eclectic", "ecological",
    "Edict", "educator", "effectiveness", "efficiency", "ego", "Egregious", "elaborate", "electoral", "elevate", "eligible",
    "elite", "Elucidate", "embark", "embarrassment", "embassy", "embed", "Embezzle", "embody", "emergence", "Empirical",
    "empower", "Emulate", "enact", "encompass", "encouragement", "encouraging", "endeavour", "endless", "endorse", "endorsement",
    "endure", "Enervate", "enforce", "enforcement", "engagement", "engaging", "Enigma", "Enmity", "enrich", "enroll",
    "ensue", "enterprise", "enthusiast", "entitle", "entity", "Ephemeral", "epidemic", "equality", "Equanimity", "equation",
    "Equivocal", "erect", "Erudite", "escalate", "Esoteric", "essence", "establishment", "eternal", "Euphemism", "Euphony",
    "evacuate", "Evanescent", "evoke", "evolutionary", "Exacerbate", "exaggerate", "Exalt", "excellence", "exceptional", "excess",
    "exclusion", "exclusive", "exclusively", "execute", "execution", "exert", "Exhort", "exile", "Exonerate", "Exorbitant",
    "Expatiate", "Expedient", "expenditure", "experimental", "Expiate", "expire", "explicit", "explicitly", "exploitation", "explosive",
    "Extol", "Extraneous", "extremist", "Extricate", "Exult", "Fabricate", "Facetious", "Facile", "facilitate", "faction",
    "fade", "fairness", "Fallacious", "Fastidious", "fatal", "fate", "Fatuous", "favourable", "feat", "Fecund",
    "Felicitous", "felony", "feminist", "Fervent", "fibre", "fierce", "filmmaker", "filter", "fine", "firearm",
    "fiscal", "fit", "Flagrant", "flaw", "flawed", "flee", "fleet", "flesh", "flexibility", "Flippant",
    "Florid", "flourish", "fluid", "Foment", "footage", "foreigner", "forge", "formula", "formulate", "forth",
    "forthcoming", "foster", "Fractious", "fragile", "franchise", "frankly", "freshman", "Frugal", "frustrated", "frustrating",
    "frustration", "functional", "fundraising", "funeral", "gambling", "Garrulous", "gathering", "gaze", "gear", "generic",
    "genocide", "gig", "glance", "glimpse", "glorious", "glory", "governance", "grace", "Grandiloquent", "grasp",
    "Gratuitous", "grave (cemetery)", "grave (serious)", "gravity", "Gregarious", "grid", "grief", "grin", "grind", "grip",
    "gross", "guerrilla", "guidance", "Guile", "guilt", "gut", "Hackneyed", "hail", "halfway", "halt",
    "handful", "handling", "handy", "Harangue", "harassment", "hardware", "harmony", "harsh", "harvest", "hatred",
    "Haughty", "haunt", "hazard", "Hedonist", "heighten", "Heretic", "heritage", "hierarchy", "high-profile", "hint",
    "homeland", "hopeful", "horizon", "horn", "hostage", "hostile", "hostility", "humanitarian", "humanity", "humble",
    "hydrogen", "Iconoclast", "identification", "ideological", "ideology", "Idiosyncratic", "idiot", "ignorance", "imagery", "immense",
    "imminent", "Impecunious", "Impervious", "Impetuous", "Implacable", "implementation", "imprison", "inability", "inadequate", "Inadvertent",
    "inappropriate", "incarcerate", "incarceration", "Inchoate", "incidence", "inclined", "inclusion", "Incongruous", "Incontrovertible", "incur",
    "Indefatigable", "indicator", "indictment", "indigenous", "Indolent", "induce", "indulge", "Ineffable", "inequality", "Inexorable",
    "infamous", "infant", "infect", "inflict", "influential", "Ingenuous", "inherent", "inhibit", "Inimical", "initiate",
    "inject", "injection", "injustice", "inmate", "Innocuous", "inquire", "insertion", "insider", "Insipid", "inspect",
    "inspection", "inspiration", "instinct", "institutional", "instruct", "instrumental", "insufficient", "Insular", "insult", "intact",
    "intake", "integral", "integrated", "integration", "integrity", "intensify", "intensity", "intensive", "intent", "interactive",
    "interface", "interfere", "interference", "interim", "interior", "intermediate", "intersection", "intervene", "intervention", "intimate",
    "Intransigent", "intriguing", "Inundate", "Invective", "inventory", "investigator", "invisible", "invoke", "involvement", "Irascible",
    "ironic", "ironically", "irony", "irrelevant", "Irrevocable", "isolation", "Itinerant", "Jaded", "judicial", "jurisdiction",
    "just", "justification", "Juxtapose", "keen", "kidnap", "kidney", "kingdom", "Knell", "Laconic", "landlord",
    "landmark", "Languid", "lap", "large-scale", "laser", "Lassitude", "latter", "Laudable", "lawmaker", "lawn",
    "lawsuit", "layout", "leak", "leap", "legacy", "legendary", "legislation", "legislative", "legislature", "legitimate",
    "lengthy", "lesbian", "lesser", "lethal", "liable", "liberal", "liberation", "liberty", "Licentious", "lifelong",
    "likelihood", "limb", "line-up", "linear", "linger", "listing", "literacy", "litre", "liver", "Loathe",
    "lobby", "log", "logic", "long-standing", "long-time", "loom", "loop", "Loquacious", "loyalty", "Lucid",
    "Lugubrious", "machinery", "magical", "Magnanimous", "magnetic", "magnitude", "mainland", "mainstream", "maintenance", "Malaise",
    "mandate", "mandatory", "manifest", "manipulate", "manipulation", "manuscript", "march", "marginal", "marine", "marketplace",
    "mask", "massacre", "mathematical", "mature", "Maverick", "maximise", "meaningful", "meantime", "medieval", "meditation"
    "melody", "memo", "memoir", "memorial", "Mendacious", "mentor", "merchant", "Mercurial", "mercy", "mere",
    "merely", "merge", "merger", "merit", "methodology", "Meticulous", "midst", "migration", "militant", "militia",
    "mill", "minimal", "minimise", "mining", "ministry", "minute", "miracle", "Mirth", "Misanthrope", "misery",
    "misleading", "missile", "Mitigate", "mob", "mobile", "mobilise", "mobility", "moderate", "modification", "module",
    "Mollify", "momentum", "monk", "monopoly", "morality", "Morose", "motive", "Mundane", "municipal", "mutual",
    "Myriad", "Nadir", "namely", "nationwide", "naval", "Nebulous", "Nefarious", "neglect", "Negligible", "neighbouring",
    "Neophyte", "nest", "net", "newsletter", "niche", "noble", "nod", "Noisome", "nominate", "nomination",
    "nominee", "non-profit", "Nonchalant", "nonetheless", "nonsense", "noon", "Nostalgia", "notable", "notably", "notify",
    "notorious", "novel", "Nuance", "nursery", "Obdurate", "Obfuscate", "objection", "oblige", "Obsequious", "obsess",
    "obsession", "Obtuse", "occasional", "occurrence", "odds", "offering", "Officious", "offspring", "Onerous", "operational",
    "opt", "optical", "optimism", "Opulent", "oral", "organisational", "orientation", "originate", "Ostentatious", "outbreak",
    "outing", "outlet", "outlook", "outrage", "outsider", "overlook", "overly", "oversee", "overturn", "overwhelm",
    "overwhelming", "pad", "Panacea", "Paradox", "Paragon", "parameter", "Paramount", "parental", "parliament", "Parsimonious",
    "partial", "partially", "passing", "passive", "pastor", "patent", "pathway", "patrol", "patron", "Paucity",
    "peak", "peasant", "peculiar", "Pejorative", "Pellucid", "Penchant", "pension", "Penurious", "Perennial", "Perfidious",
    "Perfunctory", "Pernicious", "persist", "persistent", "personnel", "Perspicacious", "Pertinent", "petition", "Petulant", "Philanthropy",
    "philosopher", "philosophical", "Phlegmatic", "Piety", "pioneer", "pipeline", "pirate", "pit", "Placate", "Platitude",
    "plea", "plead", "pledge", "Plethora", "plug", "plunge", "pole", "poll", "pond", "pop",
    "portfolio", "portray", "post-war", "postpone", "practitioner", "Pragmatic", "preach", "Precarious", "precedent", "precision",
    "Precocious", "predator", "predecessor", "predominantly", "pregnancy", "prejudice", "preliminary", "premier", "premise", "premium",
    "prescribe", "prescription", "presently", "preservation", "preside", "presidency", "prestigious", "presumably", "presume", "Presumptuous",
    "prevail", "prevalence", "Prevaricate", "prevention", "prey", "privatization", "privilege", "probe", "Probity", "problematic",
    "proceeding", "proceeds", "processing", "processor", "proclaim", "Proclivity", "productive", "productivity", "profitable", "Profligate",
    "profound", "projection", "Prolific", "prominent", "pronounced", "propaganda", "Propensity", "Propitious", "proposition", "Prosaic",
    "prosecute", "prosecution", "prosecutor", "prospective", "prosperity", "Protean", "protective", "protocol", "province", "provincial",
    "provision", "provoke", "Prudent", "psychiatric", "Pugnacious", "Pulchritudinous", "pulse", "pump", "punch", "Punctilious",
    "Quagmire", "Querulous", "query", "quest", "Quixotic", "quota", "radar", "radical", "rage", "raid",
    "rally", "Rancorous", "ranking", "Rapacious", "rape", "ratio", "rational", "ray", "readily", "realization",
    "realm", "rear", "reasoning", "reassure", "rebel", "rebellion", "Recalcitrant", "Recant", "recipient", "Recondite",
    "reconstruction", "recount", "recruitment", "Redoubtable", "referendum", "reflection", "reform", "refuge", "refusal", "Refute",
    "regain", "regardless", "regime", "regulator", "regulatory", "rehabilitation", "reign", "rejection", "Relegate", "relevance",
    "reliability", "reluctant", "remainder", "remains", "remedy", "reminder", "Remiss", "removal", "render", "renew",
    "renowned", "rental", "replacement", "reportedly", "Reprehensible", "representation", "Reprobate", "reproduce", "reproduction", "republic",
    "Repudiate", "Rescind", "resemble", "reside", "residence", "residential", "residue", "resignation", "Resilient", "resistance",
    "Resolute", "respective", "respectively", "restoration", "restraint", "resume", "Reticent", "retreat", "retrieve", "revelation",
    "revenge", "Reverent", "reverse", "revival", "revive", "revolutionary", "Rhetoric", "rifle", "riot", "rip",
    "ritual", "robust", "rock", "rod", "rookie", "roster", "rotate", "rotation", "ruling", "rumour",
    "sacred", "sacrifice", "saint", "sake", "sanction", "Sanguine", "Sardonic", "say", "scattered", "sceptical",
    "Scintillating", "scope", "screw", "Scrupulous", "scrutiny", "seal", "secondly", "secular", "seemingly", "segment",
    "seize", "seldom", "selective", "sensation", "sensitivity", "sentiment", "separation", "Serendipity", "serial", "Servile",
    "settlement", "setup", "sexuality", "shareholder", "shatter", "shed", "sheer", "shipping", "shoot", "shrink",
    "shrug", "sigh", "Simper", "simulate", "simulation", "simultaneously", "sin", "situated", "sketch", "skip",
    "slam", "slap", "slash", "slavery", "slot", "smash", "snap", "soak", "soar", "socialist",
    "sole", "solely", "solidarity", "solo", "sophomore", "Soporific", "sound", "sovereignty", "spam", "span",
    "spark", "specialised", "specification", "specimen", "Specious", "spectacle", "spectrum", "spell", "sphere", "spin",
    "spine", "spotlight", "spouse", "Spurious", "spy", "squad", "Squander", "squeeze", "stab", "stabilise",
    "stability", "Staid", "stake", "standing", "stark", "statistical", "steer", "stem", "stereotype", "Stigma",
    "stimulus", "stir", "Stolid", "storage", "straightforward", "strain", "strand", "strategic", "strip (narrow piece)", "strive",
    "structural", "stumble", "stun v.", "Subjugate", "Sublime", "submission", "subscriber", "subscription", "subsidy", "substantial",
    "substantially", "substitute", "substitution", "Subterfuge", "subtle", "suburban", "succession", "successive", "successor", "suck"
    "sue", "suicide", "suite", "summit", "superb", "Supercilious", "superintendent", "superior", "supervise", "supervision",
    "supervisor", "supplement", "supportive", "supposedly", "suppress", "supreme", "Surfeit", "surge", "surgical", "surplus",
    "surrender", "Surreptitious", "surveillance", "suspension", "suspicion", "suspicious", "sustain", "swing", "sword", "Sycophant",
    "symbolic", "syndrome", "synthesis", "systematic", "Taciturn", "tackle", "tactic", "tactical", "Tantamount", "taxpayer",
    "Temerity", "tempt", "tenant", "tender", "Tenuous", "tenure", "terminate", "terrain", "terrific", "Terse",
    "testify", "testimony", "texture", "thankfully", "theatrical", "theology", "theoretical", "thereafter", "thereby", "thoughtful",
    "thread", "threshold", "thrilled", "thrive", "tide", "tighten", "timber", "timely", "Timorous", "tobacco",
    "tolerance", "tolerate", "toll", "top", "Torpid", "torture", "toss", "total", "toxic", "trademark",
    "trail", "trailer", "transaction", "transcript", "transformation", "transit", "transmission", "transparency", "transparent", "trauma",
    "treaty", "tremendous", "Trepidation", "tribal", "tribute", "trio", "Trite", "triumph", "trophy", "troubled",
    "Truculent", "trustee", "tuition", "tumour", "turnout", "turnover", "twist", "Ubiquitous", "Umbrage", "unconstitutional",
    "Unctuous", "undergraduate", "underlying", "Undermine", "undoubtedly", "Unfettered", "unify", "Unilateral", "Unprecedented", "Untenable",
    "unveil", "upcoming", "upgrade", "uphold", "Urbane", "Usurp", "utilise", "utility", "utterly", "Vacillate",
    "vacuum", "vague", "validity", "vanish", "variable", "varied", "vein", "Venerate", "venture", "Veracity",
    "verbal", "Verbose", "verdict", "verify", "verse", "versus", "vessel", "veteran", "Vex", "viable",
    "vibrant", "Vicarious", "vice", "vicious", "Vicissitude", "Vilify", "Vindicate", "violate", "violation", "virtue",
    "Virtuoso", "Vitriolic", "Vituperate", "vocal", "Volatile", "Voluble", "Voracious", "vow", "vulnerability", "vulnerable",
    "Wane", "ward", "warehouse", "warfare", "warrant", "warrior", "weaken", "weave", "weed", "well",
    "well-being", "whatsoever", "whereby", "Whimsical", "whip", "wholly", "widen", "widow", "width", "willingness",
    "wipe", "Wistful", "wit", "withdrawal", "workout", "worship", "worthwhile", "worthy", "yell", "yield",
    "Zealous", "Zenith"
]

Synonyms = [
        "Abandon", "Abase", "Abate", "Abdicate", "Aberrant", "Aberration", "Abet", "Abeyance", "Abhor", "Abhorrent",
        "Abject", "Ablution", "Abnegate", "Abnegation", "Abolish", "Abominable", "Abrogate", "Abscond", "Abstain", "Abstemious",
        "Abstruse", "Accede", "Accelerate", "Accolade", "Accomplish", "Accost", "Account", "Accretion", "Accurate", "Acerbic",
        "Achieve", "Acknowledge", "Acquiesce", "Acquire", "Acrid", "Acrimonious", "Acumen", "Adamant", "Adapt", "Adaptable",
        "Adjust", "Admire", "Admonish", "Adroit", "Adulation", "Adulterate", "Adumbrate", "Advance", "Adventure", "Adversarial",
        "Adverse", "Aesthetic", "Affable", "Affected", "Affinity", "Afflict", "Affluent", "Affront", "Aged", "Aggrandize",
        "Aggregate", "Agile", "Agitate", "Aid", "Alacrity", "Alarm", "Alchemy", "Alienate", "Alleviate", "Allocate",
        "Allude", "Allure", "Allusion", "Aloof", "Alter", "Altruistic", "Amalgamate", "Amazing", "Ambiguous", "Ambivalent",
        "Ameliorate", "Amelioration", "Amenable", "Amicable", "Amorphous", "Amplify", "Amusing", "Anachronism", "Analogous", "Anarchy",
        "Anathema", "Anathematize", "Anecdote", "Anger", "Angry", "Anguish", "Animated", "Annex", "Annihilate", "Annoy",
        "Annul", "Anomalous", "Answer", "Antagonize", "Antecedent", "Antediluvian", "Anthology", "Anthropomorphic", "Anticipate", "Antipathy",
        "Antiquated", "Anxiety", "Apathy", "Apex", "Aphorism", "Apocryphal", "Apotheosis", "Appall", "Apparent", "Apparition",
        "Appear", "Appease", "Appellation", "Append", "Appetizing", "Apposite", "Appraise", "Appreciate", "Apprehend", "Apprehensive",
        "Apprise", "Approach", "Approbation", "Appropriate (v)", "Apropos", "Apt", "Arbiter", "Arbitrary", "Arcane", "Arduous",
        "Area", "Arise", "Arrest", "Arrive", "Arrogate", "Articulate", "Artless", "Ascetic", "Ask", "Asperity",
        "Assail", "Assassinate", "Assiduous", "Assign", "Assist", "Assorted", "Assuage", "Astonishing", "Astral", "Astute",
        "Atrophy", "Attain", "Attenuate", "Audacious", "Augment", "Auspicious", "Austere", "Avarice", "Avaricious", "Aver",
        "Averment", "Averse", "Aversion", "Awful", "Bad", "Baleful", "Banal", "Bawl", "Be Pleased", "Beautiful",
        "Begin", "Behind", "Belie", "Believe", "Bellicose", "Belligerence", "Belligerent", "Benefactor", "Beneficent", "Benevolent",
        "Benign", "Bent", "Big", "Bilious", "Blandishment", "Blatant", "Blithe", "Bolster", "Bombastic", "Boorish",
        "Brave", "Break", "Bright", "Brighten", "Bucolic", "Burgeon", "Burnish", "Bustle", "Cabal", "Cacophony",
        "Cajole", "Calm", "Calumniate", "Calumny", "Camouflage", "Canonical", "Capricious", "Capture", "Carry Out", "Carve",
        "Castigate", "Catalyst", "Catch", "Caustic", "Cease", "Certain", "Characterize", "Charitable", "Chary", "Chicanery",
        "Chilly", "Choose", "Churlish", "Circumlocution", "Circumlocutory", "Circumspect", "Clarify", "Cleave", "Clemency", "Coarse",
        "Cogent", "Cold", "Collusion", "Combine", "Come", "Complacent", "Complaisance", "Conceal", "Concept", "Conception",
        "Conciliatory", "Conclude", "Condone", "Conflagrant", "Conflagration", "Confluence", "Confound", "Congenial", "Conjoin", "Connoisseur",
        "Conquer", "Consider", "Contaminated", "Contemplate", "Contented", "Contention", "Contentious", "Contrast", "Contrite", "Contumacious",
        "Contumely", "Conundrum", "Converge", "Convivial", "Cool", "Copious", "Corpulent", "Correct", "Corroborate", "Counterfeit",
        "Courageous", "Covet", "Crash", "Craven", "Crawl", "Credulous", "Creep", "Critical", "Crooked", "Cry",
        "Current", "Cursory", "Cut", "Damage", "Dangerous", "Dapper", "Dark", "Dash", "Dauntless", "Dazzling",
        "Dearth", "Decide", "Deference", "Define", "Definite", "Delectable", "Deleterious", "Deleteriously", "Delicious", "Delight In",
        "Delighted", "Delineate", "Demagogue", "Demolish", "Demur", "Denigrate", "Depart", "Depraved", "Deride", "Derivative",
        "Descend", "Describe", "Desert", "Desiccate", "Desideratum", "Design", "Despise", "Destroy", "Desultory", "Determine",
        "Determined", "Detest", "Diaphanous", "Diatribe", "Dichotomy", "Difference", "Different", "Diffidence", "Diffuse", "Dilapidated",
        "Dilemma", "Diminutive", "Dinky", "Direct", "Disabuse", "Disagreement", "Disappear", "Discerning", "Disclose", "Discordant",
        "Discrepancy", "Discretion", "Disingenuous", "Disinterested", "Disparage", "Disparagement", "Disparate", "Display", "Dissemble", "Disseminate",
        "Dissimilarity", "Dissimulate", "Dissolution", "Dissonance", "Distend", "Distinguished", "Distress", "Dither", "Diverse", "Do",
        "Dogmatic", "Dormant", "Dread", "Dreadful", "Droll", "Drop", "Dull", "Dupe", "Duplicity", "Eager",
        "Ebullient", "Eclectic", "Effect", "Effervescence", "Efficacy", "Effrontery", "Egregious", "Elaborate", "Eloquent", "Embellish",
        "Emerge", "Empirical", "Emulate", "Enact", "Encomium", "Encourage", "End", "Endemic", "Enervate", "Engender",
        "Enigma", "Enjoy", "Enlarge", "Enlighten", "Enmity", "Enormous", "Enrage", "Enraged", "Enthusiastic", "Ephemeral",
        "Equanimity", "Equivocal", "Equivocate", "Erudite", "Esoteric", "Establish", "Esteem", "Eulogy", "Euphemism", "Evolve",
        "Exacerbate", "Exacting", "Excellent", "Exculpate", "Execrate", "Execute", "Exegesis", "Exhibit", "Exhortation", "Exigent",
        "Exonerate", "Exorbitant", "Expand", "Expatiate", "Expedient", "Expedition", "Expiate", "Expiatory", "Explain", "Explicate",
        "Expose", "Expurgate", "Extant", "Extol", "Extraneous", "Extricate", "Fabricate", "Facetious", "Facilitate", "Factual",
        "Fade", "Fair", "Fake", "Fall", "Fallacious", "Fancy", "Fascinating", "Fast", "Fastidious", "Fat",
        "Fatuous", "Fear", "Fearful", "Fearless", "Fecund", "Felicitous", "Fervent", "Fervid", "Finish", "Flagrant",
        "Flexible", "Flippant", "Flit", "Florid", "Fly", "Foible", "Foment", "Forbearance", "Forsake", "Fortuitous",
        "Fraction", "Fractious", "Fracture", "Fragment", "Fraudulent", "Fright", "Frigid", "Frosty", "Frugal", "Frustrate",
        "Fulfill", "Funny", "Furious", "Gain", "Gainsay", "Garrulous", "Generous", "Get", "Gigantic", "Gloomy",
        "Go", "Good", "Gorgeous", "Grandiloquent", "Grasp", "Gratuitous", "Great", "Gregarious", "Gross", "Guide",
        "Guile", "Hackneyed", "Halcyon", "Halt", "Hapless", "Happy", "Harangue", "Harbinger", "Hasten", "Hasty",
        "Hate", "Have", "Hazardous", "Heinous", "Help", "Heterogeneous", "Hiatus", "Hide", "Histrionic", "Hoary",
        "Hold", "Homogeneous", "Hooked", "Horrible", "Hover", "Huge", "Humorous", "Hurry", "Hurt", "Hyperbole",
        "Iconoclast", "Idea", "Idiosyncrasy", "Idle", "Ignominious", "Illuminate", "Immense", "Immutable", "Impartial", "Impassive",
        "Impecunious", "Imperative", "Impervious", "Impetuous", "Impish", "Implacable", "Implicate", "Important", "Imprecation", "Impregnable",
        "Impress", "Imprint", "Improbable", "Improper", "Improvident", "Inactive", "Inchoate", "Incontrovertible", "Incorrigible", "Incredible",
        "Inculcate", "Indecent", "Indefatigability", "Indefatigable", "Indignant", "Indispensable", "Indolent", "Indulge In", "Ineffable", "Ineluctable",
        "Inept", "Inequity", "Inert", "Inexorable", "Infuriate", "Ingenuous", "Inimical", "Iniquity", "Initiate", "Innocuous",
        "Inquire", "Insecure", "Insensible", "Insidious", "Insipid", "Insouciance", "Inspect", "Insularity", "Intelligent", "Intensify",
        "Interesting", "Interpret", "Interrogate", "Intractable", "Intransigence", "Intransigent", "Intrepid", "Inundate", "Inure", "Invective",
        "Inveterate", "Invidious", "Involved", "Irascible", "Itinerant", "Join", "Journey", "Just", "Juxtapose", "Keen",
        "Keep", "Kill", "Kind-hearted", "Laconic", "Lassitude", "Latent", "Laudable", "Laughable", "Launch", "Lazy",
        "Leave", "Lethargic", "Levity", "Lifeless", "Lighten", "Like", "Limpid", "Little", "Loathe", "Location",
        "Look", "Loquacious", "Love", "Lucid", "Lugubrious", "Luscious", "Machination", "Magnanimous", "Magnificent", "Magnify",
        "Magniloquence", "Maintain", "Make", "Malaise", "Malevolent", "Malinger", "Malleable", "Manufacture", "Mark", "Marvelous",
        "Materialize", "Maverick", "Mediate", "Meditate", "Mendacious", "Mendicant", "Mercurial", "Merge", "Meticulous", "Miniature",
        "Misanthrope", "Mischievous", "Mitigate", "Modern", "Modify", "Mollify", "Monstrous", "Morose", "Move", "Multifaceted",
        "Mundane", "Murky", "Nadir", "Narrate", "Narrative", "Nascent", "Nasty", "Natty", "Navigate", "Near",
        "Neat", "Nebulous", "Necessary", "Nefarious", "Negligible", "Neophyte", "New", "Noisome", "Nominal", "Nonplussed",
        "Nostalgia", "Note", "Noteworthy", "Notion", "Novel", "Nuance", "Obdurate", "Obfuscate", "Objective", "Oblique",
        "Obsequious", "Obtain", "Obtuse", "Odd", "Officious", "Old", "Onerous", "Opaque", "Open", "Opulent",
        "Ostensible", "Ostentatious", "Pacify", "Pain", "Palatable", "Palliate", "Panacea", "Panicked", "Paradigm", "Paradox",
        "Paragon", "Paramount", "Parsimonious", "Part", "Pathos", "Paucity", "Paunchy", "Pause", "Peaceful", "Peculiar",
        "Pedantic", "Penchant", "Penurious", "Perfidious", "Perfidy", "Perfunctory", "Perilous", "Permeate", "Perspicacious", "Pertinacious",
        "Pertinent", "Pervasive", "Phlegmatic", "Picture", "Piety", "Pilot", "Placate", "Place", "Placid", "Plan",
        "Plasticity", "Platitude", "Pleased", "Plethora", "Pliable", "Plight", "Plod", "Plot", "Plump", "Plunge",
        "Ponder", "Ponderous", "Portion", "Portray", "Position", "Positive", "Pragmatic", "Prankish", "Precarious", "Precipitate",
        "Precise", "Precursor", "Predicament", "Prescient", "Present", "Prevaricate", "Pristine", "Probity", "Proclivity", "Procrastinate",
        "Procure", "Prodigal", "Prodigious", "Produce", "Profound", "Prohibitive", "Proliferate", "Prolific", "Propensity", "Proper",
        "Propitiate", "Propitiation", "Propriety", "Prosaic", "Provident", "Prudent", "Pugnacious", "Pugnacity", "Puny", "Put",
        "Qualified", "Quandary", "Querulous", "Query", "Question", "Quick", "Quiet", "Quixotic", "Race", "Radiant",
        "Rancorous", "Rapid", "Rarefy", "Raze", "Realize", "Recalcitrance", "Recalcitrant", "Recant", "Recede", "Recent",
        "Recondite", "Recount", "Rectify", "Redoubtable", "Reflect", "Refresh", "Refute", "Regenerate", "Region", "Relegate",
        "Relentless", "Relevant", "Remarkable", "Remedial", "Remiss", "Renew", "Renounce", "Reply", "Repudiate", "Rescind",
        "Resilient", "Resolute", "Resolve", "Respond", "Restful", "Restore", "Reticent", "Retort", "Reveal", "Reverent",
        "Revive", "Rhetoric", "Right", "Risky", "Rotten", "Rude", "Ruin", "Run", "Rush", "Sagacious",
        "Salacious", "Salubrious", "Sanction", "Sanguine", "Sardonic", "Satiate", "Satisfied", "Saturate", "Savant", "Savory",
        "Say", "Scared", "Scrupulous", "Scrutinize", "Section", "Secure", "Seize", "Serene", "Servile", "Settle",
        "Shadowy", "Shimmering", "Show", "Shroud", "Sinful", "Situation", "Slack", "Slay", "Slice", "Slit",
        "Slothful", "Slow", "Smart", "Soar", "Sob", "Soporific", "Space", "Sparkling", "Specious", "Splendid",
        "Sporadic", "Sportive", "Spot", "Sprint", "Spurious", "Squalid", "Stagnant", "Staid", "Stanch", "Start",
        "Staunch", "Stay", "Steer", "Stolid", "Stop", "Story", "Stout", "Strange", "Striated", "Stringent",
        "Study", "Stygian", "Succinct", "Succor", "Supercilious", "Superfluous", "Supplant", "Support", "Sure", "Surface",
        "Surfeit", "Surreptitious", "Survey", "Sustain", "Swiftly", "Sycophant", "Tacit", "Taciturn", "Take", "Tale",
        "Tangential", "Tedious", "Tell", "Tenuous", "Terminate", "Terrible", "Terror", "Think", "Thought", "Timorous",
        "Tiresome", "Topple", "Torpid", "Tortuous", "Trace", "Tractable", "Tranquil", "Transient", "Travel", "Trepidation",
        "Trim", "Trite", "Trouble", "Truculence", "Truculent", "Turbid", "Turgid", "Twisted", "Ubiquitous", "Ugly",
        "Umbrage", "Unassailable", "Unbelievable", "Unbiased", "Uncertain", "Unconscionable", "Undermine", "Unequivocal", "Unfamiliar", "Unfettered",
        "Unhurried", "Unimaginative", "Unite", "Unlit", "Unnerved", "Unpleasant", "Unprecedented", "Unruffled", "Unscrupulous", "Untenable"
        "Unusual", "Upbraid", "Urbane", "Urge", "Used", "Vacillate", "Varied", "Veil", "Venerate", "Veracious",
        "Verbose", "Versatile", "Vex", "Vicarious", "Vicissitude", "Vilify", "Vindicate", "Virtuoso", "Virulent", "Vital",
        "Vitiate", "Vituperate", "Vituperation", "Vivid", "Volatile", "Voluble", "Voyage", "Waggish", "Wail", "Wane",
        "Warranted", "Wary", "Weep", "Welter", "Whimsical", "Wily", "Wing", "Winsome", "Worn", "Worthy",
        "Wrathful", "Wreck", "Wretchedness", "Yarn", "Zealous", "Zenith", "Zigzag"
]

Antonyms = [
    "abate", "abet", "abeyance", "abhor", "abhorrence", "abrogate", "abstainer", "abstemious", "abstract", "abundance",
    "abundant", "accept", "acceptance", "accidental", "accolade", "accurate", "acquired", "active", "acumen", "adamant",
    "adept", "admit", "adoration", "adore", "adulation", "advance", "affable", "affirm", "affluent", "aftermath",
    "aggravate", "agitated", "alacrity", "alien", "ally", "alterable", "amass", "ambiguous", "amiable", "amity",
    "amorphous", "ample", "amplify", "ancient", "anxious", "apathetic", "apathy", "apex", "appear", "approval",
    "arrogant", "articulate", "artificial", "ascend", "asceticism", "assent", "atrophy", "attack", "attenuate", "atypical",
    "augment", "austere", "authentic", "authorize", "banal", "barbaric", "barren", "base", "behemoth", "belittle",
    "bellicose", "belligerence", "belligerent", "benevolent", "benign", "biased", "blemish", "bold", "bolster", "bolstering",
    "bottom", "brave", "brief", "brittle", "brusque", "bucolic", "burgeon", "cacophony", "cajole", "calm",
    "candid", "candor", "capable", "capricious", "captive", "careless", "caustic", "cautious", "censure", "certainty",
    "changeable", "cheerful", "circumspect", "clandestine", "clarify", "clarity", "clear", "clemency", "clumsy", "cogent",
    "coherent", "cohesion", "colossal", "commend", "common", "compassionate", "complex", "compliant", "compulsory", "conceal",
    "concise", "concrete", "concur", "confidence", "confirm", "conformist", "confused", "conquer", "conserve", "consistent",
    "constant", "construct", "continuation", "continuity", "conventional", "corroborate", "corrupted", "counterfeit", "courteous", "covert",
    "cowardly", "create", "critic", "criticism", "criticize", "crucial", "cruel", "cryptic", "cultured", "current",
    "danger", "dark", "dauntless", "dearth", "decadence", "decadent", "defeat", "defend", "defensible", "defiant",
    "defined", "deft", "defunct", "defy", "deleterious", "deliberate", "delicate", "democracy", "denunciation", "deny",
    "deplete", "depths", "deride", "descend", "desiccate", "despise", "despondent", "destitute", "destroy", "detest",
    "dexterous", "diatribe", "didactic", "diligent", "dim", "diminish", "diminutive", "direct", "discord", "discourage",
    "disgraceful", "dishonesty", "disjointed", "disperse", "disreputable", "dissent", "dissuade", "distinct", "diverse", "divided",
    "division", "dormant", "dull", "duplicity", "duress", "dynamic", "eager", "earnest", "ebullient", "eclectic",
    "economical", "edify", "efface", "effervescence", "effervescent", "effortless", "elaborate", "elegant", "elite", "elongate",
    "embrace", "eminent", "enact", "encourage", "endorse", "enduring", "energetic", "enervate", "engaging", "engender",
    "enhance", "enigma", "entertaining", "enthusiastic", "ephemeral", "equanimity", "equivocate", "erect", "erratic", "erroneous",
    "esoteric", "eternal", "eulogy", "evasive", "exacerbate", "excitable", "exciting", "exodus", "exonerate", "exoteric",
    "exotic", "expert", "explicit", "extant", "exterior", "extinguish", "extol", "extraordinary", "extravagant", "facetious",
    "facilitate", "faded", "fail", "fallacy", "fastidious", "feasible", "feeble", "fertile", "fervor", "few",
    "flatness", "flawed", "fleeting", "flexible", "flippant", "florid", "flowing", "fluent", "foe", "folly",
    "foment", "fortunate", "foster", "fragile", "fragmentation", "frantic", "free", "fresh", "friendly", "frivolity",
    "frivolous", "frugal", "frugality", "fulminate", "gainsay", "gale", "garrulity", "garrulous", "gather", "generous",
    "genial", "genuine", "glib", "glorify", "glutton", "gluttonous", "graceful", "gravity", "gregarious", "grim",
    "grow", "grueling", "guile", "guileless", "guilty", "gullible", "gumption", "hackneyed", "halcyon", "halting",
    "hamper", "haphazard", "hapless", "harbinger", "harmony", "healthy", "hedonism", "heed", "heedless", "hesitant",
    "heterogeneous", "hiatus", "hidden", "highlight", "hinder", "histrionic", "homogeneous", "honesty", "horizontal", "hostile",
    "humane", "humble", "hydrate", "hypertrophy", "hypothetical", "iconoclast", "idealistic", "ignorance", "ignore", "illicit",
    "illogical", "illuminate", "immaculate", "immense", "immutable", "impartial", "impeccable", "impede", "impervious", "implicate",
    "implicit", "impractical", "imprison", "imprudent", "inability", "inarticulate", "incite", "incoherent", "incompetence", "indifference",
    "inept", "ineptitude", "inert", "inferior", "influx", "inhospitable", "inhuman", "injustice", "innate", "innocent",
    "insane", "insignificant", "institute", "insufficient", "intangible", "integrity", "intensify", "intentional", "interior", "intractable",
    "inure", "invalid", "invalidate", "invigorate", "invigorating", "irrational", "isolate", "jaded", "jargon", "jeopardy",
    "jettison", "jocular", "jovial", "jubilant", "jubilation", "judicious", "justice", "justifiable", "juvenile", "juxtapose",
    "keen", "kindle", "kindred", "kinetic", "knack", "knell", "knowledge", "kowtow", "kudos", "labyrinthine",
    "laconic", "languid", "lassitude", "latent", "laud", "lavish", "lax", "lazy", "legal", "lengthy",
    "lenient", "lethargic", "lethargy", "levity", "liberate", "lifeless", "light", "lilliputian", "listless", "logical",
    "loquacious", "loquacity", "loyal", "lucid", "lucrative", "luminous", "major", "malevolent", "malicious", "malignant",
    "malleable", "master", "mature", "maverick", "meager", "methodical", "meticulous", "minor", "misanthrope", "miser",
    "miserable", "mislead", "mitigate", "mobile", "moderate", "modern", "moral", "morbid", "morose", "motionless",
    "mourning", "mundane", "munificent", "mutable", "myopic", "myriad", "mystical", "nadir", "naive", "naïve",
    "nebulous", "necessitate", "nefarious", "neglect", "negligent", "negligible", "neutral", "nonchalant", "novel", "novice",
    "now", "noxious", "null", "nullify", "nurture", "obdurate", "obedient", "obfuscate", "obscure", "obsolete",
    "obviate", "opaque", "oppose", "optimist", "opulent", "ordinary", "original", "ornate", "ostentatious", "ostracize",
    "overcome", "overt", "pacific", "pacifism", "pallid", "panacea", "panegyric", "parsimonious", "passionate", "paucity",
    "peaceable", "perfidious", "perfunctory", "peril", "permanent", "permeable", "pessimist", "pessimistic", "philanthropist", "pinnacle",
    "pit", "plain", "plain language", "planned", "plentiful", "plethora", "polite", "pollute", "polluted", "ponder",
    "ponderous", "pragmatic", "praise", "precise", "predictable", "prescient", "present", "preserve", "pristine", "private",
    "proficiency", "proficient", "profligacy", "profound", "proven", "provoke", "prudent", "public", "quagmire", "quaint",
    "qualified", "qualm", "quandary", "quell", "querulous", "quiescent", "quintessential", "quixotic", "rancor", "rapid",
    "rash", "ratify", "rational", "raze", "recalcitrant", "recant", "reckless", "reclusive", "refine", "refined",
    "refute", "reject", "release", "relinquish", "reluctance", "reluctant", "renaissance", "replenish", "reproach", "repulsive",
    "rescind", "resilient", "resist", "resolve", "retain", "reticence", "reticent", "retreat", "reveal", "revere",
    "revile", "revoke", "rigid", "robust", "rock bottom", "rude", "rural", "rush", "rustic", "safety",
    "salient", "salutary", "sane", "sanguine", "scarce", "scarcity", "scatter", "scorn", "secretive", "sensitize",
    "separate", "serene", "serious", "seriousness", "severity", "significant", "simple", "sincere", "sinuous", "skeptical",
    "skillful", "slovenly", "sluggish", "sociable", "solemn", "solid ground", "solitary", "soothing", "sophisticated", "soporific",
    "sparse", "specious", "spendthrift", "spontaneous", "squalid", "squander", "stabilize", "stagnant", "static", "stationary",
    "steadfast", "stimulating", "stingy", "stolid", "stormy", "straightforward", "strengthen", "strenuous", "strict", "stringent",
    "stupidity", "sturdy", "subdued", "succeed", "sufficient", "superficial", "superior", "suppress", "surfeit", "surly",
    "surplus", "surrender", "sycophant", "systematic", "tacit", "taciturn", "taciturnity", "talkative", "tangible", "tedious",
    "tempestuous", "temporary", "tepid", "terse", "tether", "thoughtful", "thrifty", "thrilling", "thrive", "timid",
    "timorous", "tiny", "tirade", "toxin", "traditionalist", "translucent", "transparent", "trepidation", "trite", "triumph",
    "trivial", "truncate", "trusting", "truth", "turbulent", "tyranny", "umbrage", "unambiguous", "unanimous", "uncanny",
    "uncouth", "undermine", "unfeasible", "ungainly", "uniform", "unity", "unpretentious", "unprofitable", "unqualified", "unrealistic",
    "unrelated", "untenable", "unworkable", "uphold", "uprightness", "urban", "urbane", "usurp", "vacuous", "vague",
    "valid", "validate", "vanish", "variable", "venerable", "venerate", "verbose", "verity", "vernacular", "vertical",
    "veteran", "veto", "viable", "vibrant", "vice", "victory", "vigor", "vilify", "virtue", "virtuous",
    "vital", "vitality", "void", "volatile", "voluntary", "wane", "wary", "wasteful", "waver", "wax",
    "weaken", "weakening", "weary", "whimsical", "whimsy", "willing", "willingness", "wily", "winsome", "wisdom",
    "wither", "withstand", "worldly", "xenial", "xenophobia", "yearn", "yield", "yoke", "yore", "zeal",
    "zealot", "zenith", "zephyr"
]

ContextualMeaning = [
    "Aberration", "Abeyance", "Acceleration", "Accommodation", "Accreditation", "Acute", "Adjudicate", "Adjustment", "Algorithm", "Amicus Curiae",
    "Amortization", "Anaphylaxis", "Annex", "Anomaly", "Antipathy", "Apathy", "Appreciation", "Arbitrage", "Arbitration", "Artery",
    "Assay", "Assign", "Asymptomatic", "Attenuation", "Auscultation", "Authorization", "Autonomy", "Backhaul", "Bandwidth", "Bankruptcy",
    "Baroque", "Base", "Baseline", "Bear", "Benign", "Bevel", "Bias", "Bill", "Bind", "Block",
    "Bond", "Boot", "Bull", "Cache", "Cadence", "Call", "Canon", "Capital", "Carrier", "Case",
    "Cash", "Catalyst", "Causal", "Cell", "Certificate", "Channel", "Charge", "Charter", "Chronic", "Circuit",
    "Citation", "Class", "Clear", "Client", "Clone", "Cloud", "Code", "Cohort", "Collateral", "Collection",
    "Combination", "Commence", "Commitment", "Commodity", "Common", "Communication", "Compact", "Compensation", "Compiler", "Complex",
    "Compliance", "Component", "Compound", "Compression", "Computation", "Concentration", "Concept", "Concession", "Condition", "Conductor",
    "Configuration", "Conform", "Connection", "Consensus", "Consideration", "Constant", "Constituent", "Constitution", "Construction", "Consumption",
    "Contact", "Container", "Contempt", "Context", "Contract", "Control", "Convergence", "Conversion", "Core", "Correlation",
    "Cost", "Counter", "Coupon", "Covenant", "Credential", "Credit", "Criteria", "Cross", "Current", "Curve",
    "Cycle", "Data", "Database", "Deal", "Debenture", "Debt", "Debug", "Decay", "Declaration", "Decryption",
    "Default", "Defendant", "Deficit", "Definition", "Degree", "Delegate", "Delivery", "Demand", "Democracy", "Demographic",
    "Deployment", "Depression", "Derivative", "Designation", "Desktop", "Detection", "Developer", "Deviation", "Device", "Diagnosis",
    "Differential", "Diffusion", "Digest", "Digital", "Dilution", "Dimension", "Discharge", "Discount", "Discourse", "Discovery",
    "Discrimination", "Disease", "Disposition", "Distributed", "Diversification", "Dividend", "Division", "Doctrine", "Document", "Domain",
    "Draft", "Drive", "Due", "Duty", "Dynamics", "Earnings", "Edition", "Efficacy", "Elastic", "Election",
    "Element", "Elevation", "Embolism", "Emergency", "Emission", "Emotion", "Encryption", "Endemic", "Endorse", "Enforcement",
    "Engagement", "Enjoin", "Enrichment", "Enterprise", "Entity", "Entropy", "Environment", "Enzyme", "Epidemic", "Equity",
    "Erosion", "Error", "Escape", "Estate", "Estimate", "Ethics", "Etiology", "Evidence", "Evolution", "Exchange",
    "Exclusion", "Execution", "Exemption", "Exercise", "Exhaust", "Existence", "Expansion", "Expedition", "Experience", "Experiment",
    "Expert", "Exposure", "Expression", "Extension", "Extent", "Extraction", "Factor", "Failure", "Fair", "Family",
    "Farce", "Farm", "Fast", "Fault", "Favor", "Feature", "Federal", "Fee", "Field", "File",
    "Filter", "Finance", "Firewall", "Firm", "Fiscal", "Fission", "Fixation", "Fixture", "Flash", "Flaw",
    "Flexibility", "Flight", "Flow", "Flu", "Fluid", "Flux", "Focus", "Force", "Foreclosure", "Forensic",
    "Form", "Format", "Formation", "Formula", "Fort", "Forum", "Fossil", "Foundation", "Fraction", "Fracture",
    "Framework", "Franchise", "Fraud", "Frequency", "Front", "Function", "Fund", "Fundamental", "Fusion", "Future",
    "Gain", "Garnishment", "Gas", "Gateway", "Gene", "General", "Generation", "Generic", "Genotype", "Genre",
    "Germ", "Gesture", "Graft", "Grant", "Graph", "Gravity", "Grid", "Gross", "Group", "Growth",
    "Guarantee", "Guardian", "Guideline", "Habeas Corpus", "Habitat", "Handle", "Hard", "Hardware", "Harm", "Harmony",
    "Hash", "Hazard", "Head", "Health", "Heap", "Heat", "Hedge", "Height", "Hierarchy", "High",
    "Hold", "Horizon", "Host", "Hybrid", "Hypervisor", "Hypothesis", "Icon", "Identity", "Idiopathic", "Image",
    "Immunity", "Impact", "Implementation", "Implied", "Import", "Impression", "Incentive", "Incidence", "Income", "Incorporation",
    "Index", "Indicator", "Industry", "Inertia", "Inflation", "Infrastructure", "Inheritance", "Inhibition", "Initial", "Injection",
    "Injury", "Inorganic", "Inquiry", "Insert", "Instance", "Institution", "Instruction", "Instrument", "Insurance", "Integration",
    "Integrity", "Intellect", "Intensity", "Interference", "Interim", "Internal", "Interpretation", "Interruption", "Interval", "Intervention",
    "Intestate", "Intrinsic", "Introduction", "Inventory", "Investment", "Invoice", "Ion", "IoT", "Irony", "Ischemia",
    "Issue", "Item", "Iteration", "Job", "Joint", "Journal", "Judge", "Judgment", "Jurisdiction", "Jury",
    "Justice", "Kernel", "Key", "Kinetic", "Knowledge", "Label", "Labor", "Lag", "Lambda", "Land",
    "Language", "Latency", "Law", "Layer", "Lead", "Lease", "Ledger", "Legacy", "Legal", "Legend",
    "Legislation", "Leverage", "Liability", "Libretto", "License", "Lien", "Life", "Limit", "Line", "Link",
    "Liquid", "List", "Litigation", "Load", "Loan", "Location", "Log", "Logic", "Long", "Loss",
    "Low", "Machine", "Macro", "Magistrate", "Magnetic", "Magnitude", "Maintenance", "Majority", "Malfeasance", "Malicious",
    "Malignant", "Malware", "Management", "Mandamus", "Manifest", "Manipulation", "Manual", "Margin", "Market", "Mask",
    "Mass", "Master", "Material", "Matrix", "Maturation", "Maximum", "Mean", "Measure", "Mechanism", "Media",
    "Medium", "Melt", "Membrane", "Memory", "Mental", "Merchant", "Merge", "Mesenchymal", "Message", "Metabolism",
    "Metastasis", "Meter", "Method", "Micro", "Migration", "Military", "Minimum", "Minority", "Minute", "Mirror",
    "Mise-en-scène", "Mitigation", "Mitosis", "Mobile", "Mode", "Model", "Modem", "Modification", "Module", "Molecule",
    "Monitor", "Monopoly", "Morbidity", "Mortgage", "Motif", "Motion", "Motive", "Movement", "Multiple", "Mutation",
    "Mutual", "Narcotic", "Narrative", "Native", "Natural", "Navigation", "Negligence", "Negotiation", "Network", "Neural",
    "Niche", "Node", "Noise", "Nonprofit", "Normal", "Nosocomial", "Note", "Notion", "Novation", "Novel",
    "Nucleus", "Object", "Obligation", "Observation", "Obstruction", "Occlusion", "Occupation", "Ode", "Offense", "Offer",
    "Oligopoly", "Ombudsman", "Omission", "Onset", "Opaque", "Operand", "Operation", "Operator", "Opinion", "Opportunity",
    "Opposition", "Option", "Orbit", "Order", "Ordinance", "Organic", "Organization", "Orientation", "Origin", "Ornament",
    "Oscillation", "Outbreak", "Outcome", "Outpost", "Output", "Overhead", "Overlap", "Oversight", "Overt", "Package",
    "Pact", "Pain", "Palliative", "Pandemic", "Panel", "Paper", "Paradigm", "Parameter", "Parasite", "Parity",
    "Parliament", "Partial", "Particle", "Partition", "Partner", "Pastoral", "Patent", "Pathogen", "Pathway", "Patient",
    "Pattern", "Peak", "Penalty", "Penetration", "Pension", "Percentile", "Perception", "Performance", "Perimeter", "Period",
    "Peripheral", "Permanent", "Permit", "Person", "Perspective", "Perturbation", "Pest", "Petition", "Phenotype", "Philosophy",
    "Phishing", "Photon", "Photosynthesis", "Physical", "Plaintiff", "Plane", "Plankton", "Plant", "Platform", "Plea",
    "Plot", "Plume", "Point", "Policy", "Portfolio", "Position", "Positive", "Post", "Postulate", "Potential",
    "Power", "Practice", "Precedent", "Precipitation", "Precision", "Predicate", "Prediction", "Premium", "Preparation", "Presence",
    "Presentation", "Pressure", "Presumption", "Prevalence", "Prevention", "Principal", "Principle", "Prior", "Probability", "Probe",
    "Procedure", "Process", "Procurement", "Product", "Profession", "Profile", "Profit", "Program", "Progression", "Project",
    "Proliferation", "Promise", "Promotion", "Proof", "Propaganda", "Property", "Prophylaxis", "Proposition", "Protocol", "Proton",
    "Proxy", "Psychology", "Public", "Pulse", "Purchase", "Pure", "Purpose", "Quality", "Quantification", "Quantum",
    "Queue", "Quorum", "Radiation", "Radius", "Raise", "Random", "Range", "Rank", "Rate", "Ratio",
    "Rational", "Reaction", "Read", "Real", "Reason", "Rebuttal", "Recession", "Recipe", "Reciprocal", "Recognition",
    "Recommendation", "Reconciliation", "Record", "Recovery", "Recursion", "Redemption", "Reduction", "Redundancy", "Reference", "Reflection",
    "Refraction", "Refrain", "Region", "Register", "Regression", "Regulation", "Rehabilitation", "Reinforcement", "Relation", "Release",
    "Relevance", "Relief", "Religion", "Remainder", "Remission", "Remote", "Render", "Repeal", "Replicate", "Report",
    "Repository", "Representation", "Reproduction", "Reputation", "Request", "Requirement", "Research", "Reservation", "Residence", "Resolution",
    "Resonance", "Resource", "Respect", "Response", "Rest", "Restraint", "Restriction", "Result", "Resurrection", "Retention",
    "Retina", "Retrieval", "Retroactive", "Return", "Revenue", "Reverse", "Review", "Revision", "Revival", "Revolution",
    "Reward", "Rhythm", "Risk", "Ritual", "Robust", "Role", "Roll", "Root", "Rotation", "Route",
    "Routine", "Rule", "Sample", "Sanction", "Saturation", "Scale", "Scenario", "Schema", "Scholarship", "Science",
    "Scope", "Screen", "Script", "Seal", "Search", "Section", "Sector", "Security", "Sediment", "Seed",
    "Segment", "Selection", "Self", "Semantic", "Seminal", "Senior", "Sensation", "Sense", "Sensitivity", "Sensor",
    "Sentence", "Separation", "Sequence", "Server", "Service", "Set", "Settlement", "Severity", "Share", "Shell",
    "Shift", "Short", "Signal", "Signature", "Significance", "Simulation", "Site", "Size", "Skill", "Slave",
    "Slot", "Smart", "Smooth", "Social", "Society", "Soft", "Software", "Soil", "Solution", "Sonnet",
    "Source", "Sovereign", "Space", "Span", "Spatial", "Species", "Specification", "Specimen", "Spectrum", "Speculation",
    "Speed", "Sphere", "Spike", "Spin", "Spirit", "Split", "Spoof", "Spot", "Spread", "Spring",
    "Spur", "Stack", "Stage", "Stake", "Standard", "Stanza", "Start", "State", "Statement", "Static",
    "Statute", "Stem", "Step", "Stimulus", "Stochastic", "Stock", "Storage", "Strain", "Strategy", "Stream",
    "Strength", "Stress", "Strike", "String", "Structure", "Study", "Style", "Subject", "Subpoena", "Substance",
    "Substrate", "Success", "Suffix", "Suit", "Summary", "Super", "Supply", "Support", "Surface", "Surge",
    "Surplus", "Survival", "Susceptible", "Suspension", "Sustained", "Switch", "Symbol", "Symptom", "Synchronization", "Syndrome",
    "Synonym", "Syntax", "Synthesis", "System", "Tactical", "Target", "Tariff", "Task", "Taste", "Tax",
    "Technique", "Technology", "Telemetry", "Template", "Tender", "Tension", "Term", "Terminal", "Terrain", "Territory",
    "Test", "Testate", "Text", "Theater", "Theme", "Theory", "Therapy", "Thermal", "Thesis", "Thick",
    "Thief", "Thin", "Thread", "Threat", "Threshold", "Thrust", "Ticket", "Tide", "Tier", "Time",
    "Tissue", "Title", "Token", "Tolerance", "Tone", "Tool", "Top", "Topic", "Topology", "Torque",
    "Tort", "Total", "Touch", "Toxic", "Trace", "Track", "Trade", "Tradition", "Trajectory", "Transaction",
    "Transcription", "Transfer", "Transformation", "Transient", "Transition", "Transmission", "Transport", "Trauma", "Treatment", "Treaty",
    "Trend", "Triage", "Trial", "Trigger", "Trust", "Tumor", "Tune", "Turn", "Type", "Ultimate",
    "Uncertainty", "Underlying", "Understanding", "Underwriting", "Uniform", "Union", "Unit", "Unity", "Universal", "Unsecured",
    "Upstream", "Urgent", "Usage", "Use", "User", "Utility", "Utilization", "Vacuum", "Valid", "Validation",
    "Value", "Valve", "Variable", "Variance", "Variation", "Vector", "Vehicle", "Velocity", "Vendor", "Venture",
    "Verdict", "Verification", "Version", "Vertex", "Vertical", "Vessel", "Veto", "Vibration", "View", "Violation",
    "Virtual", "Virus", "Viscosity", "Vision", "Visual", "Vital", "Vitamin", "Voice", "Void", "Volume",
    "Volunteer", "Vote", "Vulnerability", "Wage", "Warrant", "Wave", "Wavelength", "Weak", "Weapon", "Wear",
    "Web", "Weight", "Welfare", "Well", "Wet", "Wheel", "Width", "Will", "Win", "Window",
    "Wing", "Wire", "Wisdom", "Witness", "Word", "Work", "World", "Worm", "Worth", "Wound",
    "Write", "Yield", "Zone", "Zoonosis"
]

WordFamily = [
    "Act", "Air", "Back", "Band", "Board", "Book", "Break", "Card", "Case", "Cast",
    "Cede", "Cide", "Claim", "Cover", "Dict", "Draw", "Duct", "Eye", "Face", "Fer",
    "Field", "Fire", "Flect", "Foot", "Force", "Form", "Graph", "Gress", "Hand", "Head",
    "Heart", "Hold", "House", "Ject", "Land", "Letter", "Light", "Line", "Log", "Mark",
    "Meter", "Mind", "Mit", "Mitt", "Note", "Page", "Phone", "Place", "Plain", "Point",
    "Port", "Pose", "Press", "Roll", "Run", "Rupt", "Scope", "Sense", "Serve", "Set",
    "Ship", "Sign", "Sist", "Sound", "Spec", "Spect", "Stand", "State", "Struct", "Tend",
    "Test", "Time", "Tract", "Turn", "Vent", "Vert", "View"
]

WordIntensity = [
    "abhor", "abrasive", "absurd", "Abundant", "Accomplish", "accumulate", "Achieve", "acidic", "acrid", "active",
    "Adamantine", "Adept", "Adequate", "Adjourn", "adjust", "admire", "adore", "Advocate", "affluent", "afraid",
    "aged", "agitated", "agonizing", "Agree", "aid", "Aloof", "Altercate", "altruistic", "amass", "Ambiguous",
    "ambrosial", "Ample", "ancient", "angry", "annoyed", "antiquated", "anxious", "Apathetic", "Apodictic", "Appease",
    "apprehensive", "Arbitrary", "Arbitrate", "archaic", "arctic", "arduous", "Argue", "arid", "aromatic", "ascend",
    "Ashamed", "ask", "assemble", "Assent", "assist", "Assured", "astonished", "Astute", "attach", "Attain",
    "Attempt", "attractive", "audacious", "authentic", "Avant-garde", "average", "averse", "avid", "avoid", "Baffled",
    "balloon", "Baroque", "barren", "Beam", "beautiful", "beg", "begin", "bend", "benevolent", "Benighted",
    "bequeath", "beseech", "bestow", "Bigoted", "Billow", "bitter", "bland", "Blaze", "bleached", "Blemished",
    "blinding", "blistering", "Bloom", "Blossom", "Blunt", "bluster", "blustery", "Bob", "bogus", "boiling",
    "bold", "bolster", "bona fide", "bone-dry", "Bounce", "Bountiful", "brave", "Brazen", "break", "Breaker",
    "breeze", "Brief", "bright", "brilliant", "brimming", "brisk", "Brittle", "brutal", "build", "bulky",
    "bumpy", "Bungling", "Buoyant", "burdensome", "Burgeon", "bursting", "bustling", "busy", "Buzz", "Byzantine",
    "Cacophonous", "calm", "Candid", "Canny", "Capitulate", "Capricious", "Cataclysm", "cease", "Cerebrate", "certain",
    "Chafe", "Challenge", "challenging", "change", "cherish", "chilly", "chunky", "clean", "clear", "Clench",
    "Clever", "cloudy", "cloying", "clue", "Clumsy", "Clutch", "coarse", "Cogent", "Coherent", "cold",
    "collapse", "collect", "colorful", "Colorless", "colossal", "Combat", "Commanding", "commence", "common", "Compact",
    "compassionate", "Complex", "Complicated", "composed", "Comprehend", "compress", "Conciliate", "Concur", "condense", "Confident",
    "confiscate", "Conflagration", "Confront", "confused", "connect", "Conquer", "Consider", "considerate", "constrict", "construct",
    "Contemplate", "Contemporary", "content", "contort", "contract", "Contradict", "contribute", "Contrite", "Convoluted", "convulse",
    "cool", "Copious", "Coruscate", "counterfeit", "Countless", "courageous", "Courteous", "cowardly", "crack", "crammed",
    "craven", "Crawl", "Creep", "cripple", "critical", "crowded", "crucial", "cruel", "Crumbling", "Crumbly",
    "crushing", "crystal", "current", "curve", "Cynical", "damage", "damp", "dank", "daring", "dazzling",
    "deafening", "Debate", "debilitate", "Decayed", "Deceptive", "Declaim", "defect", "Defer", "Deferential", "Defiled",
    "deform", "Defy", "dehydrated", "Delay", "delectable", "Deliberate", "Delicate", "deluge", "Demure", "Dense",
    "Depict", "Depleted", "Depraved", "depressed", "Derelict", "descend", "Desecrated", "Desiccate", "desiccated", "desolate",
    "despise", "despondent", "destitute", "destroy", "Desultory", "Detached", "devastate", "devastated", "Devitalized", "devoid",
    "Differ", "difficult", "Dilapidated", "dim", "diminish", "dirty", "Disagree", "disappointed", "disband", "Discern",
    "disconnect", "discontinue", "Discordant", "Discourteous", "Discriminatory", "Discuss", "Dishonest", "disinclined", "disintegrate", "dislike",
    "Dispassionate", "disperse", "Disregard", "disseminate", "Dissent", "Dissonant", "distraught", "distribute", "disturbed", "divide",
    "Dominant", "donate", "Doodle", "Doubtful", "downpour", "Downy", "drab", "Drag", "drained", "Draw",
    "drenched", "Drift", "drizzle", "Drone", "Droop", "dry", "Dubious", "Ductile", "dull", "Duplicitous",
    "eager", "ear-splitting", "easy", "ecstatic", "Educated", "Effulge", "elated", "emaciated", "Embark", "Embellished",
    "Ember", "empty", "Endeavor", "Endorse", "Enduring", "engineer", "enormous", "enraged", "enthusiastic", "Ephemeral",
    "Equitable", "Equivocal", "erect", "Erudite", "Eternal", "Ethical", "Euphonic", "Evanescent", "even", "evidence",
    "Exasperated", "Excessive", "excruciating", "Exemplary", "exhausted", "expand", "Expert", "exquisite", "Extinct", "extravagant",
    "Extreme", "Exuberant", "fabricate", "faded", "Fail", "failing", "faint", "Fair", "fake", "fall",
    "Falter", "fast", "Fathom", "fatigued", "fault", "fearless", "Fecund", "feeble", "Fertile", "fervent",
    "fetid", "Few", "Fierce", "Fiery", "filthy", "fix", "Fixed", "flabbergasted", "Flame", "flat",
    "flatten", "flavorful", "flaw", "Flawless", "Fleeting", "Flexible", "Flood", "Florid", "Flounder", "Flourish",
    "Flow", "Fluffy", "Flummoxed", "Fog", "foggy", "foolish", "Forbearing", "forceful", "Forget", "formidable",
    "foul", "Founder", "fracture", "Fragile", "Fragment", "Fragmentary", "fragrant", "frail", "Frank", "frantic",
    "Fraudulent", "freezing", "frenetic", "frenzied", "fresh", "Fretful", "Friable", "frigid", "full", "Fumbling",
    "furious", "fuse", "Gainsay", "gale", "gale-force", "gather", "gaunt", "gaze", "genius", "gentle",
    "genuine", "gigantic", "give", "glance", "glare", "gleaming", "Glide", "Glimmer", "Glint", "Glisten",
    "Glitter", "gloomy", "glossy", "Glow", "glowing", "Glutted", "gorgeous", "grab", "Grain", "Grainy",
    "Grapple", "Grasp", "Grating", "Grip", "Gritty", "grow", "grueling", "Guilty", "gust", "gusty",
    "halt", "Haphazard", "happy", "harm", "Harmonious", "Harmonize", "hate", "Haul", "Haze", "hazy",
    "heavy", "hectic", "help", "helpless", "hesitant", "hint", "Hit", "hoard", "Hold", "Honest",
    "Hopeful", "horrified", "hot", "huge", "Hum", "humid", "hurricane", "hurt", "hysterical", "Idiotic",
    "Ignorant", "Ignore", "Illiterate", "Illogical", "Imbecilic", "Immaculate", "Immoral", "Immutable", "impair", "Impartial",
    "Impatient", "Impeccable", "Impel", "Impenetrable", "imperative", "Impertinent", "imperturbable", "implore", "Impolite", "important",
    "impossible", "impotent", "impoverished", "inane", "inaugurate", "Incandesce", "incandescent", "Incompetent", "Incomplete", "Inconsequential",
    "Indifferent", "indigent", "Inept", "Inequitable", "inevitable", "Infallible", "Inferno", "Infertile", "inflate", "infrequent",
    "Infuriated", "initiate", "injure", "innovative", "insipid", "Insist", "Insolent", "integrate", "Intense", "Intricate",
    "Inundation", "Irrational", "Irrefutable", "irritated", "isolate", "jagged", "jammed", "Jar", "Jarring", "Jiggle",
    "join", "Jolt", "Jostle", "joyful", "Just", "kaleidoscopic", "keen", "keep", "kind", "lackluster",
    "large", "Lasting", "launch", "lavish", "lean", "Learned", "leisurely", "Lettered", "level", "light",
    "lightning", "like", "likely", "limpid", "livid", "loaded", "loath", "loathe", "Logical", "Long-suffering",
    "look", "loud", "love", "lucid", "ludicrous", "Lugubrious", "lukewarm", "lustrous", "Luxuriant", "mad",
    "Maladroit", "malevolent", "Malleable", "malodorous", "manageable", "Many", "march", "Marginal", "Marred", "massive",
    "Masterly", "matte", "Meager", "mean", "Mediate", "Mediocre", "medium", "Mellifluous", "Melodic", "mend",
    "messy", "Methodical", "Meticulous", "miffed", "mighty", "mild", "Minimal", "minor", "Miscarry", "Misleading",
    "Mist", "moderate", "modern", "Modest", "modify", "moist", "Mollify", "Momentary", "Moral", "Morose",
    "move", "muggy", "Mummify", "murky", "murmur", "musty", "muted", "Mystified", "Naive", "nasty",
    "needy", "Nefarious", "Neglect", "Negligible", "Negotiate", "nervous", "new", "noisy", "Nominal", "nonexistent",
    "Nonsensical", "notable", "novel", "Numerous", "Obsequious", "obsolete", "Obtuse", "odorous", "offer", "ogled",
    "old", "Omit", "Omniscient", "opaque", "Oppose", "Optimistic", "opulent", "Orate", "Orderly", "ordinary",
    "Ornate", "overflowing", "overhaul", "Overlook", "Pacify", "packed", "painful", "Paint", "pale", "parched",
    "Partial", "Particle", "Passable", "Pat", "Patient", "pause", "peaceful", "Penetrate", "Penitent", "penniless",
    "perceptive", "Perennial", "Perfect", "Perfidious", "perfumed", "Perpetual", "Perplexed", "Persistent", "Perspicacious", "Pessimistic",
    "petrified", "philanthropic", "phony", "Piquant", "Placate", "placid", "plain", "plausible", "plead", "pleased",
    "Plethoric", "Pliable", "Pliant", "Plod", "plummet", "plunder", "plunge", "Plush", "Poised", "polish",
    "polished", "Polite", "Ponder", "poor", "possible", "Postpone", "powerless", "Precarious", "Precise", "Prejudiced",
    "preposterous", "preserve", "pretty", "Principled", "Pristine", "probable", "prodigious", "Productive", "Proficient", "Profuse",
    "proliferate", "Prolific", "proof", "Propel", "Propitiate", "Propose", "prudent", "Pull", "pulverize", "Pummel",
    "Punch", "pungent", "Push", "putrid", "puzzled", "quake", "Quarrel", "Questionable", "quick", "quiet",
    "radiant", "Radiate", "rain", "Ramshackle", "rancid", "Random", "rank", "rapid", "rare", "Ratify",
    "Rational", "raucous", "real", "Reasoned", "recent", "Recite", "Recommend", "Reconcile", "redolent", "Redundant",
    "refine", "regular", "rejuvenate", "relaxed", "Relent", "reluctant", "Remorseful", "Render", "renovate", "repair",
    "request", "Reserved", "Resigned", "Resist", "resistant", "Resonant", "Respectful", "Restive", "restore", "Reticent",
    "revolutionize", "rich", "Righteous", "Rigorous", "Ripple", "rise", "Roar", "robust", "Rococo", "rotten",
    "rough", "Rub", "Rude", "Rueful", "rugged", "ruin", "Ruinous", "Ruminate", "run", "Rush",
    "saccharine", "sad", "sadistic", "sagacious", "sage", "Saintly", "Sanction", "Sandy", "Sanguine", "saturated",
    "Saturnine", "savage", "save", "savory", "Scant", "scarce", "scared", "scatter", "scented", "Scholarly",
    "scorching", "scrumptious", "Secure", "seize", "Self-possessed", "separate", "serene", "sever", "Several", "severe",
    "shake", "Shaky", "sham", "Shard", "Sharp", "shatter", "Shelve", "Shine", "shiny", "shocked",
    "shout", "Shove", "shower", "Shrewd", "shrink", "Shrivel", "Shuffle", "shy", "sign", "Silky",
    "silly", "simple", "sink", "Sketch", "Skilled", "skinny", "skyrocket", "Slap", "slim", "slow",
    "Smack", "small", "smart", "smash", "smelly", "Smog", "smooth", "snatch", "soaked", "soar",
    "soft", "soggy", "Solid", "Some", "sore", "Sound", "soundless", "sour", "Spark", "Sparkle",
    "sparse", "speak", "Speck", "spent", "Spicy", "Splinter", "split", "Spotless", "sprinkle", "sprint",
    "spurious", "squalid", "Stable", "stale", "standard", "stare", "start", "startled", "Steady", "Steam",
    "Sterile", "still", "stockpile", "Stoic", "stop", "stride", "Strident", "Strike", "Strive", "Stroke",
    "stroll", "strong", "Struggle", "stuffed", "stunned", "Stupid", "sturdy", "subdued", "Submit", "Succeed",
    "Succumb", "Sufficient", "sugary", "Suggest", "Sullied", "Superfluous", "Supple", "support", "Surfeited", "surge",
    "surprised", "Surrender", "Suspend", "sustain", "swarming", "sweet", "swell", "swift", "Sycophantic", "Symphonic",
    "syrupy", "Systematic", "take", "talk", "Tap", "tarnished", "tart", "tasteless", "tasty", "teeming",
    "Teetering", "tender", "Tepid", "terminate", "terrified", "testament", "thick", "thin", "Thrive", "Thrust",
    "Thunder", "thunderous", "tidy", "timid", "timorous", "tiny", "tired", "Token", "Tolerable", "Tolerant",
    "torrent", "torturous", "Tottering", "Touch", "tough", "tower", "tranquil", "transform", "Transient", "translucent",
    "transmute", "transparent", "treacly", "tremble", "Triumph", "trivial", "troubled", "Trudge", "Truthful", "Tug",
    "turbid", "twist", "typical", "ubiquitous", "unappetizing", "Unassailable", "unavoidable", "Unbiased", "Uncertain", "uncommon",
    "Unconcerned", "Understand", "uneasy", "Unerring", "Unethical", "Unfair", "unflappable", "unify", "unimportant", "Uninformed",
    "Unjust", "unlikely", "Unscrupulous", "Unshakable", "Unsteady", "Unsullied", "Untarnished", "untidy", "Unversed", "Unyielding",
    "upset", "Urge", "usual", "vacant", "valid", "vapid", "Vapor", "Velvety", "veritable", "vibrant",
    "vibrate", "vice", "vicious", "vinegary", "Virginal", "Virtuoso", "Virtuous", "vital", "vivid", "void",
    "walk", "warm", "warp", "washed-out", "Wave", "weak", "weaken", "weakness", "wealthy", "weary",
    "wet", "Whimsical", "whisper", "whispered", "Wilt", "wind", "windy", "wise", "Wither", "Witless",
    "Wobbly", "worried", "worship", "Wrangle", "Wrench", "Wrestle", "Yank", "yell", "Yield", "zealous"
    "Zesty"
]

FieldSpecificMeaning = [
    "Abate", "Abatement", "Abject", "Abrogate", "Abscond", "Absentee voting", "Abstemious", "Acceleration", "Accession", "Accomplice",
    "Accountability", "Accreditation", "accrual", "Accusatorial", "acetylation", "Achievement", "Acid", "Acquittal", "Actionable", "actus reus",
    "Acumen", "Adhesion", "Adjudicate", "adjudication", "Administrator", "Admissibility", "Admissible", "Admonition", "Adocate", "Adroit",
    "Adumbrate", "Adverse", "Advocate", "Affable", "affidavit", "Agency", "Agenda setting", "Aggregate", "aggregation", "Alacrity",
    "algorithm", "Alibi", "alkane", "Allegation", "allele", "Alleviate", "Alloy", "Alternative dispute resolution", "Amalgam", "Ambiguous",
    "Ambivalent", "Ameliorate", "Amenable", "amicus", "Amicus Curiae", "amortization", "amplitude", "Anachronism", "analgesic", "Analogous",
    "analysis", "Anarchy", "Anathema", "Andragogy", "anesthesia", "Anion", "Annex", "Annul", "Annulment", "anomaly",
    "Antedecent", "Antipathy", "antiseptic", "Apathy", "Apex", "Apocryphal", "apoptosis", "appeal", "Appellant", "Appellee",
    "Applaud", "Appraisal", "Apprise", "Approbation", "Appropriate", "Appropriation", "arbitrage", "arbitration", "Arduous", "arithmetic",
    "Arraignment", "array", "Arrest", "Arson", "Artless", "Ascetic", "Assault", "Assessment", "asset", "Assiduous",
    "Assignee", "Assignment", "Assuage", "Atom", "atomicity", "Atrophy", "Attachment", "Attenuate", "Attorney", "Audacious",
    "Audit", "Auditory", "Austere", "Authentic", "Authority", "Automation", "Avarice", "Aver", "axiom", "bacterium",
    "Bail", "Bailiff", "bailment", "Ballot", "Banal", "Bankruptcy", "Bar", "basalt", "Base", "batch",
    "Battery", "Bayesian", "Behaviorism", "Belie", "Bench", "benchmark", "Benefactor", "Beneficiary", "Benevolent", "Benign",
    "Bequeath", "Bequest", "Berate", "Bilingual", "binary", "binomial", "biopsy", "Black propaganda", "Blandishment", "blockchain",
    "Bloom", "Bloom's", "Board of election inspectors", "Bolster", "Bombastic", "Bona Fide", "bond", "Boon", "Bovine", "branding",
    "Brazen", "Brief", "broadcast", "Budget", "buffer", "buoyancy", "Burden", "Bureaucracy", "Burgeon", "Burglary",
    "Burnish", "Buttress", "cache", "Cacophony", "Cadence", "Callous", "Calorie", "Calumny", "Campaign", "Candid",
    "Canon", "Canvassing", "capacitance", "capacitor", "Capacity", "Capital", "capitalization", "Capricious", "Carbohydrate", "cardinality",
    "cardiology", "Case", "Castigate", "catalysis", "catalyst", "catheter", "Cation", "Cause", "Caustic", "Cavort",
    "Cell", "Censure", "Centralization", "Certificate of candidacy", "Certification", "Certiorari", "Chain", "Challenge", "Chambers", "Charge",
    "Chastise", "Chattel", "checksum", "Chemical", "chiral", "chlorophyll", "chromatography", "chromosome", "churn", "Circuit",
    "Circuitous", "Citation", "Civil", "Civil society", "Claim", "Clairvoyant", "Clamor", "Class", "Classroom", "Clemency",
    "cluster", "Coalesce", "Coda", "Code", "Codicil", "Cogent", "Cognition", "Cognitive", "Cognitivism", "Collaborative",
    "Collateral", "combination", "Comity", "Commensurate", "Commission on elections", "commit", "Common", "comorbidity", "Compendium", "compiler",
    "Complacent", "Complaint", "Compliant", "Complicit", "Compound", "Comprehension", "compressive", "Compromise", "Conciliatory", "concurrency",
    "Concurrent", "Condemnation", "Condominium", "Condone", "conductivity", "Conductor", "Confession", "Conflict", "Confound", "Connoisseur",
    "conscientious", "conscientiousness", "Consensus", "Consideration", "consistency", "Conspiracy", "Constant", "Constituency", "Constructivism", "consumer",
    "container", "Contempt", "Contentious", "continuous", "Contract", "Contravention", "Contrite", "Controversy", "Contumacious", "Conundrum",
    "convection", "convergence", "conveyance", "Conviction", "Convoluted", "Cooperative", "Copyright", "Core", "corollary", "corpus",
    "Corpus Delicti", "Corroborate", "Corruption", "Counsel", "Counterclaim", "County", "coupon", "Course", "Court", "covariance",
    "Covenant", "Covet", "Craven", "Creative", "Credential", "Credulous", "Crescendo", "Crime", "Criminal", "criterion",
    "Critical", "Cross-examination", "Crust", "cryogenics", "cryptography", "Crystal", "Culpable", "current", "Curriculum", "cursor",
    "Custody", "Customs", "Cynic", "cytokinesis", "daemon", "Damages", "damping", "dataset", "Daunt", "De Facto",
    "Dearth", "Debacle", "Debate", "debugging", "Debunk", "Decedent", "Decentralization", "Decision", "Declaratory", "Decorum",
    "Decree", "Deed", "Defendant", "Defense", "Deference", "deflation", "Defunct", "degenerate", "Delegation", "Deleterious",
    "Delineate", "Delinquency", "Democracy", "Demur", "Demurrer", "Denigrate", "denormalization", "Density", "Deposition", "depreciation",
    "Deride", "derivative", "Descent", "Desiccate", "Desultory", "Detention", "Deter", "Developmental", "Devise", "Dialogue",
    "dialysis", "Diatribe", "Dichotomy", "Dictum", "Didactic", "dielectric", "Differentiated", "differentiation", "Diffident", "Diffraction",
    "diffusion", "Dilatory", "diode", "Disabuse", "Discerning", "Discipline", "Discordant", "Discovery", "Discredit", "discrete",
    "Disenfranchisement", "Disingenuous", "Dismissal", "Disparate", "Disposition", "Disqualification", "disruptive", "Dissemble", "Disseminate", "Dissent",
    "Distend", "Distrain", "distribution", "District", "Diverge", "divergence", "Diverse", "Divest", "dividend", "DNA",
    "DNS", "Docket", "Doctrinaire", "Dogmatic", "Domicile", "Dormant", "ductility", "due process", "durability", "Duress",
    "dynamics", "E-learning", "Earthquake", "easement", "EBITDA", "eccentric", "Eclectic", "Ecology", "Ecosystem", "Education",
    "Educator", "efficacy", "Effrontery", "Egregious", "eigenvalue", "Ejectment", "elasticity", "Election", "Electoral fraud", "Electrode",
    "Electron", "Elegy", "Element", "Elementary", "Elicit", "Embellish", "Embezzlement", "Eminent", "Empirical", "Empowerment",
    "Emulate", "enantiomer", "encapsulation", "encryption", "Encumbrance", "Endemic", "Endorsement", "endothermic", "endpoint", "Energy",
    "Enervate", "Engagement", "Engender", "engram", "Enjoin", "entanglement", "entrophy", "entropy", "enzyme", "Ephemeral",
    "epidemic", "epidemiology", "epigenetics", "Epistemology", "Equanimity", "Equation", "equilibrium", "equity", "Equivocal", "Erudite",
    "Escheat", "Esoteric", "Estate", "esterification", "estoppel", "Ethics", "eukaryote", "Eulogy", "Euphemism", "evaluate",
    "Evaluation", "evanescent", "eventuality", "Evidence", "Ex Parte", "Exacerbate", "exception", "Exculpate", "exculpatory", "Execution",
    "Executor", "Exemption", "Exigency", "exigent", "Exonerate", "exothermic", "Expedite", "Experiential", "Explicate", "explicit",
    "exponential", "export", "expression", "Expunge", "Extant", "extension", "Extol", "Extortion", "Extradition", "Extrajudicial",
    "Extraneous", "Extricate", "extroversion", "Exult", "Fabricate", "Facile", "Facilitation", "Facilitator", "Fallacious", "Fastidious",
    "Fatuous", "Fawn", "Federalism", "Feedback", "Felicitous", "Felony", "Fervent", "Fetter", "fiduciary", "field",
    "firewall", "Fixture", "Flag", "Flout", "Fluency", "flux", "Flying voters", "Foil", "Foment", "Force",
    "Forestall", "Forgery", "Forgo", "Formative", "Forsake", "Fortuitous", "Forum", "Fractious", "fragmentation", "framework",
    "Fraud", "Freedom of information", "frequency", "Friction", "Frivolous", "Frugal", "fundamental", "fungible", "funnel", "Gainsay",
    "Galaxy", "Garnishment", "Garrulous", "gateway", "Gauche", "gene", "Genial", "genome", "genotype", "geometric",
    "Germane", "Gerrymandering", "Gifted", "Glib", "governance", "Grade", "gradient", "Graduate", "Grand", "graph",
    "gravity", "Gregarious", "Grievance", "group", "Guarantee", "Guardian", "Guile", "habeas", "Habeas corpus", "Hackneyed",
    "handshake", "Hapless", "Harangue", "Harbinger", "harmonic", "Hearing", "hearsay", "Heat", "hedge", "Hedonism",
    "Heir", "Heresy", "heuristic", "Hiatus", "Hierarchy", "Higher", "Holistic", "Homework", "Homicide", "Homogeneous",
    "homomorphism", "Hormone", "horsepower", "hydrolysis", "Hyperbole", "Iconoclast", "Idolatry", "IEP", "Immunity", "Immunization",
    "immunology", "Immutable", "Impassive", "Impeachment", "Impecunious", "impedance", "Impede", "Impervious", "Impetuous", "Implacable",
    "Implementation", "Implicit", "Impugn", "Inadvertence", "Inadvertent", "Incentive", "Inchoate", "Inclusion", "Incongruous", "Incorrigible",
    "incriminate", "indemnity", "Independent", "index", "Indictment", "Indigence", "Individual", "Indolent", "induction", "inductor",
    "Inert", "inertia", "infallibility", "inflation", "Infraction", "Ingenuous", "Inherent", "inhibition", "Initiative", "injunction",
    "Innocent", "Innocuous", "innovation", "inoculation", "input", "inquisitive", "Insidious", "Insipid", "Instructional", "instructor",
    "Instrument", "Insular", "Insurance", "integral", "integrate", "Integration", "integrity", "intellect", "Intelligence", "intemperate",
    "Intent", "intention", "Interactive", "interceptor", "interdependence", "Interest group", "interface", "interlocutor", "intermediate", "Interpleader",
    "interpolation", "interpreter", "Interrogatories", "intersect", "intestate", "intimidate", "Intractable", "Intransigent", "Intrastate", "intravenous",
    "introspection", "intuition", "Inundate", "inure", "Inured", "Invective", "Investigation", "Inveterate", "inviolable", "Involuntary",
    "Ion", "Irascible", "irreducible", "irrelevant", "Irresolute", "isolation", "isomer", "isomorphism", "Isotope", "iteration",
    "Itinerant", "jeopardy", "join", "Joinder", "Judge", "Judgment", "Judicial", "judicious", "jurisdiction", "jurisprudence",
    "Jury", "Justice", "Juxtapose", "kernel", "Kidnapping", "kinematics", "Kinesthetic", "Kinetic", "Knowledge", "KPI",
    "kurtosis", "Laconic", "Lament", "Lampoon", "Languid", "Larceny", "latency", "latent", "Laud", "Lavish",
    "Law", "lawful", "Lawsuit", "Learner", "Learning", "Legacy", "Legatee", "Legislation", "lemma", "Lessee",
    "Lesson", "Lessor", "Lethargic", "Levee", "leverage", "Levity", "Levy", "liability", "Libel", "License",
    "Lien", "Light", "limit", "Line agency", "linearity", "lipid", "Liquid", "liquidity", "Listless", "Literacy",
    "lithosphere", "litigation", "Lobby", "Lobbying", "Local election", "Loquacious", "Lucid", "Luminous", "Magistrate", "Magnanimous",
    "Magnet", "magnetism", "Maintenance", "maladapted", "Malediction", "malefic", "Malevolent", "Malfeasance", "malicious", "Malleable",
    "malnourished", "Malpractice", "Mandamus", "mandate", "manifold", "Manslaughter", "margin", "marginal", "Maritime", "Markov",
    "Marshal", "martyrdom", "Mass", "Mass media", "Mastery", "matrix", "Matter", "Maverick", "maximum", "mean",
    "median", "Mediation", "meiosis", "mellifluous", "Mendacious", "mens rea", "Mercurial", "Metabolism", "metabolite", "Metacognition",
    "metadata", "Metal", "metamorphic", "metaphor", "methodical", "Methodology", "methylation", "Meticulous", "metric", "microorganism",
    "microservice", "Middle", "middleware", "migration", "minimize", "miscellaneous", "Misdemeanor", "Miserly", "misogyny", "Misprision",
    "Mistrial", "mistrust", "Mitigate", "Mitigation", "mitochondria", "mitosis", "mode", "model", "moderate", "modulation",
    "module", "modulus", "Molecule", "Mollify", "moment", "momentum", "Monitoring", "monochrome", "Montessori", "Moot",
    "morbid", "morbidity", "Morose", "mortality", "Mortgage", "Motion", "Motivation", "motive", "MTU", "Mudslinging",
    "multicast", "Multiple", "Mundane", "Murder", "mutation", "mutual", "Myopic", "Nadir", "namespace", "Nascent",
    "National election", "Nationalization", "naturalism", "nebula", "Nebulous", "Nefarious", "negligence", "Negligible", "Negotiable", "Negotiation",
    "neologism", "nephrology", "Nepotism", "neurology", "neuropathy", "neutral", "Neutron", "niche", "nil", "Nolo",
    "nomenclature", "Non-governmental organization", "nonce", "normalization", "Notary", "Notice", "Noxious", "nucleotide", "Nucleus", "Nuisance",
    "nullspace", "numerator", "nuptial", "Oath", "Obdurate", "obedience", "Obfuscate", "Objection", "Objective", "objectivity",
    "Obligation", "Oblique", "obnoxious", "obscure", "Obsequious", "observatory", "Obstruction", "Obtuse", "occasion", "occupant",
    "Of counsel", "Offer", "Officious", "Ombudsman", "omniscient", "onboarding", "oncology", "Onerous", "Online", "ontology",
    "Opaque", "operable", "Opinion", "Opprobrium", "optimal", "Option", "optionality", "Orbit", "orchestration", "ordinal",
    "Ordinance", "organelle", "organic", "Organism", "orientation", "Original", "oscillation", "osmotic", "Ostentatious", "output",
    "Overt", "oxidation", "oxidative", "oxygenation", "packet", "Panacea", "pandemic", "paradigm", "Paradox", "Paragon",
    "parameter", "Pardon", "parity", "parochial", "Parole", "parse", "Parsimony", "participant", "Participation", "Particle",
    "Partisan", "partition", "Party", "Party-list", "passivity", "pastoral", "patch", "Patent", "pathogen", "pathogenesis",
    "Pathological", "pathology", "patriarchy", "pattern", "Paucity", "pecuniary", "pedagogical", "Pedagogy", "Pedantic", "penalty",
    "Penchant", "penetration", "penumbra", "Penurious", "People's organization", "peptide", "Per curiam", "percentile", "perceptron", "Perennial",
    "perfect", "Perfidious", "Performance", "Perfunctory", "perilous", "perimeter", "Perjury", "Permeate", "Permit", "permutation",
    "perpetrator", "perpetuity", "perquisite", "persecution", "perseverance", "persistent", "Personal", "personality", "perspiration", "perturbation",
    "Pervasive", "Petition", "pH", "phantasm", "Phase", "phenomenology", "phenotype", "Philosophy", "Phlegmatic", "Phonetics",
    "phosphorylation", "Photon", "photonic", "photonics", "Photosynthesis", "photovoltaic", "phrenology", "phylogeny", "physical", "physics",
    "physiology", "Piety", "pinnacle", "pipeline", "pivot", "Placate", "placebo", "plagiarism", "Plaintiff", "Planet",
    "Planning", "plasmid", "Plastic", "plasticity", "platform", "Platitude", "Plea", "Pleading", "Plebiscite", "Plethora",
    "Pliable", "plugin", "plume", "pluralism", "pneumatic", "Poignant", "pointer", "polarity", "polarization", "Polemical",
    "Police", "policy", "Policy analysis", "Policy cycle", "Policy evaluation", "Policy implementation", "Policy making", "political", "polymer", "polymerization",
    "Polynomial", "polysemous", "portfolio", "positioning", "positive", "possibility", "postulate", "potential", "Power", "practical",
    "Practice", "Pragmatic", "Precarious", "precedent", "Precept", "Precinct", "Precipitate", "Preclude", "Precocious", "predicate",
    "prediction", "Predilection", "predisposition", "Preempt", "Preemption", "prelude", "Premeditation", "Preponderance", "Preschool", "Prescient",
    "presence", "Presentment", "Pressure", "Pressure group", "Presumption", "pretext", "prevalence", "Prevaricate", "preventive", "Prima facie",
    "primal", "Primary", "primate", "Principal", "principle", "prioritize", "prism", "Pristine", "Privacy", "Privatization",
    "Privilege", "probability", "probate", "Probation", "Probity", "Problem", "procedure", "Process", "Proclamation", "Proclivity",
    "Procurement", "Prodigal", "produce", "Product", "productivity", "Profane", "Professional", "Proficiency", "profile", "profit",
    "Profligate", "prognosis", "Program", "progress", "Progressive", "Prohibition", "Project", "projection", "prokaryote", "Proliferate",
    "prologue", "prolusion", "Promissory", "Propaganda", "Propensity", "Property", "Propitiate", "Proportional representation", "proprietary", "Propriety",
    "Prosaic", "Prosecution", "prosperity", "protagonist", "Protean", "Protein", "proteome", "protocol", "Proton", "protracted",
    "provenance", "proverbial", "Proximate", "proximity", "proxy", "Prudence", "Psychology", "Public", "Public corporation", "Public opinion",
    "Public policy", "Puerile", "Pugnacious", "pulsar", "Punctilious", "Punitive", "purgative", "purification", "pyrolysis", "quackery",
    "quagmire", "quaint", "Qualification", "quantile", "quantitative", "quantization", "quantum", "Quark", "quartile", "quasar",
    "Quash", "Quell", "Querulous", "query", "Question", "queue", "quiescent", "Quiet", "quintessential", "Quixotic",
    "Quo warranto", "Quorum", "quotient", "radial", "radiance", "Radiation", "radical", "radioactive", "radiography", "radius",
    "Rally", "Rancor", "random", "range", "rank", "Rapacious", "Rape", "rate", "ratio", "rationale",
    "rationalism", "rationality", "Reaction", "Readiness", "Reading", "Real", "realism", "reality", "realm", "Reasonable",
    "Reasoning", "Rebuttal", "Recalcitrant", "Recall", "Recall election", "Recant", "receipt", "receptive", "reciprocal", "recitation",
    "reckoning", "reclamation", "recognition", "Recognizance", "Recondite", "reconnaissance", "reconstruct", "record", "recount", "recover",
    "Recovery", "recreate", "Rectitude", "recursion", "Recusal", "Red tape", "redeem", "redirect", "Redoubtable", "reduction",
    "redundancy", "reeducation", "refactor", "referee", "reference", "Referendum", "refinement", "Reflection", "reform", "Reformation",
    "refract", "refraction", "refresh", "refuge", "refutation", "Refute", "regard", "regeneration", "Registration", "registry",
    "regression", "regularity", "regulate", "Regulation", "rehabilitate", "Rehearing", "rehearse", "reification", "Reinforcement", "reiterate",
    "reject", "relativity", "Release", "Relegate", "reluctant", "remainder", "Remand", "remarkable", "remedial", "remediation",
    "Remiss", "remittance", "remorse", "render", "renege", "renounce", "renovate", "renunciation", "reorder", "reorganization",
    "reorientation", "reparation", "repatriate", "repay", "repel", "repent", "repercussion", "repertoire", "repetition", "replace",
    "Replete", "Replevin", "replica", "replication", "reply", "Report", "repose", "repository", "Representation", "Reprieve",
    "reprimand", "Reproach", "Reprobate", "reproduce", "reproof", "reproval", "Repudiate", "repugnance", "repulsion", "reputation",
    "request", "requirement", "Res", "Rescind", "Rescission", "rescue", "research", "resemblance", "resent", "reservation",
    "reserve", "reside", "residual", "resignation", "resilience", "resin", "resist", "Resistance", "resistor", "Resolution",
    "resolve", "resonance", "Resource", "respect", "Respiration", "Respite", "Respondent", "response", "responsibility", "responsive",
    "restatement", "Restitution", "restoration", "restrict", "restriction", "Restrictive", "resultant", "resume", "resumption", "resurgence",
    "resurrect", "resuscitate", "Retainer", "retaliate", "retard", "retention", "retribution", "retroactive", "retrograde", "retrospective",
    "return", "reunification", "revalidate", "revaluation", "reveal", "revelation", "revenge", "Revenue", "reverberate", "reverence",
    "Reverent", "reverse", "reversion", "revert", "Review", "revise", "revision", "revival", "revive", "Revocation",
    "revoke", "revolution", "revolve", "reward", "Rhetoric", "rheumatology", "rhythm", "riddle", "ridge", "Rife",
    "Right to know", "rightful", "rigor", "ring", "ritual", "RNA", "Robbery", "robust", "ROI", "rollback",
    "romantic", "root", "rotation", "roughness", "round", "route", "router", "routine", "rubble", "Rubric",
    "rudiment", "rugged", "Rule", "rumination", "runtime", "rupture", "ruse", "sacrifice", "safeguard", "Sagacious",
    "salience", "Salient", "saliva", "Salt", "Sanction", "sanctity", "sanitation", "sarcasm", "satellite", "Satiate",
    "satisfaction", "Saturate", "saturated", "saturation", "savage", "savvy", "scaffold", "Scaffolding", "scalability", "scale",
    "scan", "scarcity", "scenario", "schedule", "schema", "scheme", "schism", "scholar", "scholarship", "School",
    "Science", "scientific", "scope", "score", "scorn", "scramble", "Scrupulous", "scrutiny", "seal", "Search",
    "seasonal", "Secondary", "secret", "section", "sector", "secure", "Security", "sediment", "sedimentary", "Sedulous",
    "segmentation", "Seizure", "Self", "semantic", "semaphore", "semblance", "semester", "semiconductor", "Seminal", "Seminar",
    "semiotic", "sensation", "sense", "sensible", "sensitivity", "sensor", "Sensory", "Sentence", "sentiment", "separate",
    "separation", "sequence", "serial", "serialization", "series", "sermon", "Service", "Servile", "session", "setback",
    "setting", "Settlement", "severity", "shadow", "shame", "shape", "sharding", "share", "sharpness", "sheet",
    "shelter", "Sheriff", "shift", "shimmer", "shock", "shortage", "shortcoming", "shoulder", "shrink", "shroud",
    "shuffle", "shyness", "signal", "signature", "significance", "signify", "silence", "similarity", "simplify", "simulation",
    "simultaneous", "sincere", "singularity", "sink", "situate", "situation", "size", "skeleton", "skeptic", "skewness",
    "Skill", "skirmish", "skyline", "slant", "slight", "slope", "sluggish", "slyness", "smartness", "smile",
    "smog", "smoothness", "snap", "Social", "society", "socket", "softness", "solar", "solemn", "Solicitor",
    "Solicitous", "solid", "solidity", "solitary", "solitude", "Solution", "solvency", "solvent", "sombre", "song",
    "soothe", "sophisticate", "Soporific", "sorrow", "sort", "Sortie", "soul", "soundness", "source", "sovereign",
    "Sovereignty", "space", "span", "Span of control", "sparseness", "speak", "spec", "Special", "specialist", "specialize",
    "specialty", "Species", "Specific", "specification", "specify", "specimen", "Specious", "spectacle", "spectral", "spectrometer",
    "spectrometry", "spectroscopy", "spectrum", "speculate", "speech", "Speed", "spell", "spend", "sphere", "spinal",
    "spine", "spiral", "spirit", "spiritual", "spleen", "split", "spoil", "sponsor", "spontaneity", "spontaneous",
    "Sporadic", "sport", "spot", "spotlight", "spread", "spring", "spur", "Spurious", "Squalid", "squander",
    "square", "SSH", "SSL", "stable", "stack", "staff", "Staff agency", "stage", "stagnant", "Staid",
    "stair", "stakeholder", "Stakeholders", "stamina", "Standard", "standardize", "Standardized", "standby", "Standing", "staple",
    "stare", "startle", "starvation", "state", "statement", "static", "statics", "station", "Statistics", "status",
    "Statute", "stay", "steadiness", "stealth", "steep", "stellar", "stem", "stencil", "stent", "step",
    "stereotype", "steroid", "stickiness", "stimulate", "stimulation", "Stimulus", "stint", "stipulate", "Stipulation", "stochastic",
    "stock", "stoichiometry", "Stolid", "stomach", "stone", "stool", "stoop", "stopwatch", "storage", "store",
    "stout", "strain", "Strategy", "stream", "strength", "stress", "stretch", "Striated", "stride", "strife",
    "strike", "stringency", "strip", "stripe", "strive", "stroke", "structure", "struggle", "Student", "Study",
    "stuff", "stumble", "Stupefy", "stupor", "sturdy", "style", "subclass", "subcommittee", "subdue", "subject",
    "Subjugate", "sublimation", "Subliminal", "submarine", "submerge", "submission", "submit", "subnet", "subordinate", "Subornation",
    "subparagraph", "subpoena", "subscribe", "subscript", "subsection", "subset", "subsidiary", "subsidy", "subsistence", "substance",
    "substantial", "Substantiate", "substitute", "subsystem", "subtlety", "subtract", "subtype", "subunit", "suburb", "subversion",
    "Subvert", "succeed", "success", "Succession", "successor", "Succinct", "succumb", "suction", "suddenness", "suffer",
    "suffice", "suffix", "suffocate", "Suffrage", "sugar", "suggest", "suggestion", "suicide", "suitability", "suitable",
    "suitcase", "suite", "summarize", "Summary", "Summative", "summer", "summit", "summon", "summons", "sumptuous",
    "sunlight", "superb", "superficial", "Superfluous", "superiority", "superlative", "supernova", "superposition", "Supervision", "supervisor",
    "supplement", "supplementary", "supplicate", "supply", "support", "supportive", "suppose", "supposition", "suppress", "suppressor",
    "supremacy", "supreme", "surcharge", "Surety", "surface", "Surfeit", "surge", "surmise", "surpass", "surplus",
    "surreal", "Surrender", "Surreptitious", "surrogate", "surround", "survey", "susceptibility", "susceptible", "Suspended", "suspense",
    "suspension", "sustain", "sustainability", "sustainable", "Sustained", "Sustaining", "swamp", "swap", "swarm", "sway",
    "swear", "sweep", "swell", "swift", "swing", "switch", "SWOT", "Sycophant", "syllabus", "syllogism",
    "symbol", "symbolic", "symbolism", "symmetry", "sympathetic", "sympathy", "symphony", "symptom", "synchronize", "syndrome",
    "synergy", "synonym", "synopsis", "syntactic", "syntax", "synthesis", "synthesize", "synthetic", "system", "systematic",
    "systemic", "Taciturn", "Tangential", "Tariff", "Taxation", "taxon", "TCP", "Teacher", "Teaching", "Technique",
    "Technology", "Temperance", "Temperature", "Tenacious", "tensile", "tensor", "Terse", "Testament", "Testimony", "Testing",
    "Theft", "theorem", "Theory", "thermodynamics", "Thinking", "thread", "threshold", "throughput", "Timorous", "Tissue",
    "Title", "titration", "TLS", "token", "tomography", "topology", "Torpor", "torque", "tort", "Totalitarianism",
    "Tractable", "Trademark", "Training", "transaction", "Transcript", "transcriptome", "Transient", "transistor", "translation", "Transmute",
    "Transparency", "Trenchant", "Trepidation", "Trespass", "Trial", "Truculent", "Trust", "tuple", "Turpitude", "Tutoring",
    "Ubiquitous", "UDP", "Umbrage", "Unassailable", "Unctuous", "Understanding", "Undue", "unicast", "Uniform", "Uninsured",
    "Unit", "United", "University", "Untenable", "vaccine", "Vacillate", "Validation", "Valuation", "variance", "vector",
    "vectorization", "velocity", "Venerate", "Venue", "Verbose", "Verdant", "verdict", "Vex", "Viable", "Vicarious",
    "Victim", "view", "Vilify", "Violation", "virtualization", "Virtuoso", "viscosity", "Viscous", "Visual", "Vitiate",
    "Vituperate", "VLAN", "Void", "Volatile", "volatility", "voltage", "Voracious", "Vote-buying", "Vygotsky", "Waiver",
    "warrant", "Warranted", "Wave", "wavefunction", "wavelength", "Welter", "Whimsical", "Whistleblower", "White propaganda", "Will",
    "Witness", "Writ", "Writing", "yield", "Zealous", "Zone", "Zoning", "ZPD", "Zygote"
]
