INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Averages', 'Calculating the mean', 'Find the mean of the given data.', 'The scores are 10, 15, 20, 25, 30. What is the mean?', '20', '18', '22', '19', 'Sum = 100. Mean = 100 ÷ 5 = 20.'),
('Arithmetic Fundamentals', 'Averages', 'Finding the median (odd set)', 'Find the median.', 'Find the median of 5, 8, 12, 15, 20.', '12', '10', '13', '14', 'Odd set → middle value after ordering is 12.'),
('Arithmetic Fundamentals', 'Averages', 'Finding the median (even set)', 'Find the median.', 'Find the median of 6, 8, 10, 12.', '9', '8', '10', '11', 'Even set → average of middle two values (8+10)/2 = 9.'),
('Arithmetic Fundamentals', 'Averages', 'Identifying the mode', 'Find the mode.', 'What is the mode of 2, 4, 4, 6, 7, 7, 7, 8?', '7', '4', '6', 'No mode', '7 appears most frequently (3 times).'),
('Arithmetic Fundamentals', 'Averages', 'Calculating the range', 'Find the range.', 'The ages are 18, 25, 29, 34, 40. What is the range?', '22', '21', '20', '23', 'Range = max − min = 40 − 18 = 22.'),
('Arithmetic Fundamentals', 'Averages', 'Word problem involving mean', 'Solve the problem.', 'The mean score of 4 tests is 75. If 3 test scores are 70, 80, and 72, what is the 4th score?', '78', '76', '74', '80', 'Total score = 75 × 4 = 300. Sum of 3 scores = 222. 300 − 222 = 78.'),
('Arithmetic Fundamentals', 'Averages', 'Finding a missing value with given mean', 'Find the missing number.', 'The mean of 6 numbers is 10. Five numbers are 8, 9, 12, 11, and 7. What is the missing number?', '13', '12', '14', '11', 'Total sum = 6×10=60. Known sum = 47. Missing = 60 − 47 = 13.'),
('Arithmetic Fundamentals', 'Averages', 'Calculating weighted averages', 'Find the weighted average.', 'A student scores 80 in Math (weight 3), 70 in Science (weight 2), and 90 in English (weight 1). What is the weighted average?', '80', '82', '78', '79', 'Weighted sum = (80×3)+(70×2)+(90×1) = 240+140+90 = 470. Total weight = 6. Weighted average = 470 ÷ 6 ≈ 80.'),
('Arithmetic Fundamentals', 'Averages', 'Applying averages in real-life scenarios', 'Solve the real-life problem.', 'A batsman scores 50, 70, and 80 runs in 3 matches. What is his batting average?', '66.67', '70', '65', '68', 'Average = (50+70+80) ÷ 3 = 200 ÷ 3 ≈ 66.67.'),
('Arithmetic Fundamentals', 'Averages', 'Comparing averages', 'Compare and interpret averages.', 'Class A has a mean score of 75 (30 students), Class B has a mean score of 80 (20 students). Which class performed better overall?', 'Class B', 'Class A', 'Equal', 'Cannot be determined', 'Mean score is higher for Class B (80 > 75), so on average they performed better.');
