-- Addition of fractions 
INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES 
('Arithmetic Fundamentals', 'Fractions', 'Addition of fractions', 'Add the given fractions.', 'What is \\( \\frac{1}{4} + \\frac{2}{4} \\)?', '\\( \\frac{3}{4} \\)', '\\( \\frac{3}{8} \\)', '\\( \\frac{1}{2} \\)', '\\( \\frac{2}{4} \\)', 'Add numerators: 1 + 2 = 3. Keep denominator 4: \\( \\frac{3}{4} \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Addition of fractions', 'Add the given fractions.', 'What is \\( \\frac{1}{3} + \\frac{1}{6} \\)?', '\\( \\frac{1}{2} \\)', '\\( \\frac{2}{9} \\)', '\\( \\frac{1}{9} \\)', '\\( \\frac{2}{6} \\)', 'Common denominator is 6: \\( \\frac{1}{3} = \\frac{2}{6} \\). Then \\( \\frac{2}{6} + \\frac{1}{6} = \\frac{3}{6} = \\frac{1}{2} \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Addition of fractions', 'Add the given fractions.', 'What is \\( \\frac{3}{5} + \\frac{1}{5} \\)?', '\\( \\frac{4}{5} \\)', '\\( \\frac{4}{10} \\)', '\\( \\frac{3}{10} \\)', '\\( \\frac{2}{5} \\)', 'Add numerators: 3 + 1 = 4. Keep denominator 5: \\( \\frac{4}{5} \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Addition of fractions', 'Add the given fractions.', 'What is \\( \\frac{2}{3} + \\frac{1}{4} \\)?', '\\( \\frac{11}{12} \\)', '\\( \\frac{3}{7} \\)', '\\( \\frac{3}{12} \\)', '\\( \\frac{8}{12} \\)', 'Common denominator is 12: \\( \\frac{2}{3} = \\frac{8}{12} \\), \\( \\frac{1}{4} = \\frac{3}{12} \\). Then \\( \\frac{8}{12} + \\frac{3}{12} = \\frac{11}{12} \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Addition of fractions', 'Add the given fractions.', 'What is \\( 1\\frac{1}{2} + \\frac{3}{4} \\)?', '\\( 2\\frac{1}{4} \\)', '\\( 1\\frac{4}{6} \\)', '\\( 2\\frac{2}{3} \\)', '\\( 1\\frac{3}{4} \\)', 'Convert to improper: \\( 1\\frac{1}{2} = \\frac{3}{2} = \\frac{6}{4} \\). Add: \\( \\frac{6}{4} + \\frac{3}{4} = \\frac{9}{4} = 2\\frac{1}{4} \\).');

-- Subtraction of fractions
INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Fractions', 'Subtraction of fractions', 'Subtract the given fractions.', '\\( \\frac{3}{4} - \\frac{1}{4} \\)', '\\( 1\\frac{1}{2} \\)', '\\( 1\\frac{2}{4} \\)', '\\( 1\\frac{1}{4} \\)', '\\( 1\\frac{3}{8} \\)', 'Subtract numerators: \\( \\frac{3}{4} - \\frac{1}{4} = \\frac{2}{4} = \\frac{1}{2} \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Subtraction of fractions', 'Subtract the given fractions.', '\\( \\frac{5}{6} - \\frac{1}{3} \\)', '\\( 1\\frac{1}{2} \\)', '\\( 1\\frac{2}{6} \\)', '\\( 1\\frac{4}{6} \\)', '\\( 1\\frac{1}{3} \\)', 'Common denominator is 6: \\( \\frac{5}{6} - \\frac{2}{6} = \\frac{3}{6} = \\frac{1}{2} \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Subtraction of fractions', 'Subtract the given fractions.', '\\( \\frac{7}{8} - \\frac{3}{8} \\)', '\\( 1\\frac{1}{2} \\)', '\\( 1\\frac{4}{8} \\)', '\\( 1\\frac{3}{4} \\)', '\\( 1\\frac{1}{4} \\)', 'Subtract numerators: \\( \\frac{7}{8} - \\frac{3}{8} = \\frac{4}{8} = \\frac{1}{2} \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Subtraction of fractions', 'Subtract the given fractions.', '\\( \\frac{9}{10} - \\frac{2}{5} \\)', '\\( 1\\frac{1}{2} \\)', '\\( 1\\frac{7}{10} \\)', '\\( 1\\frac{3}{10} \\)', '\\( 1\\frac{2}{10} \\)', 'Common denominator is 10: \\( \\frac{9}{10} - \\frac{4}{10} = \\frac{5}{10} = \\frac{1}{2} \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Subtraction of fractions', 'Subtract the given fractions.', '\\( \\frac{3}{5} - \\frac{1}{10} \\)', '\\( 1\\frac{1}{2} \\)', '\\( 1\\frac{2}{5} \\)', '\\( 1\\frac{4}{5} \\)', '\\( 1\\frac{1}{5} \\)', 'Common denominator is 10: \\( \\frac{6}{10} - \\frac{1}{10} = \\frac{5}{10} = \\frac{1}{2} \\).');

-- Multiplication of fractions
INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Fractions', 'Multiplication of fractions', 'Multiply the given fractions.', '\\( \\frac{2}{3} \\times \\frac{3}{4} \\)', '\\( 1\\frac{1}{2} \\)', '\\( 1\\frac{5}{12} \\)', '\\( 1\\frac{2}{7} \\)', '\\( 1\\frac{3}{5} \\)', 'Multiply numerators and denominators: \\( \\frac{2}{3} \\times \\frac{3}{4} = \\frac{6}{12} = \\frac{1}{2} \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Multiplication of fractions', 'Multiply the given fractions.', '\\( \\frac{5}{6} \\times \\frac{2}{5} \\)', '\\( 1\\frac{1}{3} \\)', '\\( 1\\frac{7}{11} \\)', '\\( 1\\frac{3}{5} \\)', '\\( 1\\frac{2}{6} \\)', 'Multiply numerators and denominators: \\( \\frac{5}{6} \\times \\frac{2}{5} = \\frac{10}{30} = \\frac{1}{3} \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Multiplication of fractions', 'Multiply the given fractions.', '\\( \\frac{3}{4} \\times \\frac{1}{2} \\)', '\\( 1\\frac{3}{8} \\)', '\\( 1\\frac{1}{4} \\)', '\\( 1\\frac{2}{8} \\)', '\\( 1\\frac{1}{2} \\)', 'Multiply numerators and denominators: \\( \\frac{3}{4} \\times \\frac{1}{2} = \\frac{3}{8} \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Multiplication of fractions', 'Multiply the given fractions.', '\\( \\frac{7}{10} \\times \\frac{5}{7} \\)', '\\( 1\\frac{1}{2} \\)', '\\( 1\\frac{2}{5} \\)', '\\( 1\\frac{5}{10} \\)', '\\( 1\\frac{7}{12} \\)', 'Multiply numerators and denominators: \\( \\frac{7}{10} \\times \\frac{5}{7} = \\frac{35}{70} = \\frac{1}{2} \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Multiplication of fractions', 'Multiply the given fractions.', '\\( \\frac{4}{9} \\times \\frac{3}{8} \\)', '\\( 1\\frac{1}{6} \\)', '\\( 1\\frac{7}{24} \\)', '\\( 1\\frac{1}{3} \\)', '\\( 1\\frac{2}{9} \\)', 'Multiply numerators and denominators: \\( \\frac{4}{9} \\times \\frac{3}{8} = \\frac{12}{72} = \\frac{1}{6} \\).');

-- Division of fractions
INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Fractions', 'Division of fractions', 'Divide the given fractions.', '\\( \\frac{2}{3} \\div \\frac{4}{5} \\)', '\\(\\frac{5}{6} \\)', '\\(\\frac{1}{2} \\)', '\\(\\frac{3}{7} \\)', '\\(\\frac{2}{5} \\)', 'Invert the second fraction and multiply: \\( \\frac{2}{3} \\div \\frac{4}{5} = \\frac{2}{3} \\times \\frac{5}{4} = \\frac{10}{12} = \\frac{5}{6} \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Division of fractions', 'Divide the given fractions.', '\\( \\frac{5}{6} \\div \\frac{2}{3} \\)', '\\(\\frac{5}{4} \\)', '\\(\\frac{3}{4} \\)', '\\(\\frac{1}{2} \\)', '\\(\\frac{2}{5} \\)', 'Invert the second fraction and multiply: \\( \\frac{5}{6} \\div \\frac{2}{3} = \\frac{5}{6} \\times \\frac{3}{2} = \\frac{15}{12} = \\frac{5}{4} \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Division of fractions', 'Divide the given fractions.', '\\( \\frac{3}{4} \\div \\frac{1}{2} \\)', '\\(\\frac{3}{2} \\)', '\\(\\frac{1}{2} \\)', '\\(\\frac{1}{4} \\)', '\\(\\frac{2}{3} \\)', 'Invert the second fraction and multiply: \\( \\frac{3}{4} \\div \\frac{1}{2} = \\frac{3}{4} \\times \\frac{2}{1} = \\frac{6}{4} = \\frac{3}{2} \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Division of fractions', 'Divide the given fractions.', '\\( \\frac{7}{8} \\div \\frac{7}{10} \\)', '\\(\\frac{10}{8} \\)', '\\(\\frac{7}{18} \\)', '\\(\\frac{1}{2} \\)', '\\(\\frac{7}{16} \\)', 'Invert the second fraction and multiply: \\( \\frac{7}{8} \\div \\frac{7}{10} = \\frac{7}{8} \\times \\frac{10}{7} = \\frac{70}{56} = \\frac{10}{8} \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Division of fractions', 'Divide the given fractions.', '\\( \\frac{4}{9} \\div \\frac{2}{3} \\)', '\\(\\frac{2}{3} \\)', '\\(\\frac{3}{4} \\)', '\\(\\frac{1}{6} \\)', '\\(\\frac{1}{3} \\)', 'Invert the second fraction and multiply: \\( \\frac{4}{9} \\div \\frac{2}{3} = \\frac{4}{9} \\times \\frac{3}{2} = \\frac{12}{18} = \\frac{2}{3} \\).');

-- Converting improper fractions to mixed numbers
INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Fractions', 'Improper fractions to mixed numbers', 'Converting improper fractions to mixed numbers', '\\( \\frac{7}{4} \\)', '\\( 1\\frac{3}{4} \\)', '\\( 1\\frac{2}{4} \\)', '\\( 2\\frac{1}{4} \\)', '\\( 1\\frac{1}{2} \\)', 'Divide numerator by denominator: \\( 7 \\div 4 = 1 \\) remainder \\( 3 \\). So, \\( \\frac{7}{4} = 1\\frac{3}{4} \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Improper fractions to mixed numbers', 'Converting improper fractions to mixed numbers', '\\( \\frac{9}{5} \\)', '\\( 1\\frac{4}{5} \\)', '\\( 1\\frac{3}{5} \\)', '\\( 2\\frac{1}{5} \\)', '\\( 1\\frac{1}{5} \\)', 'Divide numerator by denominator: \\( 9 \\div 5 = 1 \\) remainder \\( 4 \\). So, \\( \\frac{9}{5} = 1\\frac{4}{5} \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Improper fractions to mixed numbers', 'Converting improper fractions to mixed numbers', '\\( \\frac{11}{6} \\)', '\\( 1\\frac{5}{6} \\)', '\\( 1\\frac{4}{6} \\)', '\\( 2\\frac{1}{6} \\)', '\\( 1\\frac{1}{6} \\)', 'Divide numerator by denominator: \\( 11 \\div 6 = 1 \\) remainder \\( 5 \\). So, \\( \\frac{11}{6} = 1\\frac{5}{6} \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Improper fractions to mixed numbers', 'Converting improper fractions to mixed numbers', '\\( \\frac{14}{3} \\)', '\\( 4\\frac{2}{3} \\)', '\\( 4\\frac{1}{3} \\)', '\\( 5\\frac{1}{3} \\)', '\\( 4\\frac{3}{3} \\)', 'Divide numerator by denominator: \\( 14 \\div 3 = 4 \\) remainder \\( 2 \\). So, \\( \\frac{14}{3} = 4\\frac{2}{3} \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Improper fractions to mixed numbers', 'Converting improper fractions to mixed numbers', '\\( \\frac{17}{8} \\)', '\\( 2\\frac{1}{8} \\)', '\\( 2\\frac{2}{8} \\)', '\\( 3\\frac{1}{8} \\)', '\\( 2\\frac{3}{8} \\)', 'Divide numerator by denominator: \\( 17 \\div 8 = 2 \\) remainder \\( 1 \\). So, \\( \\frac{17}{8} = 2\\frac{1}{8} \\).');

-- Converting mixed numbers to improper fractions
INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Fractions', 'Mixed numbers to improper fractions', 'Converting mixed numbers to improper fractions', '\\( 1\\frac{3}{4} \\)', '\\( \\frac{7}{4} \\)', '\\( \\frac{6}{4} \\)', '\\( \\frac{5}{4} \\)', '\\( \\frac{8}{4} \\)', 'Multiply whole number by denominator and add numerator: \\( 1 \\times 4 + 3 = 7 \\). So, \\( 1\\frac{3}{4} = \\frac{7}{4} \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Mixed numbers to improper fractions', 'Converting mixed numbers to improper fractions', '\\( 1\\frac{4}{5} \\)', '\\( \\frac{9}{5} \\)', '\\( \\frac{8}{5} \\)', '\\( \\frac{7}{5} \\)', '\\( \\frac{10}{5} \\)', 'Multiply whole number by denominator and add numerator: \\( 1 \\times 5 + 4 = 9 \\). So, \\( 1\\frac{4}{5} = \\frac{9}{5} \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Mixed numbers to improper fractions', 'Converting mixed numbers to improper fractions', '\\( 1\\frac{5}{6} \\)', '\\( \\frac{11}{6} \\)', '\\( \\frac{10}{6} \\)', '\\( \\frac{9}{6} \\)', '\\( \\frac{12}{6} \\)', 'Multiply whole number by denominator and add numerator: \\( 1 \\times 6 + 5 = 11 \\). So, \\( 1\\frac{5}{6} = \\frac{11}{6} \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Mixed numbers to improper fractions', 'Converting mixed numbers to improper fractions', '\\( 2\\frac{1}{3} \\)', '\\( \\frac{7}{3} \\)', '\\( \\frac{6}{3} \\)', '\\( \\frac{5}{3} \\)', '\\( \\frac{8}{3} \\)', 'Multiply whole number by denominator and add numerator: \\( 2 \\times 3 + 1 = 7 \\). So, \\( 2\\frac{1}{3} = \\frac{7}{3} \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Mixed numbers to improper fractions', 'Converting mixed numbers to improper fractions', '\\( 3\\frac{2}{5} \\)', '\\( \\frac{17}{5} \\)', '\\( \\frac{16}{5} \\)', '\\( \\frac{15}{5} \\)', '\\( \\frac{18}{5} \\)', 'Multiply whole number by denominator and add numerator: \\( 3 \\times 5 + 2 = 17 \\). So, \\( 3\\frac{2}{5} = \\frac{17}{5} \\).');

-- Converting fractions to percentages
INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Fractions', 'Fractions to percentages', 'Convert the fraction to a percentage.', '\\( \\frac{1}{4} \\)', '25%', '20%', '30%', '40%', 'Multiply by 100: \\( \\frac{1}{4} \\times 100 = 25\\% \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Fractions to percentages', 'Convert the fraction to a percentage.', '\\( \\frac{3}{5} \\)', '60%', '50%', '70%', '80%', 'Multiply by 100: \\( \\frac{3}{5} \\times 100 = 60\\% \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Fractions to percentages', 'Convert the fraction to a percentage.', '\\( \\frac{2}{3} \\)', '66.67%', '60%', '70%', '80%', 'Multiply by 100: \\( \\frac{2}{3} \\times 100 = 66.67\\% \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Fractions to percentages', 'Convert the fraction to a percentage.', '\\( \\frac{5}{8} \\)', '62.5%', '60%', '70%', '80%', 'Multiply by 100: \\( \\frac{5}{8} \\times 100 = 62.5\\% \\).'),
('Arithmetic Fundamentals', 'Fractions', 'Fractions to percentages', 'Convert the fraction to a percentage.', '\\( \\frac{7}{10} \\)', '70%', '60%', '80%', '90%', 'Multiply by 100: \\( \\frac{7}{10} \\times 100 = 70\\% \\).');

-- Fractions to decimals
INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Fractions', 'Fractions to decimals', 'Convert the fraction to decimal.', 'Convert \\( \\frac{1}{2} \\) to decimal.', '0.5', '0.2', '0.25', '2.0', 'Divide numerator by denominator: 1 ÷ 2 = 0.5.'),
('Arithmetic Fundamentals', 'Fractions', 'Fractions to decimals', 'Convert the fraction to decimal.', 'Convert \\( \\frac{3}{4} \\) to decimal.', '0.75', '0.7', '0.25', '1.33', 'Divide numerator by denominator: 3 ÷ 4 = 0.75.'),
('Arithmetic Fundamentals', 'Fractions', 'Fractions to decimals', 'Convert the fraction to decimal.', 'Convert \\( \\frac{2}{5} \\) to decimal.', '0.4', '0.2', '0.25', '0.5', 'Divide numerator by denominator: 2 ÷ 5 = 0.4.'),
('Arithmetic Fundamentals', 'Fractions', 'Fractions to decimals', 'Convert the fraction to decimal.', 'Convert \\( \\frac{7}{8} \\) to decimal.', '0.875', '0.78', '0.85', '0.75', 'Divide numerator by denominator: 7 ÷ 8 = 0.875.'),
('Arithmetic Fundamentals', 'Fractions', 'Fractions to decimals', 'Convert the fraction to decimal.', 'Convert \\( \\frac{5}{6} \\) to decimal.', '0.8333', '0.85', '0.8', '0.75', 'Divide numerator by denominator: 5 ÷ 6 ≈ 0.8333.');


-- Comparing fractions with like denominators
INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Fractions', 'Comparing fractions with like denominators', 'Which fraction is greater?', '\\( \\frac{2}{5} \\) or \\( \\frac{3}{5} \\)', '\\( \\frac{3}{5} \\)', '\\( \\frac{2}{5} \\)', '\\( \\frac{5}{5} \\)', '\\( \\frac{1}{5} \\)', 'Since the denominators are the same, compare numerators: \\( 2 < 3 \\). So, \\( \\frac{3}{5} \\) is greater.'),
('Arithmetic Fundamentals', 'Fractions', 'Comparing fractions with like denominators', 'Which fraction is greater?', '\\( \\frac{4}{7} \\) or \\( \\frac{2}{7} \\)', '\\( \\frac{4}{7} \\)', '\\( \\frac{2}{7} \\)', '\\( \\frac{3}{7} \\)', '\\( \\frac{5}{7} \\)', 'Since the denominators are the same, compare numerators: \\( 4 > 2 \\). So, \\( \\frac{4}{7} \\) is greater.'),
('Arithmetic Fundamentals', 'Fractions', 'Comparing fractions with like denominators', 'Which fraction is greater?', '\\( \\frac{1}{3} \\) or \\( \\frac{2}{3} \\)', '\\( \\frac{2}{3} \\)', '\\( \\frac{1}{3} \\)', '\\( \\frac{3}{3} \\)', '\\( \\frac{4}{3} \\)', 'Since the denominators are the same, compare numerators: \\( 1 < 2 \\). So, \\( \\frac{2}{3} \\) is greater.'),
('Arithmetic Fundamentals', 'Fractions', 'Comparing fractions with like denominators', 'Which fraction is greater?', '\\( \\frac{5}{8} \\) or \\( \\frac{3}{8} \\)', '\\( \\frac{5}{8} \\)', '\\( \\frac{3}{8} \\)', '\\( \\frac{4}{8} \\)', '\\( \\frac{6}{8} \\)', 'Since the denominators are the same, compare numerators: \\( 5 > 3 \\). So, \\( \\frac{5}{8} \\) is greater.'),
('Arithmetic Fundamentals', 'Fractions', 'Comparing fractions with like denominators', 'Which fraction is greater?', '\\( \\frac{6}{10} \\) or \\( \\frac{4}{10} \\)', '\\( \\frac{6}{10} \\)', '\\( \\frac{4}{10} \\)', '\\( \\frac{5}{10} \\)', '\\( \\frac{7}{10} \\)', 'Since the denominators are the same, compare numerators: \\( 6 > 4 \\). So, \\( \\frac{6}{10} \\) is greater.');

-- Comparing fractions with unlike denominators
INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Fractions', 'Comparing fractions with unlike denominators', 'Which fraction is greater?', '\\( \\frac{2}{3} \\) or \\( \\frac{3}{4} \\)', '\\( \\frac{3}{4} \\)', '\\( \\frac{2}{3} \\)', '\\( \\frac{5}{7} \\)', '\\( \\frac{1}{2} \\)', 'Common denominator is 12: \\( \\frac{2}{3} = \\frac{8}{12}, \\frac{3}{4} = \\frac{9}{12} \\). Since 8 < 9, \\( \\frac{3}{4} \\) is greater.'),
('Arithmetic Fundamentals', 'Fractions', 'Comparing fractions with unlike denominators', 'Which fraction is greater?', '\\( \\frac{5}{6} \\) or \\( \\frac{7}{8} \\)', '\\( \\frac{7}{8} \\)', '\\( \\frac{5}{6} \\)', '\\( \\frac{6}{7} \\)', '\\( \\frac{4}{5} \\)', 'Common denominator is 24: \\( \\frac{5}{6} = \\frac{20}{24}, \\frac{7}{8} = \\frac{21}{24} \\). Since 20 < 21, \\( \\frac{7}{8} \\) is greater.'),
('Arithmetic Fundamentals', 'Fractions', 'Comparing fractions with unlike denominators', 'Which fraction is greater?', '\\( \\frac{3}{5} \\) or \\( \\frac{2}{3} \\)', '\\( \\frac{2}{3} \\)', '\\( \\frac{3}{5} \\)', '\\( \\frac{5}{6} \\)', '\\( \\frac{1}{2} \\)', 'Common denominator is 15: \\( \\frac{3}{5} = \\frac{9}{15}, \\frac{2}{3} = \\frac{10}{15} \\). Since 9 < 10, \\( \\frac{2}{3} \\) is greater.'),
('Arithmetic Fundamentals', 'Fractions', 'Comparing fractions with unlike denominators', 'Which fraction is greater?', '\\( \\frac{7}{10} \\) or \\( \\frac{3}{4} \\)', '\\( \\frac{3}{4} \\)', '\\( \\frac{7}{10} \\)', '\\( \\frac{5}{8} \\)', '\\( \\frac{2}{3} \\)', 'Common denominator is 20: \\( \\frac{7}{10} = \\frac{14}{20}, \\frac{3}{4} = \\frac{15}{20} \\). Since 14 < 15, \\( \\frac{3}{4} \\) is greater.'),
('Arithmetic Fundamentals', 'Fractions', 'Comparing fractions with unlike denominators', 'Which fraction is greater?', '\\( \\frac{4}{7} \\) or \\( \\frac{5}{9} \\)', '\\( \\frac{5}{9} \\)', '\\( \\frac{4}{7} \\)', '\\( \\frac{6}{11} \\)', '\\( \\frac{1}{2} \\)', 'Common denominator is 63: \\( \\frac{4}{7} = \\frac{36}{63}, \\frac{5}{9} = \\frac{35}{63} \\). Since 36 > 35, actually \\( \\frac{4}{7} \\) is greater.');

-- Ordering fractions from least to greatest
INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Fractions', 'Ordering fractions from least to greatest', 'Order the fractions from least to greatest.', '\\( \\frac{1}{4}, \\frac{1}{2}, \\frac{3}{4} \\)', '\\( \\frac{1}{4} < \\frac{1}{2} < \\frac{3}{4} \\)', '\\( \\frac{3}{4} < \\frac{1}{2} < \\frac{1}{4} \\)', '\\( \\frac{1}{2} < \\frac{3}{4} < \\frac{1}{4} \\)', '\\( \\frac{1}{2} < \\frac{1}{4} < \\frac{3}{4} \\)', 'Compare fractions with common denominator: 1/4 = 1/4, 1/2 = 2/4, 3/4 = 3/4. So order is 1/4, 1/2, 3/4.'),
('Arithmetic Fundamentals', 'Fractions', 'Ordering fractions from least to greatest', 'Order the fractions from least to greatest.', '\\( \\frac{2}{5}, \\frac{3}{10}, \\frac{1}{2} \\)', '\\( \\frac{3}{10} < \\frac{2}{5} < \\frac{1}{2} \\)', '\\( \\frac{2}{5} < \\frac{3}{10} < \\frac{1}{2} \\)', '\\( \\frac{1}{2} < \\frac{3}{10} < \\frac{2}{5} \\)', '\\( \\frac{2}{5} < \\frac{1}{2} < \\frac{3}{10} \\)', 'Common denominator is 10: 2/5 = 4/10, 3/10 = 3/10, 1/2 = 5/10. Order: 3/10, 4/10, 5/10.'),
('Arithmetic Fundamentals', 'Fractions', 'Ordering fractions from least to greatest', 'Order the fractions from least to greatest.', '\\( \\frac{3}{8}, \\frac{1}{4}, \\frac{5}{8} \\)', '\\( \\frac{1}{4} < \\frac{3}{8} < \\frac{5}{8} \\)', '\\( \\frac{3}{8} < \\frac{1}{4} < \\frac{5}{8} \\)', '\\( \\frac{5}{8} < \\frac{3}{8} < \\frac{1}{4} \\)', '\\( \\frac{1}{4} < \\frac{5}{8} < \\frac{3}{8} \\)', 'Common denominator is 8: 3/8 = 3/8, 1/4 = 2/8, 5/8 = 5/8. Order: 2/8, 3/8, 5/8.'),
('Arithmetic Fundamentals', 'Fractions', 'Ordering fractions from least to greatest', 'Order the fractions from least to greatest.', '\\( \\frac{2}{3}, \\frac{3}{4}, \\frac{5}{6} \\)', '\\( \\frac{2}{3} < \\frac{3}{4} < \\frac{5}{6} \\)', '\\( \\frac{3}{4} < \\frac{2}{3} < \\frac{5}{6} \\)', '\\( \\frac{5}{6} < \\frac{3}{4} < \\frac{2}{3} \\)', '\\( \\frac{3}{4} < \\frac{5}{6} < \\frac{2}{3} \\)', 'Common denominator is 12: 2/3 = 8/12, 3/4 = 9/12, 5/6 = 10/12. Order: 8/12, 9/12, 10/12.'),
('Arithmetic Fundamentals', 'Fractions', 'Ordering fractions from least to greatest', 'Order the fractions from least to greatest.', '\\( \\frac{1}{5}, \\frac{2}{3}, \\frac{3}{4} \\)', '\\( \\frac{1}{5} < \\frac{2}{3} < \\frac{3}{4} \\)', '\\( \\frac{2}{3} < \\frac{1}{5} < \\frac{3}{4} \\)', '\\( \\frac{3}{4} < \\frac{2}{3} < \\frac{1}{5} \\)', '\\( \\frac{2}{3} < \\frac{3}{4} < \\frac{1}{5} \\)', 'Common denominator is 60: 1/5 = 12/60, 2/3 = 40/60, 3/4 = 45/60. Order: 12/60, 40/60, 45/60.');

-- Ordering fractions from greatest to least
INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Fractions', 'Ordering fractions from greatest to least', 'Order the fractions from greatest to least.', '\\( \\frac{1}{4}, \\frac{1}{2}, \\frac{3}{4} \\)', '\\( \\frac{3}{4} > \\frac{1}{2} > \\frac{1}{4} \\)', '\\( \\frac{1}{4} > \\frac{1}{2} > \\frac{3}{4} \\)', '\\( \\frac{1}{2} > \\frac{3}{4} > \\frac{1}{4} \\)', '\\( \\frac{1}{2} > \\frac{1}{4} > \\frac{3}{4} \\)', 'Common denominator is 4: 1/4 = 1/4, 1/2 = 2/4, 3/4 = 3/4. Order greatest to least: 3/4, 2/4, 1/4.'),
('Arithmetic Fundamentals', 'Fractions', 'Ordering fractions from greatest to least', 'Order the fractions from greatest to least.', '\\( \\frac{2}{5}, \\frac{3}{10}, \\frac{1}{2} \\)', '\\( \\frac{1}{2} > \\frac{2}{5} > \\frac{3}{10} \\)', '\\( \\frac{2}{5} > \\frac{3}{10} > \\frac{1}{2} \\)', '\\( \\frac{3}{10} > \\frac{2}{5} > \\frac{1}{2} \\)', '\\( \\frac{3}{10} > \\frac{1}{2} > \\frac{2}{5} \\)', 'Common denominator is 10: 2/5 = 4/10, 3/10 = 3/10, 1/2 = 5/10. Order greatest to least: 5/10, 4/10, 3/10.'),
('Arithmetic Fundamentals', 'Fractions', 'Ordering fractions from greatest to least', 'Order the fractions from greatest to least.', '\\( \\frac{3}{8}, \\frac{1}{4}, \\frac{5}{8} \\)', '\\( \\frac{5}{8} > \\frac{3}{8} > \\frac{1}{4} \\)', '\\( \\frac{3}{8} > \\frac{5}{8} > \\frac{1}{4} \\)', '\\( \\frac{1}{4} > \\frac{3}{8} > \\frac{5}{8} \\)', '\\( \\frac{1}{4} > \\frac{5}{8} > \\frac{3}{8} \\)', 'Common denominator is 8: 3/8 = 3/8, 1/4 = 2/8, 5/8 = 5/8. Order greatest to least: 5/8, 3/8, 2/8.'),
('Arithmetic Fundamentals', 'Fractions', 'Ordering fractions from greatest to least', 'Order the fractions from greatest to least.', '\\( \\frac{2}{3}, \\frac{3}{4}, \\frac{5}{6} \\)', '\\( \\frac{5}{6} > \\frac{3}{4} > \\frac{2}{3} \\)', '\\( \\frac{2}{3} > \\frac{3}{4} > \\frac{5}{6} \\)', '\\( \\frac{3}{4} > \\frac{5}{6} > \\frac{2}{3} \\)', '\\( \\frac{2}{3} > \\frac{5}{6} > \\frac{3}{4} \\)', 'Common denominator is 12: 2/3 = 8/12, 3/4 = 9/12, 5/6 = 10/12. Order greatest to least: 10/12, 9/12, 8/12.'),
('Arithmetic Fundamentals', 'Fractions', 'Ordering fractions from greatest to least', 'Order the fractions from greatest to least.', '\\( \\frac{1}{5}, \\frac{2}{3}, \\frac{3}{4} \\)', '\\( \\frac{3}{4} > \\frac{2}{3} > \\frac{1}{5} \\)', '\\( \\frac{2}{3} > \\frac{1}{5} > \\frac{3}{4} \\)', '\\( \\frac{1}{5} > \\frac{2}{3} > \\frac{3}{4} \\)', '\\( \\frac{1}{5} > \\frac{3}{4} > \\frac{2}{3} \\)', 'Common denominator is 60: 1/5 = 12/60, 2/3 = 40/60, 3/4 = 45/60. Order greatest to least: 45/60, 40/60, 12/60.');

-- Simplifying or reducing fractions
INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Fractions', 'Simplifying or reducing fractions', 'Simplify the given fraction.', '\\( \\frac{8}{12} \\)', '\\( \\frac{2}{3} \\)', '\\( \\frac{4}{6} \\)', '\\( \\frac{3}{4} \\)', '\\( \\frac{1}{2} \\)', 'Divide numerator and denominator by their greatest common factor (GCF) 4: 8/12 ÷ 4/4 = 2/3.'),
('Arithmetic Fundamentals', 'Fractions', 'Simplifying or reducing fractions', 'Simplify the given fraction.', '\\( \\frac{15}{25} \\)', '\\( \\frac{3}{5} \\)', '\\( \\frac{5}{15} \\)', '\\( \\frac{2}{5} \\)', '\\( \\frac{4}{5} \\)', 'GCF of 15 and 25 is 5: 15/25 ÷ 5/5 = 3/5.'),
('Arithmetic Fundamentals', 'Fractions', 'Simplifying or reducing fractions', 'Simplify the given fraction.', '\\( \\frac{18}{24} \\)', '\\( \\frac{3}{4} \\)', '\\( \\frac{6}{8} \\)', '\\( \\frac{9}{12} \\)', '\\( \\frac{2}{3} \\)', 'GCF of 18 and 24 is 6: 18/24 ÷ 6/6 = 3/4.'),
('Arithmetic Fundamentals', 'Fractions', 'Simplifying or reducing fractions', 'Simplify the given fraction.', '\\( \\frac{20}{30} \\)', '\\( \\frac{2}{3} \\)', '\\( \\frac{4}{6} \\)', '\\( \\frac{3}{5} \\)', '\\( \\frac{5}{8} \\)', 'GCF of 20 and 30 is 10: 20/30 ÷ 10/10 = 2/3.'),
('Arithmetic Fundamentals', 'Fractions', 'Simplifying or reducing fractions', 'Simplify the given fraction.', '\\( \\frac{12}{18} \\)', '\\( \\frac{2}{3} \\)', '\\( \\frac{6}{9} \\)', '\\( \\frac{3}{4} \\)', '\\( \\frac{4}{6} \\)', 'GCF of 12 and 18 is 6: 12/18 ÷ 6/6 = 2/3.');

-- Finding equivalent fractions
INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Fractions', 'Finding equivalent fractions', 'Find an equivalent fraction for the given fraction.', '\\( \\frac{1}{2} \\)', '\\( \\frac{2}{4} \\)', '\\( \\frac{1}{3} \\)', '\\( \\frac{3}{5} \\)', '\\( \\frac{3}{4} \\)', 'Multiply numerator and denominator by the same number: 1×2 / 2×2 = 2/4.'),
('Arithmetic Fundamentals', 'Fractions', 'Finding equivalent fractions', 'Find an equivalent fraction for the given fraction.', '\\( \\frac{3}{5} \\)', '\\( \\frac{6}{10} \\)', '\\( \\frac{9}{15} \\)', '\\( \\frac{3}{8} \\)', '\\( \\frac{4}{5} \\)', 'Multiply numerator and denominator by 2: 3×2 / 5×2 = 6/10.'),
('Arithmetic Fundamentals', 'Fractions', 'Finding equivalent fractions', 'Find an equivalent fraction for the given fraction.', '\\( \\frac{4}{7} \\)', '\\( \\frac{8}{14} \\)', '\\( \\frac{2}{7} \\)', '\\( \\frac{6}{10} \\)', '\\( \\frac{5}{7} \\)', 'Multiply numerator and denominator by 2: 4×2 / 7×2 = 8/14.'),
('Arithmetic Fundamentals', 'Fractions', 'Finding equivalent fractions', 'Find an equivalent fraction for the given fraction.', '\\( \\frac{5}{8} \\)', '\\( \\frac{10}{16} \\)', '\\( \\frac{15}{24} \\)', '\\( \\frac{5}{10} \\)', '\\( \\frac{9}{8} \\)', 'Multiply numerator and denominator by 2: 5×2 / 8×2 = 10/16.'),
('Arithmetic Fundamentals', 'Fractions', 'Finding equivalent fractions', 'Find an equivalent fraction for the given fraction.', '\\( \\frac{2}{3} \\)', '\\( \\frac{4}{6} \\)', '\\( \\frac{3}{5} \\)', '\\( \\frac{6}{9} \\)', '\\( \\frac{3}{4} \\)', 'Multiply numerator and denominator by 2: 2×2 / 3×2 = 4/6.');

-- Identifying proper fractions
INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Fractions', 'Identifying proper fractions', 'Identify the proper fraction.', '\\( \\frac{3}{4} \\)', 'Proper', 'Improper', 'Mixed', 'None', 'A proper fraction has a numerator smaller than the denominator: 3 < 4, so it is proper.'),
('Arithmetic Fundamentals', 'Fractions', 'Identifying proper fractions', 'Identify the proper fraction.', '\\( \\frac{5}{8} \\)', 'Proper', 'Improper', 'Mixed', 'None', 'Numerator 5 is less than denominator 8, so it is a proper fraction.'),
('Arithmetic Fundamentals', 'Fractions', 'Identifying proper fractions', 'Identify the proper fraction.', '\\( \\frac{7}{10} \\)', 'Proper', 'Improper', 'Mixed', 'None', '7 < 10, therefore this is a proper fraction.'),
('Arithmetic Fundamentals', 'Fractions', 'Identifying proper fractions', 'Identify the proper fraction.', '\\( \\frac{2}{3} \\)', 'Proper', 'Improper', 'Mixed', 'None', 'Numerator 2 is less than denominator 3, making it a proper fraction.'),
('Arithmetic Fundamentals', 'Fractions', 'Identifying proper fractions', 'Identify the proper fraction.', '\\( \\frac{4}{5} \\)', 'Proper', 'Improper', 'Mixed', 'None', '4 < 5, so it is a proper fraction.');

-- Identifying improper fractions
INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Fractions', 'Identifying improper fractions', 'Identify the improper fraction.', '\\( \\frac{7}{4} \\)', 'Improper', 'Proper', 'Mixed', 'None', 'An improper fraction has a numerator greater than or equal to the denominator: 7 > 4, so it is improper.'),
('Arithmetic Fundamentals', 'Fractions', 'Identifying improper fractions', 'Identify the improper fraction.', '\\( \\frac{9}{5} \\)', 'Improper', 'Proper', 'Mixed', 'None', 'Numerator 9 is greater than denominator 5, making it an improper fraction.'),
('Arithmetic Fundamentals', 'Fractions', 'Identifying improper fractions', 'Identify the improper fraction.', '\\( \\frac{11}{6} \\)', 'Improper', 'Proper', 'Mixed', 'None', '11 > 6, therefore this is an improper fraction.'),
('Arithmetic Fundamentals', 'Fractions', 'Identifying improper fractions', 'Identify the improper fraction.', '\\( \\frac{8}{3} \\)', 'Improper', 'Proper', 'Mixed', 'None', 'Numerator 8 is greater than denominator 3, so it is improper.'),
('Arithmetic Fundamentals', 'Fractions', 'Identifying improper fractions', 'Identify the improper fraction.', '\\( \\frac{5}{2} \\)', 'Improper', 'Proper', 'Mixed', 'None', '5 > 2, which makes this an improper fraction.');

-- Identifying unit fractions
INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Fractions', 'Identifying unit fractions', 'Identify the unit fraction.', '\\( \\frac{1}{5} \\)', 'Unit', 'Non-unit', 'Improper', 'Mixed', 'A unit fraction has numerator 1 and denominator greater than 1: 1/5 is a unit fraction.'),
('Arithmetic Fundamentals', 'Fractions', 'Identifying unit fractions', 'Identify the unit fraction.', '\\( \\frac{1}{8} \\)', 'Unit', 'Non-unit', 'Improper', 'Mixed', 'Numerator is 1 and denominator 8 > 1, so it is a unit fraction.'),
('Arithmetic Fundamentals', 'Fractions', 'Identifying unit fractions', 'Identify the unit fraction.', '\\( \\frac{1}{3} \\)', 'Unit', 'Non-unit', 'Improper', 'Mixed', 'Numerator 1 and denominator 3, therefore a unit fraction.'),
('Arithmetic Fundamentals', 'Fractions', 'Identifying unit fractions', 'Identify the unit fraction.', '\\( \\frac{1}{10} \\)', 'Unit', 'Non-unit', 'Improper', 'Mixed', 'Numerator 1 and denominator 10, making it a unit fraction.'),
('Arithmetic Fundamentals', 'Fractions', 'Identifying unit fractions', 'Identify the unit fraction.', '\\( \\frac{1}{2} \\)', 'Unit', 'Non-unit', 'Improper', 'Mixed', 'Numerator 1 and denominator 2, so this is a unit fraction.');


-- Complex fractions
INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Fractions', 'Complex fractions', 'Simplify the complex fraction.', '\\( \\frac{\\frac{2}{3}}{\\frac{4}{5}} \\)', '\\( \\frac{5}{6} \\)', '\\( \\frac{1}{2} \\)', '\\( \\frac{3}{7} \\)', '\\( \\frac{2}{5} \\)', 'Divide the numerator by the denominator: (2/3) ÷ (4/5) = 2/3 × 5/4 = 10/12 = 5/6.'),
('Arithmetic Fundamentals', 'Fractions', 'Complex fractions', 'Simplify the complex fraction.', '\\( \\frac{\\frac{3}{4}}{\\frac{1}{2}} \\)', '\\( \\frac{3}{2} \\)', '\\( \\frac{1}{2} \\)', '\\( \\frac{1}{4} \\)', '\\( \\frac{2}{3} \\)', 'Divide fractions: (3/4) ÷ (1/2) = 3/4 × 2/1 = 6/4 = 3/2.'),
('Arithmetic Fundamentals', 'Fractions', 'Complex fractions', 'Simplify the complex fraction.', '\\( \\frac{\\frac{5}{6}}{\\frac{2}{3}} \\)', '\\( \\frac{5}{4} \\)', '\\( \\frac{1}{2} \\)', '\\( \\frac{3}{4} \\)', '\\( \\frac{2}{5} \\)', 'Divide fractions: (5/6) ÷ (2/3) = 5/6 × 3/2 = 15/12 = 5/4.'),
('Arithmetic Fundamentals', 'Fractions', 'Complex fractions', 'Simplify the complex fraction.', '\\( \\frac{\\frac{7}{8}}{\\frac{7}{10}} \\)', '\\( \\frac{10}{8} \\)', '\\( \\frac{1}{2} \\)', '\\( \\frac{7}{16} \\)', '\\( \\frac{7}{18} \\)', 'Divide fractions: (7/8) ÷ (7/10) = 7/8 × 10/7 = 70/56 = 10/8.'),
('Arithmetic Fundamentals', 'Fractions', 'Complex fractions', 'Simplify the complex fraction.', '\\( \\frac{\\frac{4}{9}}{\\frac{2}{3}} \\)', '\\( \\frac{2}{3} \\)', '\\( \\frac{1}{6} \\)', '\\( \\frac{3}{4} \\)', '\\( \\frac{1}{3} \\)', 'Divide fractions: (4/9) ÷ (2/3) = 4/9 × 3/2 = 12/18 = 2/3.');

