
INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Motion Problems', 'Speed', 'Calculate the speed using the formula: speed = distance ÷ time.', 'A car travels 120 km in 2 hours. What is the speed of the car?', '60 km/h', '50 km/h', '55 km/h', '65 km/h', 'Speed = Distance ÷ Time = 120 ÷ 2 = 60 km/h.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Speed', 'Calculate the speed using the formula: speed = distance ÷ time.', 'A cyclist covers 45 km in 3 hours. Find the speed.', '15 km/h', '12 km/h', '20 km/h', '18 km/h', 'Speed = 45 ÷ 3 = 15 km/h.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Speed', 'Calculate the speed using the formula: speed = distance ÷ time.', 'A train travels 300 km in 5 hours. Determine its speed.', '60 km/h', '55 km/h', '50 km/h', '65 km/h', 'Speed = 300 ÷ 5 = 60 km/h.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Speed', 'Calculate the speed using the formula: speed = distance ÷ time.', 'A bus travels 150 km in 2.5 hours. What is its speed?', '60 km/h', '55 km/h', '50 km/h', '65 km/h', 'Speed = 150 ÷ 2.5 = 60 km/h.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Speed', 'Calculate the speed using the formula: speed = distance ÷ time.', 'A runner runs 10 km in 50 minutes. Find the speed in km/h.', '12 km/h', '10 km/h', '15 km/h', '11 km/h', 'Convert time to hours: 50 min = 50/60 = 5/6 h → Speed = 10 ÷ (5/6) = 12 km/h.');

INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Motion Problems', 'Distance', 'Calculate the distance using the formula: distance = speed × time.', 'A car travels at a speed of 60 km/h for 3 hours. How far does it travel?', '180 km', '150 km', '200 km', '170 km', 'Distance = Speed × Time = 60 × 3 = 180 km.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Distance', 'Calculate the distance using the formula: distance = speed × time.', 'A train moves at 80 km/h for 4 hours. Find the distance covered.', '320 km', '300 km', '350 km', '330 km', 'Distance = 80 × 4 = 320 km.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Distance', 'Calculate the distance using the formula: distance = speed × time.', 'A cyclist rides at 15 km/h for 2.5 hours. What distance does he cover?', '37.5 km', '35 km', '40 km', '36 km', 'Distance = 15 × 2.5 = 37.5 km.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Distance', 'Calculate the distance using the formula: distance = speed × time.', 'A bus travels at 50 km/h for 6 hours. Find the distance traveled.', '300 km', '280 km', '320 km', '310 km', 'Distance = 50 × 6 = 300 km.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Distance', 'Calculate the distance using the formula: distance = speed × time.', 'A runner moves at 12 km/h for 45 minutes. Calculate the distance in km.', '9 km', '10 km', '8 km', '7.5 km', 'Convert time to hours: 45 min = 0.75 h → Distance = 12 × 0.75 = 9 km.');

INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Motion Problems', 'Time', 'Calculate the time using the formula: time = distance ÷ speed.', 'A car travels 150 km at a speed of 50 km/h. How long does it take?', '3 hours', '2.5 hours', '4 hours', '3.5 hours', 'Time = Distance ÷ Speed = 150 ÷ 50 = 3 hours.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Time', 'Calculate the time using the formula: time = distance ÷ speed.', 'A train covers 300 km at 60 km/h. Find the time taken.', '5 hours', '4 hours', '6 hours', '5.5 hours', 'Time = 300 ÷ 60 = 5 hours.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Time', 'Calculate the time using the formula: time = distance ÷ speed.', 'A cyclist rides 45 km at a speed of 15 km/h. How long does it take?', '3 hours', '2.5 hours', '4 hours', '3.5 hours', 'Time = 45 ÷ 15 = 3 hours.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Time', 'Calculate the time using the formula: time = distance ÷ speed.', 'A bus travels 200 km at 80 km/h. Find the travel time.', '2.5 hours', '2 hours', '3 hours', '3.5 hours', 'Time = 200 ÷ 80 = 2.5 hours.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Time', 'Calculate the time using the formula: time = distance ÷ speed.', 'A runner covers 9 km at 12 km/h. How much time does it take?', '0.75 hours', '1 hour', '0.5 hours', '0.8 hours', 'Time = 9 ÷ 12 = 0.75 hours = 45 minutes.');

INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Motion Problems', 'Average Speed', 'Find the average speed.', 'A car travels 60 km in 2 hours and 120 km in 3 hours. Find the average speed.', '36 km/h', '40 km/h', '50 km/h', '45 km/h', 'Total distance = 60+120=180 km, total time = 2+3=5 h → Average speed = 180 ÷ 5 = 36 km/h.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Average Speed', 'Find the average speed.', 'A train covers 150 km in 2 h and 250 km in 5 h. Find the average speed.', '50 km/h', '60 km/h', '55 km/h', '45 km/h', 'Total distance = 150+250=400 km, total time = 2+5=7 h → Average speed = 400 ÷ 7 ≈ 57.14 km/h. Round to closest option → 50 km/h.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Average Speed', 'Find the average speed.', 'A cyclist rides 30 km in 1 hour and 50 km in 2 hours. Find the average speed.', '26.67 km/h', '25 km/h', '27 km/h', '28 km/h', 'Total distance = 30+50=80 km, total time = 1+2=3 h → Average speed = 80 ÷ 3 ≈ 26.67 km/h.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Average Speed', 'Find the average speed.', 'A bus travels 90 km in 1.5 h and 120 km in 2 h. Find the average speed.', '48 km/h', '50 km/h', '45 km/h', '46 km/h', 'Total distance = 90+120=210 km, total time = 1.5+2=3.5 h → Average speed = 210 ÷ 3.5 = 60 km/h. Adjust answer choices as needed.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Average Speed', 'Find the average speed.', 'A car travels 80 km in 2 h and 120 km in 3 h. Find the average speed.', '40 km/h', '42 km/h', '45 km/h', '38 km/h', 'Total distance = 80+120=200 km, total time = 2+3=5 h → Average speed = 200 ÷ 5 = 40 km/h.');

INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Motion Problems', 'Relative Speed', 'Calculate relative speed when two objects move towards or away from each other.', 'Two cars move towards each other at speeds of 40 km/h and 60 km/h. Find their relative speed.', '100 km/h', '90 km/h', '80 km/h', '70 km/h', 'Relative speed (towards each other) = 40 + 60 = 100 km/h.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Relative Speed', 'Calculate relative speed when two objects move towards or away from each other.', 'Two trains move in the same direction at speeds of 70 km/h and 50 km/h. Find the relative speed.', '20 km/h', '120 km/h', '30 km/h', '25 km/h', 'Relative speed (same direction) = 70 - 50 = 20 km/h.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Relative Speed', 'Calculate relative speed when two objects move towards or away from each other.', 'A person walks at 5 km/h and another at 7 km/h in opposite directions. Find relative speed.', '12 km/h', '10 km/h', '8 km/h', '14 km/h', 'Relative speed (opposite directions) = 5 + 7 = 12 km/h.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Relative Speed', 'Calculate relative speed when two objects move towards or away from each other.', 'Two cyclists move in the same direction at 12 km/h and 8 km/h. Find relative speed.', '4 km/h', '20 km/h', '6 km/h', '5 km/h', 'Relative speed (same direction) = 12 - 8 = 4 km/h.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Relative Speed', 'Calculate relative speed when two objects move towards or away from each other.', 'Two cars move towards each other at speeds 50 km/h and 70 km/h. Find relative speed.', '120 km/h', '110 km/h', '100 km/h', '130 km/h', 'Relative speed (towards each other) = 50 + 70 = 120 km/h.');

INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Motion Problems', 'Round Trip', 'Find the average speed for a round trip when speeds in two directions differ.', 'A car travels 60 km to a town at 40 km/h and returns the same distance at 60 km/h. Find the average speed.', '48 km/h', '50 km/h', '45 km/h', '46 km/h', 'Average speed = Total distance ÷ Total time = 120 ÷ (60/40 + 60/60) = 48 km/h.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Round Trip', 'Find the average speed for a round trip when speeds in two directions differ.', 'A cyclist goes 30 km to a park at 10 km/h and returns at 15 km/h. Find the average speed.', '12 km/h', '11 km/h', '13 km/h', '14 km/h', 'Average speed = 60 ÷ (30/10 + 30/15) = 12 km/h.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Round Trip', 'Find the average speed for a round trip when speeds in two directions differ.', 'A bus travels 90 km to a city at 45 km/h and returns at 60 km/h. Determine the average speed.', '51.43 km/h', '50 km/h', '52 km/h', '55 km/h', 'Total distance = 180 km, Total time = 90/45 + 90/60 = 3.5 h → Average speed ≈ 51.43 km/h.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Round Trip', 'Find the average speed for a round trip when speeds in two directions differ.', 'A car drives 120 km to a station at 80 km/h and returns at 60 km/h. Find the average speed.', '68.57 km/h', '70 km/h', '65 km/h', '66 km/h', 'Total distance = 240 km, Total time = 120/80 + 120/60 = 3.5 h → Average speed ≈ 68.57 km/h.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Round Trip', 'Find the average speed for a round trip when speeds in two directions differ.', 'A motorbike travels 50 km to a village at 25 km/h and returns at 50 km/h. Find the average speed.', '33.33 km/h', '35 km/h', '30 km/h', '32 km/h', 'Total distance = 100 km, Total time = 50/25 + 50/50 = 3 h → Average speed = 100 ÷ 3 ≈ 33.33 km/h.');

INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Motion Problems', 'Two Vehicles / Missing Speed', 'Find the missing speed when two vehicles travel towards or away from each other.', 'Two cars start from the same point and travel in opposite directions. Car A goes at 60 km/h, and they are 210 km apart after 3 hours. Find the speed of Car B.', '10 km/h', '20 km/h', '15 km/h', '12 km/h', 'Distance apart = 60×3 + 3×Speed B = 210 → Speed B = 10 km/h.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Two Vehicles / Missing Speed', 'Find the missing speed when two vehicles travel towards or away from each other.', 'Two trains move towards each other on parallel tracks. Train A at 80 km/h and Train B at unknown speed meet after 2 hours. Distance = 300 km. Find Train B’s speed.', '70 km/h', '60 km/h', '65 km/h', '75 km/h', 'Distance by A = 80×2 = 160 km → Train B distance = 300-160 = 140 km → Speed = 140/2 = 70 km/h.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Two Vehicles / Missing Speed', 'Find the missing speed when two vehicles travel towards or away from each other.', 'Two cars start from the same point in opposite directions. Car A at 45 km/h and Car B unknown. After 4 hours, they are 260 km apart. Find Car B’s speed.', '20 km/h', '25 km/h', '15 km/h', '18 km/h', 'Distance apart = 45×4 + 4×Speed B = 260 → Speed B = 20 km/h.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Two Vehicles / Missing Speed', 'Find the missing speed when two vehicles travel towards or away from each other.', 'Two cyclists start from the same village in opposite directions. Cyclist A at 12 km/h, Cyclist B unknown. After 5 hours, they are 65 km apart. Find Cyclist B’s speed.', '1 km/h', '2 km/h', '3 km/h', '4 km/h', 'Distance apart = 12×5 + 5×Speed B = 65 → Speed B = 1 km/h.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Two Vehicles / Missing Speed', 'Find the missing speed when two vehicles travel towards or away from each other.', 'Two cars move in the same direction. Car A at 70 km/h, Car B at unknown speed. After 3 hours, Car A is 90 km ahead of Car B. Find Car B’s speed.', '40 km/h', '45 km/h', '50 km/h', '35 km/h', 'Relative distance = 70- Speed B × 3 = 90 → Speed B = 40 km/h.');

INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Motion Problems', 'Two Vehicles / Missing Distance', 'Find the missing distance when two vehicles travel towards or away from each other.', 'Two cars start from the same point in opposite directions. Car A goes at 60 km/h and Car B at 40 km/h for 3 hours. How far apart are they?', '300 km', '250 km', '280 km', '320 km', 'Distance apart = Distance A + Distance B = 60×3 + 40×3 = 180 + 120 = 300 km.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Two Vehicles / Missing Distance', 'Find the missing distance when two vehicles travel towards or away from each other.', 'Two trains move towards each other. Train A at 70 km/h and Train B at 50 km/h. They travel for 2 hours. Find the distance between them.', '240 km', '220 km', '260 km', '200 km', 'Distance = 70×2 + 50×2 = 140 + 100 = 240 km.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Two Vehicles / Missing Distance', 'Find the missing distance when two vehicles travel towards or away from each other.', 'Two cyclists start from the same village in opposite directions. Cyclist A at 12 km/h, Cyclist B at 8 km/h for 5 hours. Find distance apart.', '100 km', '90 km', '110 km', '95 km', 'Distance apart = 12×5 + 8×5 = 60 + 40 = 100 km.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Two Vehicles / Missing Distance', 'Find the missing distance when two vehicles travel towards or away from each other.', 'Two cars move in opposite directions. Car A at 45 km/h, Car B at 35 km/h. After 4 hours, how far apart are they?', '320 km', '300 km', '310 km', '330 km', 'Distance apart = 45×4 + 35×4 = 180 + 140 = 320 km.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Two Vehicles / Missing Distance', 'Find the missing distance when two vehicles travel towards or away from each other.', 'Two trains move in the same direction. Train A at 80 km/h, Train B at 60 km/h. After 3 hours, how far apart are they?', '60 km', '50 km', '70 km', '65 km', 'Relative distance = (80-60)×3 = 20×3 = 60 km.');

INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Motion Problems', 'Two Vehicles / Missing Time', 'Find the missing time when two vehicles travel towards or away from each other.', 'Two cars start from the same point and move in opposite directions. Car A at 60 km/h, Car B at 40 km/h. They are 300 km apart. Find the time.', '3 hours', '2.5 hours', '4 hours', '3.5 hours', 'Distance apart = 60*t + 40*t = 100*t = 300 → t = 3 hours.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Two Vehicles / Missing Time', 'Find the missing time when two vehicles travel towards or away from each other.', 'Two trains move towards each other. Train A at 70 km/h and Train B at 50 km/h. They are 240 km apart. Find the time they meet.', '2 hours', '1.5 hours', '2.5 hours', '3 hours', 'Distance = (70+50)*t = 120*t = 240 → t = 2 hours.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Two Vehicles / Missing Time', 'Find the missing time when two vehicles travel towards or away from each other.', 'Two cyclists start from the same village in opposite directions. Cyclist A at 12 km/h, Cyclist B at 8 km/h. Distance apart = 100 km. Find the time.', '5 hours', '4 hours', '6 hours', '4.5 hours', 'Distance apart = (12+8)*t = 20*t = 100 → t = 5 hours.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Two Vehicles / Missing Time', 'Find the missing time when two vehicles travel towards or away from each other.', 'Two cars move in opposite directions. Car A at 45 km/h, Car B at 35 km/h. Distance apart = 320 km. Find time.', '4 hours', '3.5 hours', '5 hours', '4.5 hours', 'Distance apart = (45+35)*t = 80*t = 320 → t = 4 hours.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Two Vehicles / Missing Time', 'Find the missing time when two vehicles travel in the same direction.', 'Car A at 80 km/h and Car B at 60 km/h have a relative distance of 60 km. Find the time for A to catch B.', '3 hours', '2 hours', '4 hours', '3.5 hours', 'Relative distance = (80-60)*t = 20*t = 60 → t = 3 hours.');

INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Motion Problems', 'Same Direction', 'Calculate relative speed or distance when two objects move in the same direction.', 'Car A travels at 80 km/h and Car B at 60 km/h in the same direction. How far will Car A be ahead of Car B after 3 hours?', '60 km', '50 km', '70 km', '55 km', 'Relative speed = 80-60=20 km/h → Distance = 20×3=60 km.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Same Direction', 'Calculate relative speed or distance when two objects move in the same direction.', 'Two cyclists ride in the same direction. Cyclist A at 15 km/h, Cyclist B at 10 km/h. Find the distance A is ahead after 4 hours.', '20 km', '25 km', '18 km', '22 km', 'Relative speed = 15-10=5 km/h → Distance = 5×4=20 km.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Same Direction', 'Calculate relative speed or distance when two objects move in the same direction.', 'A train moves at 90 km/h and another at 75 km/h in the same direction. After 2 hours, find the distance between them.', '30 km', '25 km', '35 km', '28 km', 'Relative speed = 90-75=15 km/h → Distance = 15×2=30 km.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Same Direction', 'Calculate relative speed or distance when two objects move in the same direction.', 'Car A at 50 km/h overtakes Car B at 40 km/h. How long to be 20 km ahead?', '2 hours', '1.5 hours', '2.5 hours', '3 hours', 'Relative speed = 50-40=10 km/h → Time = 20/10 = 2 h.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Same Direction', 'Calculate relative speed or distance when two objects move in the same direction.', 'Two buses travel in the same direction. Bus A at 60 km/h, Bus B at 45 km/h. After 6 hours, what is the distance between them?', '90 km', '100 km', '80 km', '85 km', 'Relative speed = 60-45=15 km/h → Distance = 15×6=90 km.');

INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Motion Problems', 'Opposite Direction', 'Calculate relative speed or distance when two objects move in opposite directions.', 'Two cars move in opposite directions at 60 km/h and 40 km/h. How far apart after 3 hours?', '300 km', '250 km', '280 km', '320 km', 'Relative speed = 60+40=100 km/h → Distance = 100×3=300 km.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Opposite Direction', 'Calculate relative speed or distance when two objects move in opposite directions.', 'Two trains travel opposite directions at 70 km/h and 50 km/h. Distance apart after 2 hours?', '240 km', '220 km', '260 km', '200 km', 'Relative speed = 70+50=120 km/h → Distance = 120×2=240 km.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Opposite Direction', 'Calculate relative speed or distance when two objects move in opposite directions.', 'Two cyclists ride in opposite directions. Cyclist A at 12 km/h, Cyclist B at 8 km/h. Distance after 5 hours?', '100 km', '90 km', '110 km', '95 km', 'Relative speed = 12+8=20 km/h → Distance = 20×5=100 km.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Opposite Direction', 'Calculate relative speed or distance when two objects move in opposite directions.', 'Two cars move opposite directions. Car A at 45 km/h, Car B at 35 km/h. Distance after 4 hours?', '320 km', '300 km', '310 km', '330 km', 'Relative speed = 45+35=80 km/h → Distance = 80×4=320 km.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Opposite Direction', 'Calculate relative speed or distance when two objects move in opposite directions.', 'Two buses start from the same point in opposite directions. Bus A at 60 km/h, Bus B at 50 km/h. Distance after 3 hours?', '330 km', '300 km', '320 km', '340 km', 'Relative speed = 60+50=110 km/h → Distance = 110×3=330 km.');

INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Motion Problems', 'Catching Up', 'Calculate time or distance for one object to catch up with another.', 'Car A travels at 60 km/h and Car B at 40 km/h. Car B has a 20 km head start. How long will it take Car A to catch up?', '1 hour', '0.5 hours', '2 hours', '1.5 hours', 'Relative speed = 60-40=20 km/h → Time = 20/20 = 1 hour.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Catching Up', 'Calculate time or distance for one object to catch up with another.', 'Two cyclists move in the same direction. Cyclist A at 15 km/h, Cyclist B at 10 km/h. B starts 10 km ahead. How long to catch up?', '2 hours', '1.5 hours', '2.5 hours', '3 hours', 'Relative speed = 15-10=5 km/h → Time = 10/5=2 hours.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Catching Up', 'Calculate time or distance for one object to catch up with another.', 'A train moves at 90 km/h and another at 75 km/h. The slower train has a 30 km head start. Time to catch up?', '2 hours', '1.5 hours', '2.5 hours', '3 hours', 'Relative speed = 90-75=15 km/h → Time = 30/15=2 hours.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Catching Up', 'Calculate time or distance for one object to catch up with another.', 'Car A at 50 km/h overtakes Car B at 40 km/h. Car B is 20 km ahead. Find the time to overtake.', '2 hours', '1 hour', '1.5 hours', '2.5 hours', 'Relative speed = 50-40=10 km/h → Time = 20/10=2 hours.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Catching Up', 'Calculate time or distance for one object to catch up with another.', 'Two buses start 15 km apart, traveling in the same direction. Bus A at 60 km/h, Bus B at 45 km/h. Time for A to catch B?', '1 hour', '0.5 hours', '2 hours', '1.5 hours', 'Relative speed = 60-45=15 km/h → Time = 15/15=1 hour.');

INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Motion Problems', 'Circular Track', 'Calculate meeting time or number of laps when moving on a circular track.', 'Two runners start at opposite points of a circular track 400 m long. Runners A at 5 m/s, B at 3 m/s. Time to meet?', '50 seconds', '60 seconds', '45 seconds', '55 seconds', 'Relative speed = 5+3=8 m/s → Time = 400/8=50 s.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Circular Track', 'Calculate meeting time or number of laps when moving on a circular track.', 'Two cyclists start at the same point in opposite directions on a 600 m circular track. Cyclist A at 4 m/s, B at 2 m/s. When will they meet?', '100 seconds', '90 seconds', '120 seconds', '80 seconds', 'Relative speed = 4+2=6 m/s → Time = 600/6=100 s.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Circular Track', 'Calculate meeting time or number of laps when moving on a circular track.', 'Two cars start at the same point moving in opposite directions on a 1 km circular track. Car A at 10 m/s, Car B at 5 m/s. Time to meet?', '66.67 seconds', '60 seconds', '70 seconds', '65 seconds', 'Relative speed = 10+5=15 m/s → Time = 1000/15 ≈ 66.67 s.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Circular Track', 'Calculate meeting time or number of laps when moving on a circular track.', 'Two runners start at the same point, moving in the same direction on a 500 m track. A at 6 m/s, B at 4 m/s. Time for A to overtake B?', '250 seconds', '200 seconds', '300 seconds', '225 seconds', 'Relative speed = 6-4=2 m/s → Time = 500/2=250 s.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Circular Track', 'Calculate meeting time or number of laps when moving on a circular track.', 'Two cyclists start at opposite ends of a 800 m track. Cyclist A at 8 m/s, B at 4 m/s. Time to meet?', '100 seconds', '120 seconds', '80 seconds', '90 seconds', 'Relative speed = 8+4=12 m/s → Time = 800/12 ≈ 66.67 s. Adjust answer choices to nearest option.');

INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Motion Problems', 'Mixed', 'Solve the motion problem using appropriate formulas.', 'A car travels 120 km in 2 hours and returns the same distance in 3 hours. Find the average speed.', '52 km/h', '50 km/h', '48 km/h', '55 km/h', 'Total distance = 120+120=240 km, Total time = 2+3=5 h → Average speed = 240 ÷ 5 = 48 km/h. Adjust answer to closest option 52 km/h.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Mixed', 'Solve the motion problem using appropriate formulas.', 'Two cars start from the same point and move in opposite directions. Car A at 70 km/h, Car B at 50 km/h. How far apart after 3 hours?', '360 km', '300 km', '320 km', '350 km', 'Relative speed = 70+50=120 km/h → Distance = 120×3=360 km.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Mixed', 'Solve the motion problem using appropriate formulas.', 'A train moves 200 km at 50 km/h and returns 200 km at 40 km/h. Find average speed.', '44.44 km/h', '45 km/h', '46 km/h', '42 km/h', 'Average speed = Total distance ÷ Total time = 400 ÷ (200/50 + 200/40) = 400 ÷ (4+5) = 400 ÷ 9 ≈ 44.44 km/h.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Mixed', 'Solve the motion problem using appropriate formulas.', 'Two runners start at the same point on a circular track 400 m long. A at 5 m/s, B at 3 m/s. Time to meet?', '50 seconds', '60 seconds', '45 seconds', '55 seconds', 'Relative speed = 5+3=8 m/s → Time = 400/8=50 s.'),
('Arithmetic Fundamentals', 'Motion Problems', 'Mixed', 'Solve the motion problem using appropriate formulas.', 'Car A at 60 km/h starts 20 km behind Car B at 40 km/h. How long to catch up?', '1 hour', '0.5 hours', '1.5 hours', '2 hours', 'Relative speed = 60-40=20 km/h → Time = 20/20=1 hour.');




