INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Order of Operations', 'PEMDAS', 'Solve using the correct order of operations.', 'Calculate: 5 + 3 × 2', '11', '16', '10', '13', 'Multiplication first: 3×2=6 → 5+6=11.'),
('Arithmetic Fundamentals', 'Order of Operations', 'PEMDAS', 'Solve using the correct order of operations.', 'Calculate: (8 + 2) × 5', '50', '30', '60', '40', 'Parentheses first: 8+2=10 → 10×5=50.'),
('Arithmetic Fundamentals', 'Order of Operations', 'PEMDAS', 'Solve using the correct order of operations.', 'Calculate: 12 ÷ 3 + 2', '6', '2', '4', '8', 'Division first: 12÷3=4 → 4+2=6.'),
('Arithmetic Fundamentals', 'Order of Operations', 'PEMDAS', 'Solve using the correct order of operations.', 'Calculate: 2 + 3 × (4 + 1)', '17', '25', '20', '15', 'Parentheses first: 4+1=5 → 3×5=15 → 2+15=17.'),
('Arithmetic Fundamentals', 'Order of Operations', 'PEMDAS', 'Solve using the correct order of operations.', 'Calculate: (6 + 4) ÷ 2 × 3', '15', '12', '18', '20', 'Parentheses: 6+4=10 → 10÷2=5 → 5×3=15.'),
('Arithmetic Fundamentals', 'Order of Operations', 'PEMDAS', 'Solve using the correct order of operations.', 'Calculate: 8 - 2 × 3 + 4', '6', '10', '8', '12', 'Multiplication first: 2×3=6 → 8-6+4=6.'),
('Arithmetic Fundamentals', 'Order of Operations', 'PEMDAS', 'Solve using the correct order of operations.', 'Calculate: 5 + 2² × 3', '17', '19', '13', '11', 'Exponents first: 2²=4 → 4×3=12 → 5+12=17.'),
('Arithmetic Fundamentals', 'Order of Operations', 'PEMDAS', 'Solve using the correct order of operations.', 'Calculate: (3 + 7) × (2 + 1)', '30', '20', '25', '35', 'Parentheses first: 3+7=10, 2+1=3 → 10×3=30.'),
('Arithmetic Fundamentals', 'Order of Operations', 'PEMDAS', 'Solve using the correct order of operations.', 'Calculate: 18 ÷ (3 × 2) + 4', '7', '10', '13', '6', 'Parentheses first: 3×2=6 → 18÷6=3 → 3+4=7.'),
('Arithmetic Fundamentals', 'Order of Operations', 'PEMDAS', 'Solve using the correct order of operations.', 'Calculate: 10 - 2 × (3 + 2) ÷ 2', '5', '6', '7', '8', 'Parentheses: 3+2=5 → 2×5=10 → 10÷2=5 → 10-5=5.');
