INSERT INTO numerical 
(category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) 
VALUES
('Arithmetic Fundamentals', 'Ratios and Proportions', 'Writing ratios in simplest form', 'Write the ratio in simplest form.', 'Simplify the ratio 24:36.', '2:3', '3:4', '4:6', '8:12', 'GCD of 24 and 36 is 12. Divide both terms by 12: 24÷12=2, 36÷12=3.'),
('Arithmetic Fundamentals', 'Ratios and Proportions', 'Comparing ratios', 'Compare the ratios.', 'Which is greater: 5:8 or 3:4?', '3:4', '5:8', 'Equal', 'Cannot be determined', 'Convert to decimals: 5/8=0.625, 3/4=0.75 → 0.75 > 0.625.'),
('Arithmetic Fundamentals', 'Ratios and Proportions', 'Solving for missing values in equivalent ratios', 'Find the missing value.', 'Complete: 4:9 = ? : 27', '12', '13', '10', '15', 'Multiply both terms by 3: 4×3=12, 9×3=27.'),
('Arithmetic Fundamentals', 'Ratios and Proportions', 'Calculating unit rates', 'Calculate the unit rate.', 'If 12 apples cost $9, what is the cost per apple?', '0.75', '0.70', '0.80', '0.65', 'Unit rate = total cost ÷ quantity = 9 ÷ 12 = 0.75 dollars/apple.'),
('Arithmetic Fundamentals', 'Ratios and Proportions', 'Using ratios to solve proportion problems', 'Solve the proportion.', 'If 5 pens cost $12.50, how much do 8 pens cost?', '20', '18', '22', '19', 'Cost per pen = 12.50 ÷ 5 = 2.50. 8 pens = 8 × 2.50 = 20.'),
('Arithmetic Fundamentals', 'Ratios and Proportions', 'Applying scale factors', 'Use the scale factor to find the actual length.', 'On a map, 1 cm represents 5 km. What is the real distance if the map shows 7 cm?', '35', '30', '40', '25', 'Scale factor = 5 km/cm. Actual distance = 7 cm × 5 km/cm = 35 km.'),
('Arithmetic Fundamentals', 'Ratios and Proportions', 'Solving problems involving direct proportion', 'Solve the direct proportion.', 'If 4 workers can build a wall in 12 days, how long will 6 workers take?', '8', '9', '10', '7', 'More workers → fewer days. Worker-days constant: 4×12=48, 48÷6=8 days.'),
('Arithmetic Fundamentals', 'Ratios and Proportions', 'Solving problems involving inverse proportion', 'Solve the inverse proportion.', 'If 10 machines produce 500 units in 4 hours, how long will 5 machines take to produce the same amount?', '8', '6', '10', '12', 'Fewer machines → more time. Machine-hours constant: 10×4=40, 40÷5=8 hours.'),
('Arithmetic Fundamentals', 'Ratios and Proportions', 'Dividing amounts in a given ratio', 'Divide the amount in the given ratio.', 'Divide $360 in the ratio 2:3. What is the smaller share?', '144', '216', '150', '200', 'Total parts=2+3=5. Value per part=360÷5=72. Smaller share=2×72=144.'),
('Arithmetic Fundamentals', 'Ratios and Proportions', 'Partnership problems', 'Solve the partnership problem.', 'A and B invest in the ratio 3:5. If the total profit is $4,000, how much does A get?', '1500', '1600', '1400', '1200', 'Total parts=3+5=8. A''s share=(3/8)×4000=1500.');