

INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Basic Formula', 'Finding Distance', 'Choose the correct answer.', 'A car travels at 60 km/h for 2.5 hours. How far does it travel?', '120 km', '130 km', '140 km', '150 km', '150 km'),
('Arithmetic Fundamentals', 'Basic Formula', 'Finding Speed', 'Choose the correct answer.', 'If a cyclist covers 45 km in 3 hours, what is the speed?', '10 km/h', '12 km/h', '14 km/h', '15 km/h', '15 km/h'),
('Arithmetic Fundamentals', 'Basic Formula', 'Finding Time', 'Choose the correct answer.', 'A train travels 180 km at 90 km/h. How long will it take?', '1 hour', '1.5 hours', '2 hours', '2.5 hours', '2 hours'),
('Arithmetic Fundamentals', 'Relative Speed', 'Same Direction', 'Choose the correct answer.', 'Two cars travel in the same direction at 70 km/h and 55 km/h. If the faster car is 150 km behind, how long will it take to catch up?', '8 hours', '9 hours', '10 hours', '12 hours', '10 hours'),
('Arithmetic Fundamentals', 'Relative Speed', 'Opposite Direction', 'Choose the correct answer.', 'Two cyclists start from points 120 km apart and move towards each other at 20 km/h and 15 km/h. How long until they meet?', '2 hours', '3 hours', '3.5 hours', '4 hours', '3.5 hours'),
('Arithmetic Fundamentals', 'Average Speed', 'Different Segments', 'Choose the correct answer.', 'A person travels from A to B at 60 km/h and returns at 40 km/h. What is the average speed for the trip?', '45 km/h', '46 km/h', '47 km/h', '48 km/h', '48 km/h'),
('Arithmetic Fundamentals', 'Conversion', 'km/h to m/s', 'Choose the correct answer.', 'Convert 72 km/h into m/s.', '18 m/s', '19.5 m/s', '20 m/s', '21 m/s', '20 m/s'),
('Arithmetic Fundamentals', 'Conversion', 'm/s to km/h', 'Choose the correct answer.', 'Convert 15 m/s into km/h.', '50 km/h', '52 km/h', '54 km/h', '54 km/h', '54 km/h'),
('Arithmetic Fundamentals', 'Overtaking', 'Same Direction', 'Choose the correct answer.', 'A car moving at 90 km/h overtakes a truck moving at 60 km/h. If the car is 150 m and the truck 200 m, how long will it take to overtake?', '15 seconds', '18 seconds', '20 seconds', '22 seconds', '20 seconds'),
('Arithmetic Fundamentals', 'Boat and Stream', 'Upstream-Downstream', 'Choose the correct answer.', 'A boat can go 12 km downstream in 40 minutes and 8 km upstream in 40 minutes. Find the speed in still water.', '10 km/h', '11 km/h', '12 km/h', '13 km/h', '12 km/h'),
('Arithmetic Fundamentals', 'Train', 'Platform', 'Choose the correct answer.', 'A train 180 m long passes a platform 120 m long in 12 seconds. Find the speed in km/h.', '80 km/h', '85 km/h', '90 km/h', '95 km/h', '90 km/h'),
('Arithmetic Fundamentals', 'Train', 'Another Train', 'Choose the correct answer.', 'Two trains of lengths 150 m and 200 m are moving in opposite directions at 60 km/h and 40 km/h. How many seconds to completely cross each other?', '10 seconds', '12 seconds', '14 seconds', '15 seconds', '12 seconds'),
('Arithmetic Fundamentals', 'Chasing', 'Different Start Times', 'Choose the correct answer.', 'A runner starts 30 min before another and runs at 8 km/h. The second runs at 12 km/h. How long to catch up?', '1.5 hours', '2 hours', '2.5 hours', '3 hours', '2 hours'),
('Arithmetic Fundamentals', 'Varying Speeds', 'Segment Travel', 'Choose the correct answer.', 'A bus travels first 100 km at 50 km/h and next 150 km at 75 km/h. Find total travel time.', '3.5 hours', '4 hours', '4.5 hours', '5 hours', '4 hours'),
('Arithmetic Fundamentals', 'Real-life', 'Travel Planning', 'Choose the correct answer.', 'You must reach 150 km away in 2.5 hours. What constant speed is needed?', '55 km/h', '60 km/h', '65 km/h', '70 km/h', '60 km/h');
