INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Time and Work', 'Calculating individual work rates', 'Find the individual work rate.', 'A can finish a job in 10 days. What is A’s work rate per day?', '1/10', '10', '1/5', '5', 'Work rate = 1 job ÷ 10 days = 1/10 job per day.'),
('Arithmetic Fundamentals', 'Time and Work', 'Finding total work rate when working together', 'Find the combined work rate.', 'A can finish a job in 8 days, B can finish in 12 days. What is their combined rate per day?', '5/24', '1/5', '1/6', '7/24', 'A’s rate = 1/8, B’s rate = 1/12. Combined = 1/8 + 1/12 = (3+2)/24 = 5/24 job/day.'),
('Arithmetic Fundamentals', 'Time and Work', 'Determining time required to complete a task', 'Find the time needed to finish the job.', 'A and B can do a job in 15 days together. How long will it take them to finish if they work at the same rate individually?', '30', '15', '20', '25', 'Together in 15 days means combined rate = 1/15. Each has the same rate, so each does 1/30 of the job per day. Alone, they take 30 days.'),
('Arithmetic Fundamentals', 'Time and Work', 'Work completion with one person leaving', 'Find the time to complete the work.', 'A and B together can do a job in 12 days. They work together for 6 days, then A leaves. If B alone finishes in 12 more days, how long would B take to do the whole job alone?', '24', '18', '20', '15', 'In 6 days together: 6×(1/12)=1/2 job done. Remaining 1/2 done by B in 12 days → rate of B = (1/2)/12 = 1/24 job/day. So B alone takes 24 days.'),
('Arithmetic Fundamentals', 'Time and Work', 'Comparing efficiency of workers', 'Compare efficiency.', 'A is twice as efficient as B. If B can finish a task in 18 days, how many days will A take?', '9', '12', '6', '8', 'Twice as efficient → takes half the time: 18 ÷ 2 = 9 days.'),
('Arithmetic Fundamentals', 'Time and Work', 'Inverse proportion with workers and time', 'Solve the inverse proportion problem.', '8 workers can complete a job in 15 days. How many workers are needed to finish in 10 days (same efficiency)?', '12', '10', '15', '8', 'Workers × Days = constant → 8×15 = 120. For 10 days: 120 ÷ 10 = 12 workers.'),
('Arithmetic Fundamentals', 'Time and Work', 'Solving partial work problems', 'Find the total time taken.', 'A can do a job in 20 days. He works for 8 days, then B (who can do it in 30 days) joins him. How long to finish the rest?', '8 + 6', '12', '10', '14', 'In 8 days, A does 8×(1/20) = 2/5. Remaining = 3/5. Combined rate = 1/20 + 1/30 = 1/12. Time = (3/5) ÷ (1/12) = 36/5 = 7.2 days. Total = 8 + 7.2 ≈ 15.2 days.'),
('Arithmetic Fundamentals', 'Time and Work', 'Practical scenario: filling tanks', 'Find the time to fill the tank.', 'A pipe can fill a tank in 4 hours, another in 6 hours. If both are opened together, how long will it take to fill the tank?', '2.4', '2', '3', '2.5', 'Rate = 1/4 + 1/6 = 5/12 tank/hour. Time = 1 ÷ (5/12) = 12/5 = 2.4 hours.'),
('Arithmetic Fundamentals', 'Time and Work', 'Finding work done in fractional time', 'Find the fraction of work completed.', 'A can finish a task in 5 hours. What fraction of the work will A complete in 2 hours?', '2/5', '3/5', '1/5', '4/5', 'Rate = 1/5 per hour. In 2 hours: 2 × (1/5) = 2/5.'),
('Arithmetic Fundamentals', 'Time and Work', 'Identifying bottlenecks in collaboration', 'Identify the bottleneck.', 'Three workers A, B, and C can produce 60 units/day, 50 units/day, and 40 units/day respectively. If the task requires assembling 100 units/day, which worker limits the output?', 'C', 'A', 'B', 'None', 'C produces the fewest (40/day), thus limiting total production.');
