INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Arithmetic Fundamentals', 'Unit Conversion', 'Units Needed', 'Solve to find the total number of units required.', 'Rodriguez needs 9300 kilos of soil. If soil is sold in bags of 50 kilos, how many bags does he need to buy?', '186', '180', '190', '200', 'Total bags = 9300 ÷ 50 = 186.'),
('Arithmetic Fundamentals', 'Unit Conversion', 'Units Needed', 'Solve to find the total number of units required.', 'A factory needs 12,000 liters of oil. If each barrel contains 250 liters, how many barrels are required?', '48', '45', '50', '52', 'Total barrels = 12,000 ÷ 250 = 48.'),
('Arithmetic Fundamentals', 'Unit Conversion', 'Units Needed', 'Solve to find the total number of units required.', 'A bookstore orders 1,500 books. If each box contains 30 books, how many boxes are needed?', '50', '45', '55', '60', 'Total boxes = 1500 ÷ 30 = 50.'),
('Arithmetic Fundamentals', 'Unit Conversion', 'Units Needed', 'Solve to find the total number of units required.', 'A construction site needs 7,500 bricks. If each pallet contains 250 bricks, how many pallets should be ordered?', '30', '28', '32', '35', 'Total pallets = 7,500 ÷ 250 = 30.'),
('Arithmetic Fundamentals', 'Unit Conversion', 'Units Needed', 'Solve to find the total number of units required.', 'A farmer has 2,400 liters of milk. If each container holds 60 liters, how many containers are required?', '40', '35', '45', '50', 'Total containers = 2,400 ÷ 60 = 40.'),
('Arithmetic Fundamentals', 'Unit Conversion', 'Units Needed', 'Solve to find the total number of units required.', 'A factory produces 18,000 screws. If each packet contains 150 screws, how many packets are needed?', '120', '100', '125', '115', 'Total packets = 18,000 ÷ 150 = 120.'),
('Arithmetic Fundamentals', 'Unit Conversion', 'Units Needed', 'Solve to find the total number of units required.', 'A shipping company needs to transport 9,600 kg of goods. Each container can hold 400 kg. How many containers are needed?', '24', '20', '25', '30', 'Total containers = 9,600 ÷ 400 = 24.'),
('Arithmetic Fundamentals', 'Unit Conversion', 'Units Needed', 'Solve to find the total number of units required.', 'A school orders 1,200 pencils. Each box contains 40 pencils. How many boxes are required?', '30', '25', '35', '40', 'Total boxes = 1,200 ÷ 40 = 30.'),
('Arithmetic Fundamentals', 'Unit Conversion', 'Units Needed', 'Solve to find the total number of units required.', 'A warehouse stores 15,000 bottles of juice. Each crate contains 250 bottles. How many crates are needed?', '60', '55', '65', '70', 'Total crates = 15,000 ÷ 250 = 60.'),
('Arithmetic Fundamentals', 'Unit Conversion', 'Units Needed', 'Solve to find the total number of units required.', 'A bakery needs 3,600 eggs. If each carton holds 12 eggs, how many cartons are required?', '300', '280', '320', '350', 'Total cartons = 3,600 ÷ 12 = 300.');
