INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Algebra', 'Linear Equations', 'Single-Variable Solutions', 'Choose the correct answer.', 'Solve for x: 3x + 7 = 22.', '5', '4', '6', '7', 'Subtract 7: 3x = 15 → x = 15 ÷ 3 = 5'),
('Algebra', 'Linear Equations', 'Age Word Problems', 'Choose the correct answer.', 'John is 4 years older than Mary. If their total age is 28, how old is Mary?', '12', '10', '14', '16', 'Let Mary = x, John = x + 4 → x + (x + 4) = 28 → 2x + 4 = 28 → 2x = 24 → x = 12'),
('Algebra', 'Linear Equations', 'Money Word Problems', 'Choose the correct answer.', 'A person has $50. He spends $20 on groceries and the rest on books. How much did he spend on books?', '30', '20', '25', '35', 'Total = 50, groceries = 20, books = 50 − 20 = 30'),
('Algebra', 'Linear Equations', 'Mixture and Concentration', 'Choose the correct answer.', 'A solution contains 10% salt. How many liters of pure water must be added to 5 liters of this solution to reduce the concentration to 5%?', '5', '4', '6', '7', 'Let x = liters added: 0.1*5 = 0.05*(5 + x) → 0.5 = 0.25 + 0.05x → 0.05x = 0.25 → x = 5'),
('Algebra', 'Linear Equations', 'Single-Variable Solutions', 'Choose the correct answer.', 'Solve for y: 2y − 9 = 7.', '8', '7', '9', '10', 'Add 9: 2y = 16 → y = 16 ÷ 2 = 8'),
('Algebra', 'Linear Equations', 'Age Word Problems', 'Choose the correct answer.', 'The sum of ages of a father and son is 50. Father is 30 years older than the son. How old is the son?', '10', '15', '20', '12', 'Let son = x, father = x + 30 → x + x + 30 = 50 → 2x = 20 → x = 10'),
('Algebra', 'Linear Equations', 'Money Word Problems', 'Choose the correct answer.', 'A man buys 3 pens and 2 notebooks for $12. If a pen costs $2, what is the cost of one notebook?', '3', '2', '4', '5', '3 pens = 3*2 = 6 → remaining 6 for 2 notebooks → 6 ÷ 2 = 3 each'),
('Algebra', 'Linear Equations', 'Checking Solutions', 'Choose the correct answer.', 'If x = 4, check if it satisfies the equation 5x − 3 = 17.', 'Yes', 'No', 'Cannot determine', 'Only approximately', 'Substitute: 5*4 − 3 = 20 − 3 = 17 → satisfies the equation → Yes'),
('Algebra', 'Linear Equations', 'Real-World Modeling', 'Choose the correct answer.', 'The cost C (in $) of buying x kg of apples is C = 3x + 2. What is the cost of 5 kg?', '17', '15', '18', '20', 'C = 3*5 + 2 = 15 + 2 = 17');
