INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Algebra', 'Quadratic Equations', 'Factoring', 'Choose the correct answer.', 'Factor: \\(x^2 + 5x + 6\\).', '(x + 2)(x + 3)', '(x + 1)(x + 6)', '(x + 2)(x + 2)', '(x + 3)(x + 3)', 'Find two numbers that multiply to 6 and add to 5 → 2 and 3 → \\((x+2)(x+3)\\)'),
('Algebra', 'Quadratic Equations', 'Solving by Factoring', 'Choose the correct answer.', 'Solve: \\(x^2 + 5x + 6 = 0\\).', 'x = -2, -3', 'x = 2, 3', 'x = -1, -6', 'x = 1, 6', 'Factor: \\((x+2)(x+3)=0\\) → x+2=0 → x=-2, x+3=0 → x=-3'),
('Algebra', 'Quadratic Equations', 'Completing the Square', 'Choose the correct answer.', 'Solve: \\(x^2 + 6x - 7 = 0\\) by completing the square.', 'x = 1, -7', 'x = -1, 7', 'x = 7, -1', 'x = -1, -7', 'x^2 + 6x = 7 → x^2 + 6x + 9 = 16 → \\((x+3)^2=16\\) → x+3=±4 → x=1,-7'),
('Algebra', 'Quadratic Equations', 'Quadratic Formula', 'Choose the correct answer.', 'Solve: \\(2x^2 - 4x - 6 = 0\\) using the quadratic formula.', 'x = 3, -1', 'x = 1, -3', 'x = 2, -3', 'x = -2, 3', 'x = [-(-4)±√((-4)^2−4*2*(-6))]/(2*2) → x=(4±√64)/4 → x=3,-1'),
('Algebra', 'Quadratic Equations', 'Word Problems', 'Choose the correct answer.', 'The area of a rectangle is 12 m^2, length is 4 m more than width. Find width.', '2', '3', '4', '6', 'Let width=x, length=x+4 → x(x+4)=12 → x^2+4x−12=0 → solve x=2,-6 → width=2'),
('Algebra', 'Quadratic Equations', 'Graphing Parabolas', 'Choose the correct answer.', 'For \\(y = x^2 - 4x + 3\\), find the vertex.', '(2, -1)', '(1, 2)', '(2, 1)', '(-2, 1)', 'Vertex formula: x=-b/2a=4/2=2 → y=2^2-4*2+3=-1 → vertex=(2,-1)'),
('Algebra', 'Quadratic Equations', 'Factoring', 'Choose the correct answer.', 'Factor: \\(x^2 - 9\\).', '(x - 3)(x + 3)', '(x - 9)(x + 1)', '(x - 1)(x + 9)', '(x - 3)(x - 3)', 'Difference of squares: x^2 - 9 = (x-3)(x+3)'),
('Algebra', 'Quadratic Equations', 'Solving by Factoring', 'Choose the correct answer.', 'Solve: \\(x^2 - 5x + 6 = 0\\).', 'x = 2, 3', 'x = -2, -3', 'x = 1, 6', 'x = -1, -6', 'Factor: (x-2)(x-3)=0 → x=2,3'),
('Algebra', 'Quadratic Equations', 'Quadratic Formula', 'Choose the correct answer.', 'Solve: \\(x^2 + x - 6 = 0\\) using quadratic formula.', 'x = 2, -3', 'x = -2, 3', 'x = 1, -6', 'x = -1, 6', 'x=[-1±√(1+24)]/2=[-1±5]/2 → x=2,-3'),
('Algebra', 'Quadratic Equations', 'Completing the Square', 'Choose the correct answer.', 'Solve: \\(x^2 - 6x + 5 = 0\\) by completing the square.', 'x = 1, 5', 'x = -1, -5', 'x = 2, 3', 'x = -2, -3', 'x^2 -6x = -5 → x^2-6x+9=4 → \\((x-3)^2=4\\) → x-3=±2 → x=1,5');
