INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Algebra', 'Systems of Equations', 'Substitution', 'Choose the correct answer.', 'Solve the system: x + y = 10, x − y = 2. Find x.', '6', '4', '5', '7', 'Add equations: (x+y)+(x−y)=10+2 → 2x=12 → x=6'),
('Algebra', 'Systems of Equations', 'Substitution', 'Choose the correct answer.', 'Solve the system: 2x + y = 8, y = x + 2. Find x.', '2', '3', '4', '1', 'Substitute y=x+2 into 2x+y=8 → 2x + (x+2)=8 → 3x+2=8 → 3x=6 → x=2'),
('Algebra', 'Systems of Equations', 'Elimination', 'Choose the correct answer.', 'Solve the system: 3x + 2y = 12, 5x + 2y = 16. Find y.', '0', '2', '1', '4', 'Subtract equations: (5x+2y)−(3x+2y)=16−12 → 2x=4 → x=2 → 3*2+2y=12 → 6+2y=12 → y=3'),
('Algebra', 'Systems of Equations', 'Graphical Solutions', 'Choose the correct answer.', 'Solve graphically: y = 2x + 1 and y = −x + 4. Find intersection point.', '(1,3)', '(0,1)', '(2,5)', '(-1, -1)', 'Set 2x+1 = −x+4 → 3x=3 → x=1 → y=2*1+1=3 → (1,3)'),
('Algebra', 'Systems of Equations', 'Mixture Problems', 'Choose the correct answer.', 'A chemist mixes 3L of solution A with 5% concentration and 2L of solution B with 10% concentration. What is the concentration of the mixture?', '7%', '6%', '8%', '9%', 'Total salt = 3*5% + 2*10% = 15%+20%=35% over 5L → 35/5=7%'),
('Algebra', 'Systems of Equations', 'Allocation Problems', 'Choose the correct answer.', 'Two people share $100 such that one gets $20 more than the other. How much does the smaller share receive?', '40', '50', '45', '35', 'Let smaller = x → larger = x+20 → x + (x+20)=100 → 2x=80 → x=40'),
('Algebra', 'Systems of Equations', 'One/None/Infinite Solutions', 'Choose the correct answer.', 'Determine the number of solutions: 2x + y = 4, 4x + 2y = 8.', 'Infinite', 'One', 'None', 'Cannot determine', 'Second equation is multiple of the first → infinitely many solutions'),
('Algebra', 'Systems of Equations', 'One/None/Infinite Solutions', 'Choose the correct answer.', 'Determine the number of solutions: x + y = 5, x + y = 8.', 'None', 'One', 'Infinite', 'Cannot determine', 'Parallel lines → no solution'),
('Algebra', 'Systems of Equations', 'Substitution', 'Choose the correct answer.', 'Solve the system: y = 3x − 2, 2x + y = 8. Find y.', '4', '5', '6', '3', 'Substitute y=3x−2 into 2x+y=8 → 2x+(3x−2)=8 → 5x−2=8 → 5x=10 → x=2 → y=3*2−2=4'),
('Algebra', 'Systems of Equations', 'Elimination', 'Choose the correct answer.', 'Solve the system: 4x − y = 5, 2x + y = 1. Find x.', '1.5', '2', '1', '2.5', 'Add equations: (4x−y)+(2x+y)=5+1 → 6x=6 → x=1 → check carefully: 4*1−y=5 → y=−1 → 2*1+(-1)=1 ✔');
