INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Basic Geometry', 'Angles', 'Triangle Angles', 'Choose the correct answer.', 'A triangle has angles 50° and 60°. Find the third angle.', '70°', '80°', '90°', '60°', 'Sum of angles in triangle = 180 → 180−50−60=70°'),
('Basic Geometry', 'Angles', 'Types of Triangles', 'Choose the correct answer.', 'A triangle has angles 90°, 45°, 45°. What type of triangle is it?', 'Right isosceles', 'Acute scalene', 'Equilateral', 'Obtuse isosceles', 'One angle is 90° → right triangle; two equal angles → isosceles → right isosceles'),
('Basic Geometry', 'Angles', 'Sum of Angles Property', 'Choose the correct answer.', 'In a triangle, angles are in ratio 2:3:4. Find the largest angle.', '80°', '90°', '100°', '120°', 'Sum = 2x+3x+4x=9x=180 → x=20 → largest = 4x=80°'),
('Basic Geometry', 'Angles', 'Unknown Angles', 'Choose the correct answer.', 'In an isosceles triangle, two equal angles are 50° each. Find the third angle.', '80°', '60°', '70°', '90°', 'Sum of angles = 180 → third = 180−50−50=80°'),
('Basic Geometry', 'Angles', 'Unknown Angles', 'Choose the correct answer.', 'In an equilateral triangle, find each angle.', '60°', '90°', '45°', '50°', 'All angles are equal and sum =180 → each = 60°'),
('Basic Geometry', 'Angles', 'Triangle Angles', 'Choose the correct answer.', 'A triangle has angles 70° and 40°. Find the third angle.', '70°', '60°', '50°', '80°', 'Third angle = 180−70−40=70°'),
('Basic Geometry', 'Angles', 'Types of Triangles', 'Choose the correct answer.', 'A triangle has angles 100°, 40°, 40°. Type?', 'Obtuse isosceles', 'Acute scalene', 'Right isosceles', 'Equilateral', 'One angle >90 → obtuse; two equal → isosceles → obtuse isosceles'),
('Basic Geometry', 'Angles', 'Sum of Angles Property', 'Choose the correct answer.', 'Angles are in ratio 3:3:2. Find each angle.', '67.5°, 67.5°, 45°', '60°, 60°, 60°', '70°, 70°, 40°', '50°, 50°, 80°', 'Sum=3x+3x+2x=8x=180 → x=22.5 → angles=67.5,67.5,45°'),
('Basic Geometry', 'Angles', 'Unknown Angles', 'Choose the correct answer.', 'Isosceles triangle has vertex angle 40°. Find base angles.', '70° each', '60° each', '50° each', '80° each', 'Sum=180 → 2*base +40=180 → base=70°'),
('Basic Geometry', 'Angles', 'Triangle Angles', 'Choose the correct answer.', 'Angles of a triangle are consecutive even numbers. Sum=180°. Find angles.', '58°, 60°, 62°', '60°, 62°, 64°', '56°, 58°, 60°', '54°, 56°, 58°', 'Let angles= x, x+2, x+4 → sum=3x+6=180 → 3x=174 → x=58 → angles=58,60,62°');
