INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Word Problems', 'Quantitative Reasoning', 'Multi-Step Arithmetic', 'Choose the correct answer.', 'A shop sells 3 pencils at $2 each and 2 erasers at $3 each. What is the total cost?', '$12', '$10', '$15', '$14', 'Pencils: 3*2=6, Erasers: 2*3=6 → Total=6+6=12'),
('Word Problems', 'Quantitative Reasoning', 'Logical Deduction', 'Choose the correct answer.', 'If 5 workers can paint a wall in 8 hours, how long for 10 workers?', '4 hours', '6 hours', '8 hours', '10 hours', 'Doubling workers halves time: 8/2=4 hours'),
('Word Problems', 'Quantitative Reasoning', 'Combining Arithmetic Operations', 'Choose the correct answer.', 'A train travels 120 km at 60 km/h and then 180 km at 90 km/h. What is total travel time?', '4 hours', '3 hours', '5 hours', '6 hours', 'Time1=120/60=2h, Time2=180/90=2h → Total=4h'),
('Word Problems', 'Quantitative Reasoning', 'Analyzing Complex Problems', 'Choose the correct answer.', 'A basket has apples and oranges. Apples=3 more than oranges. Total fruits=23. How many apples?', '13', '10', '12', '15', 'Let oranges=x → apples=x+3 → x+x+3=23 → 2x+3=23 → 2x=20 → apples=10+3=13'),
('Word Problems', 'Quantitative Reasoning', 'Multi-Step Arithmetic', 'Choose the correct answer.', 'A book costs $15. A student buys 3 books and pays with a $100 bill. Change?', '$55', '$45', '$50', '$60', '3*15=45 → 100-45=55'),
('Word Problems', 'Quantitative Reasoning', 'Logical Deduction', 'Choose the correct answer.', 'Tom is twice as old as Mary. Sum of ages=36. How old is Tom?', '24', '18', '12', '20', 'Let Mary=x → Tom=2*x → x+2*x=36 → Tom=2*12=24'),
('Word Problems', 'Quantitative Reasoning', 'Combining Arithmetic Operations', 'Choose the correct answer.', 'A car travels 50 km at 25 km/h and 100 km at 50 km/h. Total time?', '4 hours', '5 hours', '6 hours', '7 hours', 'Time1=50/25=2h, Time2=100/50=2h → Total=4h'),
('Word Problems', 'Quantitative Reasoning', 'Analyzing Complex Problems', 'Choose the correct answer.', 'A container holds 5 liters. If 3 containers are filled, how many liters total?', '15 L', '10 L', '20 L', '12 L', '3*5=15 L'),
('Word Problems', 'Quantitative Reasoning', 'Multi-Step Arithmetic', 'Choose the correct answer.', 'A man buys 2 shirts at $20 each and 3 trousers at $30 each. Total cost?', '$130', '$120', '$110', '$140', '2*20=40, 3*30=90 → Total=40+90=130'),
('Word Problems', 'Quantitative Reasoning', 'Logical Deduction', 'Choose the correct answer.', 'A bus can carry 50 passengers. How many buses for 275 passengers?', '6', '5', '7', '4', '275/50=5.5 → round up → 6 buses');
