INSERT INTO numerical (category, type, sub_type, instruction, question, correct_answer, wrong_answer1, wrong_answer2, wrong_answer3, explanation) VALUES
('Word Problems', 'Real-Life Scenarios', 'Budgeting/Cost Analysis', 'Choose the correct answer.', 'A family has a budget of $500. Rent=$300, groceries=$120. How much is left for other expenses?', '$80', '$70', '$100', '$90', 'Total expenses = 300+120=420 → 500−420=80'),
('Word Problems', 'Real-Life Scenarios', 'Budgeting/Cost Analysis', 'Choose the correct answer.', 'A shop sells 4 items: $10, $15, $20, $25. Find the total cost.', '$70', '$60', '$75', '$65', 'Total = 10+15+20+25=70'),
('Word Problems', 'Real-Life Scenarios', 'Resource Allocation', 'Choose the correct answer.', 'A teacher has 120 pencils to distribute equally among 8 students. How many each?', '15', '12', '10', '20', '120 ÷ 8 = 15 pencils each'),
('Word Problems', 'Real-Life Scenarios', 'Budgeting/Cost Analysis', 'Choose the correct answer.', 'A company earns $2000 revenue and spends $1500. Profit?', '$500', '$400', '$600', '$450', 'Profit = Revenue−Expenses = 2000−1500=500'),
('Word Problems', 'Real-Life Scenarios', 'Comparing Costs', 'Choose the correct answer.', 'Store A sells 5 kg rice for $25. Store B sells 8 kg for $36. Which store is cheaper per kg?', 'Store B', 'Store A', 'Both same', 'Cannot determine', 'Store A: 25/5=5 per kg, Store B: 36/8=4.5 per kg → Store B is cheaper'),
('Word Problems', 'Real-Life Scenarios', 'Resource Allocation', 'Choose the correct answer.', 'A project needs 12 workers for 8 days. If only 6 workers are available, how many days needed?', '16 days', '12 days', '14 days', '10 days', 'Work is constant → fewer workers → more days → 12×8=6×x → x=16'),
('Word Problems', 'Real-Life Scenarios', 'Budgeting/Cost Analysis', 'Choose the correct answer.', 'A family spends $60 on food, $40 on transport, $50 on utilities. Total spent?', '$150', '$140', '$130', '$160', 'Total = 60+40+50=150'),
('Word Problems', 'Real-Life Scenarios', 'Comparing Costs', 'Choose the correct answer.', 'Product X costs $120 for 10 units. Product Y costs $150 for 15 units. Cheaper per unit?', 'Product Y', 'Product X', 'Both same', 'Cannot determine', 'X: 120/10=12 per unit, Y:150/15=10 per unit → Product Y is cheaper'),
('Word Problems', 'Real-Life Scenarios', 'Resource Allocation', 'Choose the correct answer.', 'A water tank has 600 L. If 4 taps fill equally in 3 hours, how much each tap contributes?', '150 L', '100 L', '200 L', '120 L', '600 ÷ 4 = 150 L per tap'),
('Word Problems', 'Real-Life Scenarios', 'Budgeting/Cost Analysis', 'Choose the correct answer.', 'Monthly salary=$2500. Rent=$900, bills=$400, groceries=$500. Remaining savings?', '$700', '$800', '$600', '$750', 'Expenses=900+400+500=1800 → Savings=2500−1800=700');
